const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function harness(initial='running'){
 let next=0;const timers=new Map(),param=()=>({value:0,setTargetAtTime(n){this.value=n;},setValueAtTime(n){this.value=n;},linearRampToValueAtTime(n){this.value=n;},exponentialRampToValueAtTime(n){this.value=n;}});
 const node=()=>({gain:param(),frequency:param(),pan:param(),Q:param(),threshold:param(),knee:param(),ratio:param(),attack:param(),release:param(),connect(){},disconnect(){},start(){this.started=true;},stop(at){this.stopped=true;if(at===undefined)this.onended?.();}});
 class Context{constructor(){this.sampleRate=1000;this.currentTime=0;this.state=initial;this.destination=node();}createGain(){return node();}createDynamicsCompressor(){return node();}createConvolver(){return node();}createBuffer(c,n){return {getChannelData:()=>new Float32Array(n)};}createOscillator(){return node();}createStereoPanner(){return node();}createBufferSource(){return node();}createBiquadFilter(){return node();}resume(){return Promise.resolve();}close(){return Promise.resolve();}}
 const context={window:{AudioContext:Context},setTimeout:f=>{timers.set(++next,f);return next;},clearTimeout:i=>timers.delete(i),Math};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../audio.js'),'utf8'),context);return {audio:new context.window.EclipseSound(),timers};
}
const path=require('node:path');
test('muting stops scheduled effects and ambient voices immediately and respects saved volume',()=>{
 const {audio:a,timers}=harness();a.configure({volume:40,music:20,musicEnabled:true},false);a.play('start');a.setBattle(true);assert.ok(a.sources.size);assert.equal(timers.size,1);a.configure({},true);assert.equal(a.master.gain.value,0);assert.equal(a.sources.size,0);assert.equal(a.musicSources.size,0);assert.equal(timers.size,0);a.configure({},false);assert.equal(a.master.gain.value,.4*.68);assert.equal(timers.size,1);a.dispose();assert.equal(timers.size,0);
});
test('pause and repeated settings updates never layer ambient loops; previews work while paused',()=>{
 const {audio:a,timers}=harness();a.unlock();a.setBattle(true);for(let i=0;i<10;i++)a.configure({volume:50},false);assert.equal(timers.size,1);a.setSuspended(true);assert.equal(timers.size,0);assert.equal(a.musicSources.size,0);const ev={fx:'fire',kind:'skill',actor:{side:'ally'},impacts:[{type:'damage',value:20}]};a.combat(ev);assert.equal(a.sources.size,0);a.combat(ev,1,true);assert.ok(a.sources.size);a.setSuspended(false);assert.equal(timers.size,1);a.setBattle(false);assert.equal(timers.size,0);a.dispose();
});
test('regional and boss music replaces previous loop; new feedback respects mute and cancellation',()=>{const {audio:a,timers}=harness();a.unlock();for(const theme of ['moon','ember','frost','void','dawn','tempest']){a.setBattle(true,{theme,boss:true});assert.equal(a.theme,theme);assert.equal(timers.size,1);assert.ok(a.musicSources.size>10);}a.setBattle(false);assert.equal(timers.size,0);for(const fx of ['ascend','equip','unequip','travel','loot','loot-rare']){a.play(fx);assert.ok(a.sources.size,fx);a.stopEffects();assert.equal(a.sources.size,0);}a.settlement(true,{experience:[{level:2,fromLevel:1}],gear:[{template:'relic-ur'}]});assert.ok(a.sources.size>15);a.configure({},true);a.play('ascend');a.settlement(true,{gear:[]});assert.equal(a.sources.size,0);assert.equal(a.musicSources.size,0);a.dispose();});
test('summon music starts after a user unlock and changes scenes without layered loops',async()=>{
 const {audio:a,timers}=harness();a.setLobby(true);assert.equal(a.ctx,null);assert.equal(timers.size,0);await a.unlock();assert.equal(timers.size,1);for(let i=0;i<5;i++)a.setLobby(true);assert.equal(timers.size,1);a.setSuspended(true);assert.equal(timers.size,0);a.play('summon');assert.ok(a.sources.size>5);a.setSuspended(false);assert.equal(timers.size,1);a.setLobby(false);assert.equal(timers.size,0);a.setBattle(true,{theme:'dawn'});assert.equal(timers.size,1);a.setLobby(true);assert.equal(timers.size,1);a.configure({musicEnabled:false},false);assert.equal(timers.size,0);a.play('ur');assert.ok(a.sources.size);a.dispose();
});
test('first summon waits for async browser resume and starts its complete sound after activation',async()=>{
 const {audio:a,timers}=harness('suspended');await a.unlock();let finish,resumes=0;a.ctx.resume=()=>{resumes++;return new Promise(resolve=>finish=()=>{a.ctx.state='running';resolve();});};a.setLobby(true);a.play('summon');a.unlock();assert.equal(resumes,1);assert.equal(a.sources.size,0);assert.equal(timers.size,0);finish();await a.resumePromise;assert.ok(a.sources.size>5);assert.equal(timers.size,1);a.dispose();
});
test('resume rejection can be retried and late activation never revives a cancelled or muted effect',async()=>{
 const {audio:a}=harness('interrupted');await a.unlock();a.ctx.resume=()=>Promise.reject(new Error('gesture required'));a.play('summon');assert.equal(await a.resumePromise,false);assert.equal(a.sources.size,0);
 let finish;a.ctx.resume=()=>new Promise(resolve=>finish=()=>{a.ctx.state='running';resolve();});a.play('summon');a.configure({},true);finish();await a.resumePromise;assert.equal(a.sources.size,0);a.configure({},false);a.ctx.state='interrupted';a.play('ascend');a.stopEffects();finish();await a.resumePromise;assert.equal(a.sources.size,0);a.play('summon');assert.ok(a.sources.size>5);a.dispose();
});
test('zero master/music volume suppresses ambient scheduling while sound preferences persist',async()=>{const {audio:a,timers}=harness();a.setLobby(true);await a.unlock();a.configure({volume:0},false);assert.equal(timers.size,0);a.configure({volume:65,music:0},false);assert.equal(timers.size,0);a.configure({music:25},false);assert.equal(timers.size,1);a.dispose();});

test('UR and SP fanfares are distinct, output audio, and stop fully when skipped or muted',()=>{const {audio:a}=harness();a.unlock();const sizes=[];for(const fx of ['summon-charge','ur','sp','sp-prism']){a.play(fx);sizes.push(a.sources.size);assert.ok(a.sources.size>0,fx);a.stopEffects();assert.equal(a.sources.size,0);}assert.ok(sizes[2]>sizes[1]);assert.ok(sizes[3]>sizes[2]);a.configure({},true);a.play('sp-prism');assert.equal(a.sources.size,0);a.dispose();});
