const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../core.js'),S=require('../covenant-skills.js'),J=require('../journey.js').install(C);
function state(ids,level=1){const s=C.freshState();s.team=ids;s.clears=Array.from({length:48},(_,i)=>i);for(const id of ids){s.owned[id]=1;s.levels[id]=level;}return s;}
function fight(ids){const b=C.battle(state(ids),0);b.enemies.forEach(e=>{e.hp=e.maxHp=10000;e.atk=0;e.weak='';e.resist='';e.shield=0;});return b;}
function context(b,id,e=b.enemies[0]){return C.skillContext(b,b.allies.find(a=>a.id===id),{impacts:[],combos:[]},e);}
function run(b){for(let n=0;n<2000&&!['win','lose'].includes(b.phase);n++){const r=C.autoStep(b);assert.ok(!r.error,r.error);for(const a of b.allies){assert.ok(Number.isFinite(a.hp)&&a.hp>=0&&a.hp<=a.maxHp);assert.ok(a.shield>=0&&a.shield<=a.maxHp*.35+1);assert.ok(a.energy>=0&&a.energy<=3);}assert.ok(b.ap>=0&&b.ap<=7);}assert.ok(['win','lose'].includes(b.phase));return b;}

test('all 108 heroes expose passive/active/ultimate and have no rarity-locked core skill',()=>{assert.equal(S.activeIds.length,108);assert.equal(S.ultimateIds.length,108);for(const h of C.HEROES){assert.ok(h.kit.passive&&h.kit.active&&h.kit.ultimate,h.id);assert.ok([1,2].includes(h.cost),h.id);assert.ok(S.activeIds.includes(h.id)&&S.ultimateIds.includes(h.id));}});
test('all 108 ultimate handlers resolve a valid, finite battle with their explicit prerequisites',()=>{for(const h of C.HEROES){const b=fight([...new Set([h.id,'bran','lark','scarlet','milo'])].slice(0,5)),a=b.allies[0],e=b.enemies[0];a.energy=3;a.m.colors=['汽幕','裂爆','余灯'];a.m.witnesses=['bran','lark','scarlet'];a.m.cuts=2;a.m.record=100;a.m.debtSeen=100;b.lastReaction={name:'汽幕',B:80,pair:['焰','潮']};e.boss={phase:'charge',charge:3,cycle:0};e.statuses.push({key:'sleepLock',value:1,expires:3});b.allies.forEach(x=>x.hp=Math.floor(x.maxHp*.4));const other=b.allies[1];other.debts=[{amount:100,due:3}];context(b,h.id).shield(other,1.2);if(h.id==='morwen'){a.m.witness=other.id;other.hp=0;}const r=C.action(b,h.id,'ultimate',0);assert.ok(r.ok,h.id+': '+r.error);assert.equal(a.energy,0,h.id);assert.equal(r.event.ultimate,true);for(const x of b.allies)assert.ok(Number.isFinite(x.hp)&&Number.isFinite(x.shield),h.id);}});
test('normal actions generate personal energy, active cooldown is two rounds, and recharged ultimates can repeat',()=>{const b=fight(['scarlet']),a=b.allies[0];C.action(b,'scarlet','skill',0);assert.equal(a.energy,1);assert.equal(b.ap,3);C.enemyTurn(b);const before=JSON.stringify(b);assert.ok(C.action(b,'scarlet','skill',0).error);assert.equal(JSON.stringify(b),before);C.action(b,'scarlet','attack',0);C.enemyTurn(b);C.action(b,'scarlet','skill',0);C.enemyTurn(b);assert.equal(a.energy,3);assert.ok(C.action(b,'scarlet','ultimate',0).ok);for(let i=0;i<3;i++){C.enemyTurn(b);C.action(b,'scarlet','guard',0);}C.enemyTurn(b);assert.ok(C.action(b,'scarlet','ultimate',0).ok);assert.equal(a.m.ultUses,2);});
test('all fifteen unordered star pairs resolve once, consume the old mark, and credit the donor',()=>{for(const r of C.SkillData.reactions){const b=fight(['scarlet','lark','milo']),c=context(b,'lark'),e=b.enemies[0];b.allies[2].hp=1;e.marks=[{phase:r.pair[0],power:80,source:'scarlet',expires:2}];c.mark(e,r.pair[1]);assert.equal(b.report.combos,1,r.name);assert.equal(b.report.assists.scarlet,1);assert.ok(c.ev.combos.includes(r.name));assert.equal(e.marks.length,0);e.marks.push({phase:r.pair[0],power:80,source:'scarlet',expires:2});c.mark(e,r.pair[1]);assert.equal(b.report.combos,1);}});
test('same phase stacks at most two and marks expire after two actual enemy actions',()=>{const b=fight(['lark']),c=context(b,'lark'),e=b.enemies[0];c.mark();c.mark();c.mark();assert.equal(e.marks.length,2);C.enemyTurn(b);assert.equal(e.marks.length,2);C.enemyTurn(b);assert.equal(e.marks.length,0);assert.equal(b.report.combos,0);});
test('storm-lightning resonance grants exactly fifteen extra poise to the next normal attack',()=>{const b=fight(['lark','scarlet']),c=context(b,'lark'),e=b.enemies[0];e.poise=e.maxPoise=200;e.marks=[{phase:'霆',power:80,source:'scarlet',expires:2}];c.mark(e,'岚');b.allies[0].acted=true;const before=e.poise;C.action(b,'scarlet','attack',0);assert.equal(before-e.poise,20);assert.ok(!b.allies[1].statuses.some(s=>s.key==='nextAttackPoise'));});
test('delaying an enemy never ticks its DOT twice, and eclipse DOT refreshes across casters',()=>{const b=fight(['skor','nix']),e=b.enemies[0];context(b,'skor').dot(e,.55,2);context(b,'nix').cold(e);C.enemyTurn(b);assert.equal(e.dots[0].turns,1);C.enemyTurn(b);assert.equal(e.dots.length,0);const a=context(b,'skor');e.marks=[{phase:'焰',power:80,source:'skor',expires:9}];a.mark(e,'幽');const q=context(b,'nix');e.marks=[{phase:'焰',power:80,source:'skor',expires:9}];q.mark(e,'幽');assert.equal(e.dots.filter(d=>d.key==='eclipse').length,1);});
test('boss breaks interrupt one attack; poise can be damaged during immunity without repeated interrupts',()=>{const b=fight(['tam']),e=b.enemies[0],c=context(b,'tam');e.boss={phase:'charge',charge:1,cycle:0};e.poise=e.maxPoise=100;c.poise(e,100);assert.equal(b.report.breaks,1);const hp=b.allies[0].hp;C.enemyStep(b);assert.equal(b.allies[0].hp,hp);C.enemyTurn(b);assert.equal(b.round,2);context(b,'tam').poise(e,100);assert.equal(b.report.breaks,1);C.enemyTurn(b);assert.equal(e.poise,0);context(b,'tam').poise(e,1);assert.equal(b.report.breaks,2);});
test('shield protection is capped and returned shields never recursively return',()=>{const b=fight(['ario','velli']),a=b.allies[0],c=context(b,'ario');b.tactics.policies={velli:{partner:'ario'}};for(let i=0;i<10;i++)c.shield(a,3);assert.ok(a.shield<=a.maxHp*.35+1);assert.equal(a.wards.length,1);b.enemies[0].atk=10000;b.allies[1].hp=0;C.enemyStep(b);assert.equal(a.hp,0);assert.ok(a.wards.length<5);assert.ok(b.report.protection<=a.maxHp*.5);});
test('recycled cloth shields cannot be collected again by Aura',()=>{const b=fight(['aura','bran']),a=b.allies[0];a.m.cloth=100;a.energy=3;C.action(b,'aura','ultimate',0);assert.ok(b.allies.every(x=>x.wards.every(w=>w.recycled)));C.enemyTurn(b);C.enemyTurn(b);assert.equal(a.m.cloth,0);});
test('lamp intercept and revival are once per character and revival does not reset spent lamp',()=>{const b=fight(['milo']),a=b.allies[0];a.m.lamp=true;b.blessings=['resolve'];b.enemies.forEach(e=>e.atk=100000);C.enemyStep(b);assert.equal(a.hp,1);assert.equal(a.m.lampSpent,true);C.enemyStep(b);assert.equal(a.revived,true);assert.ok(a.hp>0);C.enemyStep(b);assert.equal(a.hp,0);assert.equal(b.phase,'lose');});
test('life fees bypass shields, stop at one HP, and award lily without rewarding hurt or energy',()=>{const b=fight(['seraphine','eirene','themis']),a=b.allies[0];context(b,'eirene').shield(a,1);const shield=a.shield;context(b,'seraphine').cost(1);assert.equal(a.hp,1);assert.equal(a.shield,shield);assert.equal(a.m.lily,1);assert.equal(a.energy,0);assert.equal(b.allies[2].m.compensation||0,0);});
test('victory pays non-cleansable HP debt first, so a last kill cannot evade a fatal debt',()=>{const b=fight(['scarlet']),a=b.allies[0];b.enemies.slice(1).forEach(e=>e.hp=0);b.enemies[0].hp=1;a.debts=[{amount:a.hp,due:99}];context(b,'scarlet').clean();assert.equal(a.debts.length,1);C.action(b,'scarlet','attack',0);assert.equal(b.phase,'lose');assert.equal(a.hp,0);});
test('action borrowing respects team generation cap and is repaid next round',()=>{const b=fight(['severin','lark']),a=b.allies[0];const r=C.action(b,'severin','skill',0);assert.ok(r.ok);assert.equal(b.extraAP,2);assert.equal(b.actionDebt,1);assert.equal(context(b,'lark').ap(2),0);C.enemyTurn(b);assert.equal(b.ap,6);assert.equal(b.actionDebt,0);a.energy=3;C.action(b,'severin','ultimate',0);assert.equal(b.extraAP,0,'unusable full AP ultimate must be rejected');});
test('Finch repairs a real ally cooldown only once in two rounds',()=>{const b=fight(['scarlet','finch']);C.action(b,'scarlet','skill',0);assert.equal(b.allies[1].m.repair,'scarlet');C.action(b,'finch','skill',0);assert.equal(b.allies[0].readyRound,2);C.enemyTurn(b);assert.ok(C.action(b,'scarlet','skill',0).ok);b.allies[1].readyRound=2;C.action(b,'finch','skill',0);assert.equal(b.allies[0].readyRound,4);});
test('Piscia links two others and only voluntarily redirects, without transferring again',()=>{const s=state(['piscia','bran','lark']);s.battleSettings.policies={piscia:{partner:'lark'}};s.battleSettings.allowSacrifice=false;const a=C.battle(s,0);assert.deepEqual(a.allies[0].m.pair,['lark','bran']);assert.ok(a.allies.every(x=>!x.statuses.some(s=>s.key==='protect')));s.battleSettings.allowSacrifice=true;const b=C.battle(s,0);assert.ok(b.allies[2].statuses.some(s=>s.key==='protect'&&s.source==='bran'));});
test('Tarn reflects one cleanseable seal and consumes the reflection',()=>{const b=fight(['tarn']),a=b.allies[0];a.energy=3;C.action(b,'tarn','ultimate',0);const e=b.enemies[0];e.profile='seal';C.enemyStep(b);assert.ok(e.statuses.some(s=>s.key==='seal'));assert.ok(!a.statuses.some(s=>s.key==='seal'||s.key==='reflectStatus'));b.enemies[1].profile='seal';C.enemyStep(b);assert.ok(a.statuses.some(s=>s.key==='seal'));});
test('Nullion collects and consumes bounded liberation light from a real friendly buff removal',()=>{const b=fight(['nullion','lark']),a=b.allies[0],c=context(b,'nullion');c.buff(a,'attackUp',.2,2);C.action(b,'nullion','skill',0);assert.equal(a.m.freedom,1);C.enemyTurn(b);a.energy=3;C.action(b,'nullion','ultimate',0);assert.equal(a.m.freedom,0);assert.ok(b.allies.some(x=>x.shield>0));});
test('Vega shares treatment only once and never recursively duplicates healing',()=>{const b=fight(['vega','milo','scarlet']);b.tactics.policies={vega:{partner:'milo'}};C.action(b,'vega','skill',0);b.allies[1].hp=b.allies[2].hp=20;const c=context(b,'milo');c.heal(b.allies[1],1);assert.equal(b.allies[2].hp,20+Math.round(c.p*.3));assert.ok(c.ev.impacts.length<=2);});
test('healing keeps its originally selected patient across heal, cleanse, and shield effects',()=>{const b=fight(['milo','scarlet']),a=b.allies[0];a.hp=a.maxHp-1;b.allies[1].hp=b.allies[1].maxHp;a.dots=[{power:10,turns:2,source:'enemy',key:'burn'}];const other=b.allies[1];C.action(b,'milo','skill',0);assert.equal(a.dots.length,0);assert.ok(a.shield>0);assert.equal(other.shield,0);});
test('policies persist through restore while all pre-existing collection, progression and currency data survive',()=>{const s=state(['milo','lark']);s.owned.milo=4;s.levels.milo=20;s.stars.milo=1;s.experience.milo=25;s.battleSettings={autoSkip:true,tactic:'sustain',allowSacrifice:false,policies:{milo:{mode:'save',partner:'lark'}}};const restored=C.restoreState(C.clone(s));for(const key of ['owned','levels','stars','experience','tickets','dust','clears'])assert.deepEqual(restored[key],s[key]);assert.equal(restored.battleSettings.policies.milo.mode,'save');assert.equal(restored.battleSettings.policies.milo.partner,'lark');assert.equal(restored.battleSettings.allowSacrifice,false);});
test('exploration carries unpaid action-point debt into the next encounter',()=>{const s=J.restoreState(state(['severin','milo','lark']));J.startExplore(s);J.chooseNode(s,'battle');const b=J.exploreBattle(s);b.phase='win';b.actionDebt=2;J.claim(s,b);const offers=J.blessingOffers(s);J.chooseBlessing(s,offers.find(x=>x.id!=='pulse').id);J.chooseNode(s,'elite');const next=J.exploreBattle(s);assert.equal(next.ap,3);assert.equal(J.restoreState(JSON.parse(JSON.stringify(s))).exploration.run.actionDebt,2);});
test('all hero solo auto battles terminate with finite bounded resources against a boss',()=>{for(const h of C.HEROES){const b=C.battle(state([h.id],3),2);run(b);}});
test('Flint is automatically used even after all shared AP is spent, but the free cast is once per battle',()=>{const b=fight(['flint']);b.ap=0;assert.equal(C.autoChoice(b).type,'skill');assert.ok(C.autoStep(b).ok);assert.equal(b.ap,0);C.enemyTurn(b);C.enemyTurn(b);b.ap=0;assert.equal(C.autoChoice(b).type,'attack');});
test('an enemy killed by damage-over-time cannot attack while its allies are still alive',()=>{const b=fight(['skor']),e=b.enemies[0];e.hp=1;e.atk=100000;context(b,'skor').dot(e,1,2);const hp=b.allies[0].hp;C.enemyStep(b);assert.equal(e.hp,0);assert.equal(b.allies[0].hp,hp);assert.notEqual(b.phase,'win');});
test('corrupt per-hero settings cannot prevent an old save from loading',()=>{const s=state(['milo']);s.battleSettings.policies={milo:null,lark:42,scarlet:{partner:'bad',mode:'bad',target:'bad'}};const r=C.restoreState(s);assert.equal(r.battleSettings.policies.milo.mode,'auto');assert.equal(r.battleSettings.policies.scarlet.partner,null);assert.equal(r.battleSettings.policies.scarlet.target,'auto');});
test('a budget party can complete a six-stop exploration using real V15 fights and blessings',()=>{const s=J.restoreState(state(['bran','lark','scarlet','flora','milo']));J.startExplore(s);s.exploration.run.seed=2;for(const node of ['battle','elite','battle','camp','event','boss']){assert.ok(J.chooseNode(s,node).ok);const r=s.exploration.run;if(r.phase==='event')J.chooseEvent(s,0);if(r.phase==='battle'){const b=run(J.exploreBattle(s));assert.equal(b.phase,'win');J.claim(s,b);if(r.phase==='blessing')J.chooseBlessing(s,J.blessingOffers(s)[0].id);}}assert.equal(s.exploration.run.phase,'complete');assert.equal(s.exploration.wins,1);});
test('four distinct parties pass 1,600 fixed-seed encounters across eight enemy profiles without invalid resources',()=>{const report=require('../../scripts/check-covenant-balance.cjs').benchmark(50);assert.equal(report.total,1600);assert.ok(report.rows.every(r=>r.finite));assert.ok(report.rows.every(r=>r.wins>=40),JSON.stringify(report.rows.filter(r=>r.wins<40)));assert.ok(report.rows.every(r=>r.resonances>0&&r.poise>0));});
