const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),C=require('../core.js'),G=C.Gear;
function team(ids=['astra','aurelia','noctis','caelum','elysium'],level=60,enhance=10){const s=C.freshState();s.clears=Array.from({length:47},(_,i)=>i);s.team=ids;s.dust=1000000;for(const id of ids){s.owned[id]=1;s.stars[id]=4;s.levels[id]=level;for(const slot of ['weapon','armor','relic']){const g=C.addGear(s,slot+'-ssr',G.seeded(s.nextGearId));for(let level=0;level<enhance;level++)C.enhanceGear(s,g.uid,level,G.seeded(g.uid*37+level));C.equip(s,id,g.uid);}}return s;}
function finish(b){assert.ok(!b.error,b.error);let steps=0;while(!['win','lose'].includes(b.phase)&&steps++<2000)C.autoStep(b);assert.ok(steps<2000);return b;}
function combos(list,k){const out=[];const pick=(start,cur)=>{if(cur.length===k){out.push([...cur]);return;}for(let i=start;i<=list.length-k+cur.length;i++){cur.push(list[i]);pick(i+1,cur);cur.pop();}};pick(0,[]);return out;}
test('final entry validates every member, every slot, rarity and level; failed entry does not mutate saves',()=>{const ready=team();assert.equal(C.finalReadiness(ready).ready,true);for(const mutate of [s=>s.team.pop(),s=>s.team[4]=s.team[0],s=>s.levels.astra=59,s=>{s.owned.selene=1;s.levels.selene=60;s.loadouts.selene=s.loadouts.astra;s.team[0]='selene';},s=>delete s.loadouts.astra.armor,s=>s.gear.find(g=>g.uid===s.loadouts.astra.relic).template='relic-sr']){const s=C.clone(ready);mutate(s);s.clears.push(47);const before=C.clone(s);assert.equal(C.finalReadiness(s).ready,false);assert.ok(C.battle(s,47).error);assert.ok(C.sweep(s,47,10).error);assert.deepEqual(s,before);}});
test('level 60, four-star UR+ teams with enhanced SSR gear beat the actual final boss in every formation',()=>{const ids=C.HEROES.filter(h=>C.rankOf(h)>=4).map(h=>h.id);let count=0;for(const five of combos(ids,5)){const s=team(five);const fight=finish(C.battle(s,47));assert.equal(fight.phase,'win',s.team.join(','));count++;}assert.equal(count,462);assert.ok(C.STAGES[47].enemies[0].atk>=1500);});
test('pre-final story remains feasible with accessible heroes and appropriately upgraded gear',()=>{for(let i=18;i<47;i++){const d=C.STAGES[i],s=team(['bran','scarlet','flora','quill','nix'],d.level,10);s.team.forEach(id=>s.stars[id]=5);assert.equal(finish(C.battle(s,i)).phase,'win',d.name);}});
test('dungeon unlocks and clear records are independent of story; starter team can earn its first gear',()=>{const s=C.freshState();assert.ok(C.battle(s,1,'dungeon').error);assert.ok(C.sweep(s,0,10,Math.random,'dungeon').error);const fight=finish(C.battle(s,0,'dungeon'));assert.equal(fight.phase,'win');const r=C.claim(s,fight,G.seeded(1));assert.equal(r.gear.length,1);assert.equal(r.tickets,0);assert.deepEqual(s.clears,[]);assert.deepEqual(s.dungeonClears,[0]);assert.ok(C.sweep(s,0,10).error);const after=C.clone(s);assert.equal(C.claim(s,fight),null);assert.deepEqual(s,after);s.clears=[5];assert.ok(!C.battle(s,1,'dungeon').error);});
test('gifts, story first clears, story repeats, sweep and dungeon defeats never give equipment',()=>{const s=C.freshState();C.claimArmory(s);C.claimDawn(s);C.claimExpansion(s);for(let i=0;i<2;i++){const b=C.battle(s,0);b.phase='win';assert.equal(C.claim(s,b).gear.length,0);}assert.equal(C.sweep(s,0,100).gear.length,0);const b=C.battle(s,0,'dungeon');b.phase='lose';assert.equal(C.claim(s,b).gear.length,0);assert.equal(s.gear.length,0);assert.deepEqual(s.dungeonClears,[]);});
test('random affixes cover 2, 3 and 4 unique entries, all types and independent values within rarity ranges',()=>{const counts=new Set(),types=new Set(),variants=new Set(),rng=G.seeded(433);for(let rank=0;rank<5;rank++)for(let i=0;i<200;i++){const affixes=G.roll(rank,rng);counts.add(affixes.length);variants.add(JSON.stringify(affixes));assert.equal(new Set(affixes.map(a=>a.id)).size,affixes.length);for(const a of affixes){types.add(a.id);const d=G.AFFIXES.find(d=>d.id===a.id),scale=d.percent?1+rank*.35:rank+1;assert.ok(a.value>=d.min*scale-.51&&a.value<=d.max*scale+.51);}}assert.deepEqual([...counts].sort(),[2,3,4]);assert.equal(types.size,6);assert.ok(variants.size>900);});
test('enhancement raises main stats and changes exactly one substat each time, up to +15',()=>{const s=C.freshState();s.dust=100000;const item=C.addGear(s,'weapon-ssr',()=>0);const rng=G.seeded(9);for(let level=0;level<15;level++){const before=C.clone(item),old=C.gearStats(item),dust=s.dust,cost=C.gearEnhancement(s,item.uid).cost;const r=C.enhanceGear(s,item.uid,level,rng);assert.equal(r.level,level+1);assert.equal(s.dust,dust-cost);assert.ok(C.gearStats(item).atk>old.atk);assert.ok(item.affixes.length<=4);const changed=item.affixes.filter(a=>!before.affixes.some(b=>a.id===b.id&&a.value===b.value));assert.equal(changed.length,1);assert.equal(changed[0].id,r.change.id);assert.deepEqual(C.restoreState(s),s);}const before=C.clone(s);assert.ok(C.enhanceGear(s,item.uid,15,rng).error);assert.deepEqual(s,before);});
test('enhancement can add a missing substat and stale or unaffordable attempts are atomic',()=>{const s=C.freshState(),item=C.addGear(s,'weapon-n',()=>0);assert.equal(item.affixes.length,2);assert.equal(C.enhanceGear(s,item.uid,0,()=>0).change.added,true);assert.equal(item.affixes.length,3);const before=C.clone(s);assert.ok(C.enhanceGear(s,item.uid,0).error);assert.ok(C.enhanceGear(s,999,0).error);assert.deepEqual(s,before);s.dust=0;const poor=C.clone(s);assert.ok(C.enhanceGear(s,item.uid,1).error);assert.deepEqual(s,poor);});
test('enhanced equipment cannot be consumed as ascension material',()=>{const s=C.freshState();s.dust=10000;const a=C.addGear(s,'armor-n'),b=C.addGear(s,'armor-n');C.enhanceGear(s,b.uid,0);assert.ok(!C.gearAscension(s,a.uid).materials.includes(b.uid));const before=C.clone(s);assert.ok(C.ascendGear(s,a.uid,b.uid,0).error);assert.deepEqual(s,before);});
test('legacy equipment receives stable affixes without losing identity, stars, ownership or progress',()=>{const old=C.freshState();delete old.dungeonClears;old.gear=[{uid:18,template:'armor-ssr',stars:3}];old.nextGearId=19;old.loadouts={milo:{armor:18}};old.clears=[0,1,2,17];old.levels.milo=20;const a=C.restoreState(old),b=C.restoreState(old);assert.deepEqual(a,b);assert.equal(a.gear[0].stars,3);assert.equal(C.gearOwner(a,18),'milo');assert.equal(a.levels.milo,20);assert.deepEqual(a.clears,old.clears);assert.deepEqual(a.dungeonClears,[]);assert.equal(a.gear[0].enhance||0,0);assert.ok(a.gear[0].affixes.length>=2);assert.deepEqual(C.restoreState(JSON.parse(JSON.stringify(a))),a);});
test('all six affix types change combat stats and mitigation reduces actual enemy damage',()=>{const s=C.freshState();for(const [slot,affixes] of [['weapon',[['atk',20],['atkPercent',.1]]],['armor',[['hp',100],['hpPercent',.2]]],['relic',[['power',.05],['mitigation',.1]]]]){const g=C.addGear(s,slot+'-n');g.affixes=affixes.map(([id,value])=>({id,value,rolls:0}));C.equip(s,'milo',g.uid);}const st=C.stats(s,'milo'),h=C.hero('milo');assert.equal(st.hp,Math.round((h.hp+70+25+100)*1.2));assert.equal(st.atk,Math.round((h.atk+10+3+20)*1.1));assert.equal(st.scale,1.09);assert.equal(st.mitigation,.1);const a=C.battle(s,0),b=C.clone(a);a.allies.forEach(x=>x.guard=false);b.allies.forEach(x=>{x.guard=false;x.mitigation=0;});C.enemyTurn(a);C.enemyTurn(b);assert.ok(a.allies[0].hp>b.allies[0].hp);});
test('dungeon batches equal repeated victories including the full random affix stream and reload',()=>{for(let stage=0;stage<6;stage++){const a=team(),b=C.clone(a);a.dungeonClears=b.dungeonClears=[stage];const ra=G.seeded(stage+42),rb=G.seeded(stage+42),result=C.sweep(a,stage,20,ra,'dungeon');for(let i=0;i<20;i++){const fight=C.battle(b,stage,'dungeon');fight.phase='win';C.claim(b,fight,rb);}assert.deepEqual(a,b);assert.equal(result.gear.length,20);assert.equal(result.tickets,0);assert.deepEqual(C.restoreState(a),a);}});
test('audio bank contains eleven non-silent original PCM wave effects',()=>{for(const name of ['blade','impact','arrow','flame','ice','thunder','heal','forge','portal','step','chime']){const b=fs.readFileSync(path.join(__dirname,'../assets/audio',name+'.wav'));assert.equal(b.toString('ascii',0,4),'RIFF');assert.equal(b.toString('ascii',8,12),'WAVE');assert.equal(b.readUInt16LE(20),1);assert.equal(b.readUInt16LE(34),16);let peak=0;for(let i=44;i<b.length-1;i+=2)peak=Math.max(peak,Math.abs(b.readInt16LE(i)));assert.ok(peak>2000,name);}});
