const test=require('node:test'),assert=require('node:assert/strict');
const Base=require('../core.js'),C=require('../journey.js').install(Base);
const runFight=b=>{for(let i=0;i<2000&&!['win','lose'].includes(b.phase);i++){const r=C.autoStep(b);assert.ok(!r.error,r.error);}assert.ok(['win','lose'].includes(b.phase));return b;};
function team(){const s=C.freshState();for(const id of ['selene','milo','scarlet','lark','astra']){s.owned[id]=1;s.levels[id]=1;}s.team=['selene','scarlet','lark','milo','astra'];return s;}
test('journey migrates old saves without changing resources and retains new settings',()=>{const old=Base.freshState(),s=C.restoreState(old);assert.equal(s.tickets,old.tickets);assert.deepEqual(s.team,old.team);assert.equal(s.battleSettings.renderer,'illustrated');s.battleSettings.tactic='burst';C.startExplore(s);C.chooseNode(s,'battle');assert.deepEqual(C.restoreState(JSON.parse(JSON.stringify(s))),s);const corrupt=JSON.parse(JSON.stringify(s));corrupt.exploration.run.blessings={};corrupt.exploration.run.path='bad';assert.doesNotThrow(()=>C.restoreState(corrupt));});
test('route locks, deterministic blessing offers, and resume preserve progress',()=>{const s=team();C.startExplore(s);const saved=JSON.stringify(s);assert.ok(C.startExplore(s).error);assert.ok(C.chooseNode(s,'boss').error);assert.equal(JSON.stringify(s),saved);C.chooseNode(s,'battle');const b=C.exploreBattle(s);runFight(b);assert.equal(b.phase,'win');C.claim(s,b);assert.equal(s.exploration.run.phase,'blessing');const offers=C.blessingOffers(s);assert.deepEqual(C.blessingOffers(C.restoreState(s)),offers);assert.ok(C.chooseBlessing(s,'bad').error);C.chooseBlessing(s,offers[0].id);assert.equal(s.exploration.run.step,1);assert.ok(C.chooseBlessing(s,offers[1].id).error);});
test('enemy shields absorb actual damage without granting false victory',()=>{
 const b=C.battle(team(),0);const e=b.enemies[0];e.hp=e.maxHp=10;e.shield=100;e.resist='潮';b.allies[0].atk=70;let r=C.action(b,b.allies[0].id,'attack',0);assert.equal(e.hp,10);assert.equal(e.shield,30);assert.equal(b.phase,'player');assert.equal(r.event.impacts.find(x=>x.type==='absorb').value,70);b.allies[1].atk=35;C.action(b,b.allies[1].id,'attack',0);assert.equal(e.hp,5);assert.equal(e.shield,0);
});

test('burst reserves a charged ultimate until boss exposure',()=>{
 const s=team();s.battleSettings.tactic='burst';const b=C.battle(s,0);b.allies=b.allies.filter(a=>a.id==='astra');b.allies[0].energy=3;b.enemies[0].boss={phase:'charge',charge:2,cycle:0};assert.notEqual(C.autoChoice(b).type,'ultimate');b.enemies[0].exposedUntil=b.round+1;assert.equal(C.autoChoice(b).type,'ultimate');
});

test('boss exposure ends with poise recovery and a period of break immunity',()=>{
 const b=C.battle(team(),0),e=b.enemies[0];e.boss={phase:'exposed',charge:3,cycle:1};e.poise=0;e.needsRecovery=true;e.exposedUntil=2;e.sturdyUntil=3;e.interrupted=true;b.enemies.forEach(e=>e.atk=0);C.enemyTurn(b);assert.equal(b.round,2);assert.equal(e.poise,e.maxPoise);assert.equal(e.boss.phase,'charge');assert.ok(e.sturdyUntil>b.round);C.enemyTurn(b);assert.equal(e.boss.charge,2);
});

test('multi-hit skills consume a primed star mark only once',()=>{
 const s=team();s.owned.capri=1;s.levels.capri=1;s.team=['capri','lark'];const b=C.battle(s,0),e=b.enemies[0];e.hp=e.maxHp=3000;e.marks=[{phase:'霆',power:80,source:'lark',expires:2}];const r=C.action(b,'capri','skill',0);assert.ok(r.ok);assert.equal(b.report.combos,1);assert.equal(e.marks.length,0);assert.ok(e.hp>0);
});

test('explicit protection redirects once and resolve revives each member at most once',()=>{
 const s=team();s.owned.bran=1;s.levels.bran=1;s.team=['bran','scarlet','lark'];s.battleSettings.policies={bran:{partner:'lark',mode:'auto'}};const b=C.battle(s,0);b.round=3;C.action(b,'bran','skill',0);b.enemies[0].atk=30;const before=b.allies[2].hp;C.enemyStep(b);assert.ok(b.report.protection>0);assert.ok(b.allies[2].hp>before-23);
 const c=C.battle(team(),0);c.allies=c.allies.slice(0,1);c.blessings=['resolve'];c.enemies.forEach(e=>e.atk=100000);C.enemyStep(c);assert.ok(c.allies[0].hp>0);assert.ok(c.allies[0].revived);C.enemyStep(c);assert.equal(c.phase,'lose');
});

test('six-stop exploration pays once, grants no equipment or story clears',()=>{const s=team(),tickets=s.tickets,dust=s.dust,gear=s.gear.length;C.startExplore(s);s.exploration.run.seed=2;for(let i=0;i<6;i++){C.chooseNode(s,['battle','elite','battle','camp','event','boss'][i]);let r=s.exploration.run;if(r.phase==='event')C.chooseEvent(s,0);else if(r.phase==='battle'){const b=C.exploreBattle(s);b.phase='win';const pay=C.claim(s,b);assert.ok(pay);assert.equal(C.claim(s,b),null);if(r.phase==='blessing')C.chooseBlessing(s,C.blessingOffers(s)[0].id);}}assert.equal(s.exploration.run.phase,'complete');assert.equal(s.exploration.wins,1);assert.ok(s.tickets>tickets);assert.ok(s.dust>dust);assert.equal(s.gear.length,gear);assert.deepEqual(s.clears,[]);const done=JSON.stringify(s);assert.ok(C.retireExplore(s).error);assert.equal(JSON.stringify(s),done);});
test('loss and retirement pay accumulated rewards once and stale battle cannot claim',()=>{const s=team();C.startExplore(s);s.exploration.run.bank={tickets:5,dust:50};C.chooseNode(s,'battle');const b=C.exploreBattle(s),before=s.tickets;const reward=C.retireExplore(s);assert.equal(reward.tickets,5);b.phase='win';assert.equal(C.claim(s,b),null);assert.equal(s.tickets,before+5);C.startExplore(s);C.chooseNode(s,'battle');const c=C.exploreBattle(s);c.phase='lose';const lost=C.claim(s,c);assert.equal(lost.gear.length,0);assert.equal(s.exploration.run.phase,'failed');assert.equal(C.claim(s,c),null);});
test('baseline starter fights finish and timeout stays terminal',()=>{const b=runFight(C.battle(C.freshState(),0));assert.equal(b.phase,'win');const c=C.battle(team(),0);c.phase='enemy';c.round=60;c.enemyQueue=[];c.enemyCursor=0;C.autoStep(c);assert.equal(c.phase,'lose');});
test('exploration events vary across a route and preserve their offers on restore',()=>{const s=team();C.startExplore(s);s.exploration.run.seed=3;const titles=[];for(const step of [0,2,4]){s.exploration.run.step=step;s.exploration.run.phase='event';titles.push(C.exploreEvent(s).title);assert.deepEqual(C.exploreEvent(C.restoreState(s)),C.exploreEvent(s));}assert.equal(new Set(titles).size,3);});
test('every exploration battle awards growth once even while currency is banked',()=>{const s=C.freshState();C.startExplore(s);C.chooseNode(s,'battle');const b=runFight(C.exploreBattle(s));const r=C.claim(s,b);assert.ok(r.experience.length);assert.ok(r.experience.some(x=>x.earned>0));const before=JSON.stringify(s);assert.equal(C.claim(s,b),null);assert.equal(JSON.stringify(s),before);});
test('recommended formation places healing specialists behind damage dealers',()=>{const s=team(),ids=C.recommendTeam(s);assert.equal(ids.length,5);assert.equal(ids[0],'selene');assert.equal(ids[4],'milo');});
test('ward, direct damage and passive damage reconcile with enemy health loss',()=>{const b=C.battle(team(),0),total=b.enemies.reduce((n,e)=>n+e.hp,0);runFight(b);const reported=Object.values(b.report.damage).reduce((n,v)=>n+v,0)+(b.report.passive||0);assert.equal(reported,total-b.enemies.reduce((n,e)=>n+e.hp,0));});

test('legacy model preference migrates to illustrated battles without losing progress',()=>{const old=team();old.battleSettings.renderer='legacy';old.tickets=123;old.clears=[0,1];const restored=C.restoreState(JSON.parse(JSON.stringify(old)));assert.equal(restored.battleSettings.renderer,'illustrated');assert.equal(restored.tickets,123);assert.deepEqual(restored.owned,old.owned);assert.deepEqual(restored.clears,old.clears);});
