const test=require('node:test'),assert=require('node:assert/strict');
const Base=require('../core.js'),C=require('../journey.js').install(Base);
const runFight=b=>{for(let i=0;i<2000&&!['win','lose'].includes(b.phase);i++){const r=C.autoStep(b);assert.ok(!r.error,r.error);}assert.ok(['win','lose'].includes(b.phase));return b;};
function team(){const s=C.freshState();for(const id of ['selene','milo','scarlet','lark','astra']){s.owned[id]=1;s.levels[id]=1;}s.team=['selene','scarlet','lark','milo','astra'];return s;}
test('journey migrates old saves without changing resources and retains new settings',()=>{const old=Base.freshState(),s=C.restoreState(old);assert.equal(s.tickets,old.tickets);assert.deepEqual(s.team,old.team);assert.equal(s.battleSettings.renderer,'illustrated');s.battleSettings.tactic='burst';C.startExplore(s);C.chooseNode(s,'battle');assert.deepEqual(C.restoreState(JSON.parse(JSON.stringify(s))),s);const corrupt=JSON.parse(JSON.stringify(s));corrupt.exploration.run.blessings={};corrupt.exploration.run.path='bad';assert.doesNotThrow(()=>C.restoreState(corrupt));});
test('route locks, deterministic blessing offers, and resume preserve progress',()=>{const s=team();C.startExplore(s);const saved=JSON.stringify(s);assert.ok(C.startExplore(s).error);assert.ok(C.chooseNode(s,'boss').error);assert.equal(JSON.stringify(s),saved);C.chooseNode(s,'battle');const b=C.exploreBattle(s);runFight(b);assert.equal(b.phase,'win');C.claim(s,b);assert.equal(s.exploration.run.phase,'blessing');const offers=C.blessingOffers(s);assert.deepEqual(C.blessingOffers(C.restoreState(s)),offers);assert.ok(C.chooseBlessing(s,'bad').error);C.chooseBlessing(s,offers[0].id);assert.equal(s.exploration.run.step,1);assert.ok(C.chooseBlessing(s,offers[1].id).error);});
test('boss ward absorbs before lethal damage without granting false victory',()=>{const b=C.battle(team(),0);b.enemies=[{id:0,name:'test',hp:10,maxHp:10,atk:1,boss:{phase:'ward',ward:100,maxWard:100,charge:2}}];b.allies[0].atk=70;let r=C.action(b,b.allies[0].id,'attack',0);assert.equal(b.enemies[0].hp,10);assert.equal(b.enemies[0].boss.ward,30);assert.equal(b.phase,'player');assert.equal(r.event.impacts.find(x=>x.type==='absorb').value,70);b.allies[1].atk=35;r=C.action(b,b.allies[1].id,'attack',0);assert.equal(b.enemies[0].hp,5);assert.equal(b.enemies[0].boss.phase,'exposed');assert.equal(b.report.breaks,1);assert.ok(r.event.combos.some(t=>t.includes('破盾')));});
test('burst saves ultimate for exposed boss and freezing delays charge',()=>{const s=team();s.battleSettings.tactic='burst';const b=C.battle(s,0);b.allies=b.allies.filter(a=>a.id==='astra');b.enemies[0].boss={phase:'ward',ward:50,maxWard:50,charge:2};assert.equal(C.autoChoice(b).type,'attack');b.enemies[0].boss.phase='exposed';assert.equal(C.autoChoice(b).type,'skill');b.phase='enemy';b.enemyCursor=0;b.enemies[0].boss.phase='charge';b.enemies[0].frozen=1;C.autoStep(b);assert.equal(b.enemies[0].boss.charge,2);});
test('boss exposure ends, charging heavy hit restores shield',()=>{const b=C.battle(team(),0),e=b.enemies[0];e.boss={phase:'exposed',until:1,charge:2,maxWard:80,ward:0};b.phase='enemy';b.enemyCursor=b.enemies.length;C.autoStep(b);assert.equal(e.boss.phase,'charge');b.phase='enemy';b.enemyCursor=0;C.autoStep(b);assert.equal(e.boss.charge,1);b.phase='enemy';b.enemyCursor=0;const r=C.autoStep(b);assert.equal(e.boss.phase,'ward');assert.equal(e.boss.ward,80);assert.match(r.event.label,/重击/);});
test('freeze into double hit triggers one shatter; damage stays bounded',()=>{const s=team();s.owned.nix=1;s.levels.nix=1;s.team=['nix','lark'];const b=C.battle(s,0);b.enemies[0].hp=b.enemies[0].maxHp=1000;b.enemies[0].frozen=1;const hitter=C.HEROES.find(h=>h.kind==='double');s.owned[hitter.id]=1;s.levels[hitter.id]=1;s.team=[hitter.id];const c=C.battle(s,0);c.enemies[0].hp=1000;c.enemies[0].frozen=1;const r=C.action(c,hitter.id,'skill',0);assert.equal(c.report.combos,1);assert.deepEqual(r.event.combos,['碎冰']);assert.equal(c.enemies[0].frozen,0);assert.ok(c.enemies[0].hp>=0);});
test('front guard shares backline damage and resolve restores a fallen unit',()=>{const b=C.battle(team(),0);b.round=3;b.phase='enemy';b.enemyCursor=0;b.enemies[0].atk=30;const before=b.allies[2].hp;C.autoStep(b);assert.ok(b.report.protection>0);assert.ok(b.allies[2].hp>before-26);const c=C.battle(team(),0);c.allies=c.allies.slice(0,1);c.blessings=['resolve'];c.phase='enemy';c.enemyCursor=0;c.enemies[0].atk=100000;C.autoStep(c);assert.ok(c.allies[0].hp>0);assert.equal(c.phase,'enemy');assert.ok(c.allies[0].revived);c.enemyCursor=0;C.autoStep(c);assert.equal(c.phase,'lose');});
test('six-stop exploration pays once, grants no equipment or story clears',()=>{const s=team(),tickets=s.tickets,dust=s.dust,gear=s.gear.length;C.startExplore(s);s.exploration.run.seed=2;for(let i=0;i<6;i++){C.chooseNode(s,['battle','elite','battle','camp','event','boss'][i]);let r=s.exploration.run;if(r.phase==='event')C.chooseEvent(s,0);else if(r.phase==='battle'){const b=runFight(C.exploreBattle(s));assert.equal(b.phase,'win');const pay=C.claim(s,b);assert.ok(pay);assert.equal(C.claim(s,b),null);if(r.phase==='blessing')C.chooseBlessing(s,C.blessingOffers(s)[0].id);}}assert.equal(s.exploration.run.phase,'complete');assert.equal(s.exploration.wins,1);assert.ok(s.tickets>tickets);assert.ok(s.dust>dust);assert.equal(s.gear.length,gear);assert.deepEqual(s.clears,[]);const done=JSON.stringify(s);assert.ok(C.retireExplore(s).error);assert.equal(JSON.stringify(s),done);});
test('loss and retirement pay accumulated rewards once and stale battle cannot claim',()=>{const s=team();C.startExplore(s);s.exploration.run.bank={tickets:5,dust:50};C.chooseNode(s,'battle');const b=C.exploreBattle(s),before=s.tickets;const reward=C.retireExplore(s);assert.equal(reward.tickets,5);b.phase='win';assert.equal(C.claim(s,b),null);assert.equal(s.tickets,before+5);C.startExplore(s);C.chooseNode(s,'battle');const c=C.exploreBattle(s);c.phase='lose';const lost=C.claim(s,c);assert.equal(lost.gear.length,0);assert.equal(s.exploration.run.phase,'failed');assert.equal(C.claim(s,c),null);});
test('baseline starter fights finish and timeout stays terminal',()=>{const b=runFight(C.battle(C.freshState(),0));assert.equal(b.phase,'win');const c=C.battle(team(),0);c.phase='enemy';c.round=60;c.enemyCursor=c.enemies.length;C.autoStep(c);assert.equal(c.phase,'lose');});
test('exploration events vary across a route and preserve their offers on restore',()=>{const s=team();C.startExplore(s);s.exploration.run.seed=3;const titles=[];for(const step of [0,2,4]){s.exploration.run.step=step;s.exploration.run.phase='event';titles.push(C.exploreEvent(s).title);assert.deepEqual(C.exploreEvent(C.restoreState(s)),C.exploreEvent(s));}assert.equal(new Set(titles).size,3);});
test('every exploration battle awards growth once even while currency is banked',()=>{const s=C.freshState();C.startExplore(s);C.chooseNode(s,'battle');const b=runFight(C.exploreBattle(s));const r=C.claim(s,b);assert.ok(r.experience.length);assert.ok(r.experience.some(x=>x.earned>0));const before=JSON.stringify(s);assert.equal(C.claim(s,b),null);assert.equal(JSON.stringify(s),before);});
test('recommended formation places healing specialists behind damage dealers',()=>{const s=team(),ids=C.recommendTeam(s);assert.equal(ids.length,5);assert.equal(ids[0],'selene');assert.equal(ids[4],'milo');});
test('ward, direct damage and passive damage reconcile with enemy health loss',()=>{const b=C.battle(team(),0),total=b.enemies.reduce((n,e)=>n+e.hp,0);runFight(b);const reported=Object.values(b.report.damage).reduce((n,v)=>n+v,0)+(b.report.passive||0);assert.equal(reported,total-b.enemies.reduce((n,e)=>n+e.hp,0));});
