const test=require('node:test');const assert=require('node:assert/strict');const C=require('../core.js');
function finish(s,stage){const b=C.battle(s,stage);assert.ok(!b.error,b.error);let n=0;while(!['win','lose'].includes(b.phase)&&n++<2000)C.autoStep(b);assert.ok(n<2000);return b;}
test('old save migration preserves duplicate copies, currencies, levels and clears',()=>{const old=C.freshState();delete old.stars;delete old.gear;delete old.loadouts;delete old.nextGearId;old.owned.milo=7;old.levels.milo=20;old.clears=[0,1,2];const s=C.restoreState(old);assert.equal(s.owned.milo,7);assert.equal(s.levels.milo,20);assert.equal(s.dust,300);assert.deepEqual(s.clears,[0,1,2]);assert.deepEqual(s.gear,[]);assert.equal(C.ascension(s,'milo').copies,6);});
test('ascension requires level and a spare card, keeps last card and never spends dust',()=>{const s=C.freshState();for(const id of ['milo','noctis','bad']){const before=C.clone(s);assert.ok(C.ascend(s,id).error);assert.deepEqual(s,before);}s.owned.milo=2;s.levels.milo=19;assert.ok(C.ascend(s,'milo').error);s.levels.milo=20;const old=C.stats(s,'milo');assert.deepEqual(C.ascend(s,'milo'),{stars:1,cap:30});assert.equal(s.owned.milo,1);assert.equal(s.levels.milo,20);assert.equal(s.dust,300);assert.equal(C.stats(s,'milo').hp,Math.round(C.hero('milo').hp*old.baseScale*1.15));s.levels.milo=30;const before=C.clone(s);assert.ok(C.ascend(s,'milo').error);assert.deepEqual(s,before);});
test('all five star gates, experience overflow and maximum level survive save reload',()=>{let s=C.freshState();s.owned.milo=6;for(let star=0;star<5;star++){C.gainExperience(s,'milo',1000000);assert.equal(s.levels.milo,20+star*10);assert.equal(C.experienceProgress(s,'milo').needed,0);assert.ok(!C.ascend(s,'milo').error);assert.ok(C.experienceProgress(s,'milo').needed>0);s=C.restoreState(C.clone(s));assert.equal(s.stars.milo,star+1);}C.gainExperience(s,'milo',1000000);assert.equal(s.levels.milo,70);assert.equal(s.owned.milo,1);assert.equal(C.experienceProgress(s,'milo').needed,0);assert.ok(C.ascend(s,'milo').error);assert.ok(C.upgrade(s,'milo').error);assert.deepEqual(C.restoreState(s),s);});
test('equipment replacement, removal and transfer never duplicate or consume items',()=>{const s=C.freshState(),a=C.addGear(s,'weapon-n'),b=C.addGear(s,'weapon-sr');assert.ok(C.equip(s,'milo',a.uid).ok);const before=C.clone(s);assert.ok(C.equip(s,'lark',a.uid).error);assert.deepEqual(s,before);assert.ok(C.equip(s,'milo',b.uid).ok);assert.equal(C.gearOwner(s,a.uid),null);assert.equal(C.gearOwner(s,b.uid),'milo');assert.equal(s.gear.length,2);assert.ok(C.unequip(s,'milo','weapon'));assert.ok(C.equip(s,'lark',b.uid).ok);assert.equal(C.gearOwner(s,b.uid),'lark');assert.deepEqual(C.restoreState(s),s);});
test('equipped main and random attributes enter an immutable battle snapshot',()=>{const s=C.freshState(),base=C.stats(s,'scarlet');for(const slot of ['weapon','armor','relic']){const item=C.addGear(s,slot+'-sr');item.affixes=[{id:'hp',value:40,rolls:0},{id:'power',value:.02,rolls:0}];C.equip(s,'scarlet',item.uid);}const st=C.stats(s,'scarlet');assert.equal(st.hp,base.hp+420+120);assert.equal(st.atk,base.atk+61);assert.ok(Math.abs(st.scale-1.20)<1e-12);const b=C.battle(s,0),a=b.allies.find(a=>a.id==='scarlet');assert.equal(a.maxHp,st.hp);assert.equal(a.atk,st.atk);C.unequip(s,'scarlet','relic');assert.ok(Math.abs(a.scale-1.20)<1e-12);const r=C.action(b,'scarlet','skill',0);assert.equal(r.event.impacts[0].value,Math.round(110*1.20));});
test('save validation rejects invalid stars, duplicate items and multiple owners',()=>{const s=C.freshState();s.stars={milo:-1,lark:6,scarlet:2};s.levels.scarlet=35;s.gear=[{uid:1,template:'weapon-ur'},{uid:1,template:'armor-ur'},{uid:-1,template:'weapon-n'},{uid:2,template:'fake'}];s.loadouts={milo:{weapon:1,armor:1},lark:{weapon:1},noctis:{weapon:1}};s.nextGearId=1;const r=C.restoreState(s);assert.equal(r.stars.milo,undefined);assert.equal(r.stars.lark,undefined);assert.equal(r.stars.scarlet,2);assert.equal(r.levels.scarlet,35);assert.equal(r.gear.length,1);assert.deepEqual(r.loadouts,{milo:{weapon:1}});assert.equal(C.addGear(r,'armor-n').uid,2);});
test('starter forging funds are one-time and story victories never grant equipment',()=>{const s=C.freshState();assert.deepEqual(C.claimArmory(s),{dust:600});assert.equal(C.claimArmory(s),null);const b=finish(s,0);assert.equal(b.phase,'win');const r=C.claim(s,b,()=>0);assert.deepEqual(r.gear,[]);const before=C.clone(s);assert.equal(C.claim(s,b),null);assert.deepEqual(s,before);const repeated=C.claim(s,finish(s,0),()=>0);assert.deepEqual(repeated.gear,[]);assert.equal(repeated.dust,50);assert.equal(repeated.tickets,3);const loss=C.battle(s,0);loss.phase='lose';assert.deepEqual(C.claim(s,loss).gear,[]);});
test('48 story stages gate sequentially across 16 regions and award resources without equipment',()=>{const s=C.freshState();s.team.forEach(id=>s.stars[id]=5);assert.equal(C.STAGES.length,48);assert.equal(C.REGIONS.length,16);assert.ok(C.battle(s,3).error);for(let i=0;i<47;i++){const st=C.STAGES[i];assert.ok(st.xp>0);assert.equal(st.boss,i%3===2);const b=C.battle(s,i);assert.ok(!b.error,b.error);b.phase='win';const r=C.claim(s,b);assert.deepEqual(r.gear,[]);assert.ok(s.clears.includes(i));}assert.ok(C.battle(s,47).error);});
test('legacy dungeon loot probability intervals match documented rarity',()=>{for(let dungeon=0;dungeon<6;dungeon++){const rates=C.DUNGEONS[dungeon].rates;assert.ok(Math.abs(rates.reduce((a,b)=>a+b,0)-1)<1e-9);let start=0;for(let rank=0;rank<5;rank++){if(rates[rank]){const s=C.freshState();s.clears=Array.from({length:48},(_,i)=>i);const b=C.battle(s,dungeon,'dungeon');b.phase='win';const r=C.claim(s,b,()=>start+rates[rank]/2);assert.equal(C.equipment(r.gear[0].template).rarity,C.RANKS[rank]);}start+=rates[rank];}}});
test('recommended-level team without SSR or UR heroes can complete the original twelve stages',()=>{for(let i=0;i<12;i++){const s=C.freshState(),st=C.STAGES[i];s.team=['bran','scarlet','flora','quill','nix'];s.clears=Array.from({length:i},(_,j)=>j);for(const id of s.team){s.owned[id]=1;s.levels[id]=st.level;s.stars[id]=Math.max(0,Math.ceil((st.level-20)/10));for(const slot of ['weapon','armor','relic'])C.equip(s,id,C.addGear(s,slot+'-'+['r','sr','ssr','ur'][st.region]).uid);}assert.equal(finish(s,i).phase,'win',st.name);}});
