(()=>{'use strict';const {system:S,heroes:H}=window.SkillDraft;const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),rank={N:'#bcc2cc',R:'#97d5ba',SR:'#b5a4ed',SSR:'#e7c684',UR:'#ecb1de',SP:'#ff8098',SSP:'#9ae6f4'},hero=id=>H.find(h=>h.id===id),phase=id=>S.phases.find(p=>p.id===id);let page=0;
function art(h){if(h.art)return `--art:url('../../assets/heroes/${h.art}.png');--rank:${rank[h.rarity]};--phase:${phase(h.phase).color}`;const original=h.sheet==='original';return `--art:url('../../assets/${original?'card-concepts':'heroes-'+h.sheet}.png');--size:${original?560.606:500}% auto;--x:${original?1.3158+h.index*24.3421:h.index*25}%;--y:22%;--rank:${rank[h.rarity]};--phase:${phase(h.phase).color}`;}
// Resolve asset URLs before passing them through CSS custom properties.
function artAtPage(h){return art(h).replaceAll('../../assets/',new URL('../assets/',location.href).href);}
function skill(text,label){const ix=text.indexOf('：'),title=ix<0?text:text.slice(0,ix),body=ix<0?'':text.slice(ix+1);return `<div class="skill"><small>${label}</small><h3>${esc(title)}</h3><p>${esc(body)}</p></div>`;}
function openHero(id){const h=hero(id);if(!h)return;$('detail-content').innerHTML=`<div class="detail-grid"><div class="detail-art" role="img" aria-label="${esc(h.name)}现有角色立绘" style="${artAtPage(h)}"></div><div class="detail-copy"><p class="eyebrow">${h.rarity} · ${h.phase} / ${esc(h.role)} · 全新技能草案</p><h2>${esc(h.name)}</h2><small>${esc(h.title)} · ${esc(h.faction)}</small><p class="quote">“${esc(h.quote)}”</p><p class="bio">${esc(h.story)}</p>${skill(h.passive,'被动 · 0星开放')}${skill(h.active,'主动技 · 名称前为行动点消耗 · 默认冷却2轮')}${skill(h.ultimate,'终式 · 3契能 · 占一次行动')}<p class="detail-limit"><strong>边界与短板：</strong>${esc(h.limit)}</p><p style="font-size:11px;color:var(--muted)">普通攻击：默认0行动点、100%攻击；多段总量不变。主动技默认附一枚本相星痕，支援技也适用；明示变相或延后时替换默认附痕。未写明确数值的低/中/高档位见核心规则词典，仍需原型测试。</p><p style="font-size:12px">可搭配的接口 · 并非限定绑定</p><div class="partners">${h.partners.map(id=>`<button data-hero="${id}">${hero(id).rarity} · ${esc(hero(id).name)} ↗</button>`).join('')}</div></div></div>`;if(!$('detail').open)$('detail').showModal();$('detail').scrollTop=0;}
function renderHeroes(){const q=$('search').value.trim().toLowerCase(),r=$('rarity').value,p=$('phase-filter').value;const list=H.filter(h=>(!r||h.rarity===r)&&(!p||h.phase===p)&&(!q||[h.id,h.name,h.title,h.faction,h.role,h.passive,h.active,h.ultimate].join(' ').toLowerCase().includes(q)));const pages=Math.max(1,Math.ceil(list.length/12));page=Math.max(0,Math.min(page,pages-1));$('result-count').textContent=`找到 ${list.length} 位契约者 · 每页12位`;$('hero-grid').innerHTML=list.slice(page*12,page*12+12).map(h=>`<button class="hero-card" data-hero="${h.id}" aria-label="查看${esc(h.name)}的新技能"><span class="portrait" style="${artAtPage(h)}"><span class="rank">${h.rarity}</span><span class="aspect">${h.phase} · ${esc(h.role)}</span></span><span class="card-copy"><small>${esc(h.title)}</small><h3>${esc(h.name)}</h3><p>${esc(h.passive)}</p><em>查看技能与配队接口 ↗</em></span></button>`).join('')||'<p>没有匹配角色。试试名字、星相或“净化”等机制词。</p>';$('page-status').textContent=`${page+1} / ${pages}`;$('previous').disabled=page===0;$('next').disabled=page>=pages-1;}
function reaction(){const a=$('phase-a').value,b=$('phase-b').value,r=S.reactions.find(r=>r.pair.includes(a)&&r.pair.includes(b)&&a!==b);$('reaction-result').innerHTML=r?`<small>${a} ＋ ${b} / ${esc(r.kind)}</small><h3>${esc(r.name)}</h3><p>${esc(r.effect)}</p><p>${esc(r.lesson)}</p><small>B = 两位参与者当前攻击的平均值</small>`:`<small>${a} ＋ ${b} / 同相储备</small><h3>留待另一种回应</h3><p>同相不发生共鸣，最多保留2枚星痕。它们可以供不同相队友依次消费，重复铺痕不自动产生增伤。</p>`;}
function view(id){if(!['system','heroes','teams','balance'].includes(id))return;document.querySelectorAll('.view').forEach(s=>s.hidden=s.id!==id);document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===id)));if(id==='heroes')renderHeroes();}
$('thesis').textContent=S.thesis;$('status').textContent=S.status;$('phases').innerHTML=S.phases.map(p=>`<article class="phase-card" style="--phase:${p.color}"><strong>${p.id} · ${p.name}</strong><p>${esc(p.meaning)}</p><small>${esc(p.role)}</small></article>`).join('');for(const id of ['phase-a','phase-b','phase-filter']){$(id).insertAdjacentHTML('beforeend',S.phases.map(p=>`<option value="${p.id}">${p.id} · ${p.name}</option>`).join(''));}$('phase-b').value='潮';reaction();$('reaction-table').innerHTML=S.reactions.map(r=>`<article><h3>${r.pair.join(' + ')} · ${esc(r.name)}</h3><p>${esc(r.effect)}</p></article>`).join('');const articles=rows=>rows.map(r=>`<article><h3>${esc(r.title)}</h3><p>${esc(r.text)}</p></article>`).join('');$('rules').innerHTML=articles(S.rules);$('glossary').innerHTML=articles(S.glossary.map(([title,text])=>({title,text})));$('factions').innerHTML=articles(S.factions.map(([name,key,text])=>({title:name+' · '+key,text})));$('balance-grid').innerHTML=articles(S.balance);$('rollout').innerHTML=articles(S.rollout.map(([title,text])=>({title,text})));$('rarity-table').innerHTML=S.rarity.map(([rarity,title,text])=>`<div class="rarity-row" style="--rank:${rank[rarity]}"><b>${rarity}</b><strong>${esc(title)}</strong><p>${esc(text)}</p></div>`).join('');$('teams-grid').innerHTML=S.teams.map(t=>`<article class="team"><h3>${esc(t.name)}</h3><div class="mini-team">${t.ids.map(id=>{const h=hero(id);return `<button data-hero="${id}" aria-label="查看${esc(h.name)}的新技能"><span class="portrait" style="${artAtPage(h)}"></span><small>${h.rarity} · ${esc(h.name)}</small></button>`;}).join('')}</div><p>${esc(t.plan)}</p><p class="value">${esc(t.works)}</p><p class="risk">取舍：${esc(t.risk)}</p></article>`).join('');
$('search').addEventListener('input',()=>{page=0;renderHeroes();});for(const id of ['rarity','phase-filter'])$(id).addEventListener('change',()=>{page=0;renderHeroes();});for(const id of ['phase-a','phase-b'])$(id).addEventListener('change',reaction);$('previous').onclick=()=>{page--;renderHeroes();};$('next').onclick=()=>{page++;renderHeroes();};document.addEventListener('click',e=>{const heroButton=e.target.closest('[data-hero]'),tab=e.target.closest('[data-view]');if(heroButton)openHero(heroButton.dataset.hero);if(tab)view(tab.dataset.view);});$('detail').querySelector('.close').onclick=()=>$('detail').close();renderHeroes();
})();
