(() => {
  'use strict';
  const C=window.EclipseCore, QA=new URLSearchParams(location.search).get('qa')==='1', SAVE_KEY='eclipse-covenant-v1'+(QA?'-qa':'');
  const main=document.getElementById('main'), dialog=document.getElementById('dialog');
  let storageOkay=true,state;
  try {state=C.restoreState(JSON.parse(localStorage.getItem(SAVE_KEY)));}catch{state=C.freshState();storageOkay=false;}
  let page=['summon','collection','team','equipment','adventure','dungeon'].includes(location.hash.slice(1))?location.hash.slice(1):'summon';
  let featuredHero='astra',teamSort='rarity';
  let filter='ALL',currentBattle=null,busy=false,reward=null,toastTimer,player=null,lastEvent=null,battleScene=null,sceneLoading=false,sceneError='',sceneVersion=0;
  let region=Math.min(C.REGIONS.length-1,Math.floor(state.clears.length/3)),gearFilter='ALL',slotFilter='ALL',equipmentHero=state.team[0]||Object.keys(state.owned)[0];
  let pendingSweep=null,lastSweep=null,summonSequence=null,lastEnhancement=null,gearPage=0,batchRunning=false,lastSummon=null;
  const GEAR_PAGE_SIZE=48;
  const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const variantClass=h=>h.variant==='prism'?'sp-prism':h.rarity==='SP'?'sp-crimson':'';
  const mysteryRate=h=>h.variant==='prism'?'0.001% · 十万分之一':'0.01% · 万分之一';
  const SHEET_META={original:{file:'card-concepts',cols:5.60606,off:1.3158,step:24.3421,y:'22.917%'},binary:{cols:2}};
  const SHEET_READY=new Set(['original','dawn','dusk']);
  const placeholder=h=>{const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 380"><defs><linearGradient id="b" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#1a1430"/><stop offset="1" stop-color="#0a0813"/></linearGradient><radialGradient id="g" cx="0.5" cy="0.3" r="0.8"><stop offset="0" stop-color="${h.color}" stop-opacity="0.5"/><stop offset="1" stop-color="${h.color}" stop-opacity="0"/></radialGradient></defs><rect width="300" height="380" fill="url(#b)"/><rect width="300" height="380" fill="url(#g)"/><text x="150" y="243" text-anchor="middle" font-family="serif" font-size="176" fill="${h.color}" fill-opacity="0.42">${h.name[0]}</text></svg>`;return `url("data:image/svg+xml,${encodeURIComponent(svg)}")`;};
  const artStyle=h=>{const rar=h.variant==='prism'?'#c7f4ff':'var(--'+h.rarity+')';if(h.art)return `--rarity:${rar};--sheet:url('assets/heroes/${h.art}.png');--art-size:cover;--art-x:50%;--art-y:25%`;const m=SHEET_META[h.sheet]||{},cols=m.cols||5,step=m.step||100/(cols-1),file=m.file||'heroes-'+h.sheet;return `--i:${h.index};--rarity:${rar};--sheet:url('assets/${file}.png');--art-size:${cols*100}% auto;--art-x:${(m.off||0)+h.index*step}%;--art-y:${m.y||'22%'}${SHEET_READY.has(h.sheet)?'':`;--ph:${placeholder(h)}`}`;};
  const sortedHeroes=()=>[...C.HEROES].sort((a,b)=>C.rankOf(b)-C.rankOf(a));
  const rarity=h=>`<span class="rarity">${h.rarity}</span>`;
  const portrait=(h,living=false)=>`<span class="portrait" role="img" aria-label="${h.title}·${h.name}角色立绘" style="${artStyle(h)}${h.art?';background-image:none':''}" ${living&&!h.video&&h.art&&['UR','SSR','SP','SSP'].includes(h.rarity)?`data-living="${h.rarity}" data-live-hero="${h.id}" data-live-art="assets/heroes/${h.art}.png"`: ''}>${h.art?`<img class="portrait-art" src="assets/heroes/${h.art}.png" alt="" loading="lazy" decoding="async" width="1024" height="1536">`:''}${living&&h.video?`<video class="portrait-video" muted loop playsinline preload="none" data-video-src="${h.video}" aria-hidden="true"></video>`:''}</span>`;
  function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));storageOkay=true;}catch{storageOkay=false;}updateWallet();}
  function toast(text){const el=document.getElementById('toast');el.textContent=text;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),3200);}
  const soundscape=new window.EclipseSound();soundscape.configure(state.audio,state.muted);
  function sound(type='click'){try{soundscape.play(type);}catch{}}
  function experienceBar(id){const p=C.experienceProgress(state,id);return `<div class="hero-experience"><div><span>${p.needed?'成长经验':'当前星级已满'}</span><span>${p.needed?p.xp+' / '+p.needed:'MAX'}</span></div><div class="xp-track" role="progressbar" aria-label="${C.hero(id).name}成长经验" aria-valuemin="0" aria-valuemax="${p.needed||1}" aria-valuenow="${p.needed?p.xp:1}"><i style="width:${p.needed?100*p.xp/p.needed:100}%"></i></div></div>`;}
  function updateWallet(){document.getElementById('tickets').textContent=state.tickets.toLocaleString();document.getElementById('dust').textContent=state.dust.toLocaleString();const btn=document.getElementById('sound');btn.textContent=state.muted?'♪':'♫';btn.setAttribute('aria-label',state.muted||soundscape.ctx?.state!=='running'?'开启声音':'关闭音效');btn.title=state.muted?'已静音':soundscape.ctx?.state==='running'?'声音已开启':'点击开启声音并试听';}
  function showDialog(html,cls=''){stopSummon();pendingSweep=null;dialog.className=cls;dialog.innerHTML=html;if(!dialog.open)dialog.showModal();syncPlayback();}
  const dialogTop=title=>`<div class="dialog-top"><h2>${title}</h2><button class="close" data-action="close" aria-label="关闭窗口">×</button></div>`;
  const tierNames={SSP:'初光 · ORIGIN',SP:'超越神话 · SOVEREIGN',UR:'神话 · MYTHIC',SSR:'传说 · LEGENDARY',SR:'史诗 · EPIC',R:'稀有 · RARE',N:'初始 · COMMON'};
  function cardOrnament(h){const rank=C.RANKS.indexOf(h.rarity);return `<span class="card-foil" aria-hidden="true"></span><svg class="card-engraving" viewBox="0 0 240 360" preserveAspectRatio="none" aria-hidden="true"><path d="M7 50V20L20 7h53M167 7h53l13 13v30M7 310v30l13 13h53M167 353h53l13-13v-30"/>${rank>=2?'<path d="M12 66V26l14-14h42m104 0h42l14 14v40M12 294v40l14 14h42m104 0h42l14-14v-40M5 90l5 8-5 8M235 90l-5 8 5 8"/>':''}${rank>=3?'<path d="M85 7l17 5 18-10 18 10 17-5M85 353l17-5 18 10 18-10 17 5M17 29l9-9 7 5-8 8Zm190-4 7-5 9 9-8 4Z"/>':''}${rank>=4?'<path d="m93 16 12 2 15-8 15 8 12-2-10 9-17-4-17 4ZM18 43l14-7-6 15-8 7Zm204 0-14-7 6 15 8 7ZM82 343l21-5 17 6 17-6 21 5M115 32l5-8 5 8-5 8Z"/>':''}</svg>${rank>=3?`<span class="card-crest" aria-hidden="true">${rank>=4?'✦':'◇'}</span>`:''}`;}
  function card(h,options={}) {
    if(C.sealed(state,h))return `<button class="hero-card rarity-${h.rarity} sealed-card ${variantClass(h)}" style="--rarity:${h.variant==='prism'?'#c7f4ff':'var(--SP)'}" data-action="detail" data-id="${h.id}" aria-label="查看${h.variant==='prism'?'炫光':'红色'}${h.rarity} 未解锁 ？？？"><div class="card-visual"><div class="sealed-orbit" aria-hidden="true"><i></i><b>✧</b></div><span class="rarity">${h.rarity}</span><span class="card-rank">未知契约</span></div><div class="card-caption"><span class="card-tier">${h.variant==='prism'?'IRIDESCENT · ORIGIN':'CRIMSON · SOVEREIGN'}</span><small>${h.variant==='prism'?'炫光封印':'绯红封印'}</small><h3>？？？</h3><div class="meta"><span>${mysteryRate(h)}</span></div><p class="sealed-hint">召唤获得后揭晓真名</p></div>${cardOrnament(h)}</button>`;
    const owned=!!state.owned[h.id],level=state.levels[h.id]||1;
    return `<button class="hero-card rarity-${h.rarity} ${variantClass(h)} ${owned?'':'locked'}" style="${artStyle(h)}" data-action="detail" data-id="${h.id}" aria-label="查看${h.rarity} ${h.name}${owned?'，已拥有':'，未收集'}">
      <div class="card-visual">${portrait(h,true)}<span class="card-aura" aria-hidden="true"></span>${rarity(h)}<span class="card-rank">${owned?'LV. '+String(level).padStart(2,'0'):'未缔结'}</span></div>
      <div class="card-caption"><span class="card-tier">${h.variant==='prism'?'初光 · ORIGIN':tierNames[h.rarity]}</span><small>${h.title}</small><h3>${h.name}</h3><div class="meta"><span>${h.role}</span><span>${owned?'已缔结':'等待邂逅'}</span></div>${owned?starsMarkup(h.id)+experienceBar(h.id):''}</div>${cardOrnament(h)}</button>`;
  }
  function render() {
    document.body.dataset.page=page;document.body.classList.toggle('in-combat',['adventure','dungeon'].includes(page)&&!!currentBattle);const context=document.getElementById('header-context');if(context)context.innerHTML=`<small>THE CELESTIAL ARCHIVE / 0${['summon','collection','team','equipment','adventure','dungeon'].indexOf(page)+1}</small><span>${{summon:'星界召唤',collection:'契约图鉴',team:'旅团编队',equipment:'星铸装备',adventure:'星蚀远征',dungeon:'星铸秘境'}[page]}</span>`;
    updateWallet();document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===page);if(b.dataset.tab===page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
    let html=page==='summon'?summonPage():page==='collection'?collectionPage():page==='team'?teamPage():page==='equipment'?equipmentPage():currentBattle&&page===(currentBattle.mode==='dungeon'?'dungeon':'adventure')?battlePage():page==='dungeon'?dungeonPage():adventurePage();
    if(!storageOkay)html='<div class="save-warning" role="alert">浏览器存储不可用，本次仍可游玩，刷新后进度可能丢失。</div>'+html;
    const focusAction=document.activeElement?.dataset?.action,focusSpeed=document.activeElement?.dataset?.speed,focusHero=document.activeElement?.dataset?.id;
    main.innerHTML=html;
    const mount=main.querySelector('.battle-viewport');if(mount&&battleScene){mount.replaceWith(battleScene.host);battleScene.update(currentBattle);battleScene.resize();}
    if(['pause-battle','speed','skip-battle','cinematic-camera'].includes(focusAction))main.querySelector(`[data-action="${focusAction}"]${focusAction==='speed'?`[data-speed="${focusSpeed}"]`:''}`)?.focus({preventScroll:true});
    if(page==='team'&&focusAction==='toggle-team')main.querySelector(`[data-action="toggle-team"][data-id="${focusHero}"]`)?.focus({preventScroll:true});
    const log=main.querySelector('.battle-log');if(log)log.scrollTop=log.scrollHeight;
  }
  function navigate(next) {
    page=next;history.replaceState(null,'','#'+next);render();syncPlayback();window.scrollTo({top:0,behavior:'instant'});
  }
  function summonPage() {
    const featured=C.hero(featuredHero);
    return `<div class="page-kicker"><span>星蚀契约 <i>✦</i> 群星回响</span><span>${C.HEROES.length} 位契约者 / ${C.HEROES.filter(h=>h.rarity==='SP').length} 位 SP / ${C.HEROES.filter(h=>h.rarity==='SSP').length} 位 SSP</span></div><section class="hero-banner" aria-label="星界常驻召唤：${featured.title}">
      <div class="hero-illustration">${portrait(featured,true)}</div><div class="hero-orbit" aria-hidden="true"></div><div class="banner-grain" aria-hidden="true"></div>
      <div class="hero-index">THE CELESTIAL COVENANT · VI</div>
      <div class="hero-copy"><div class="season">常驻星界 <span>✦</span> 群星之约</div><p class="eyebrow">BEYOND THE LAST ECLIPSE</p><h1>群星为你，<br><em>再度闪耀。</em></h1><p class="description">召唤命运的同路人。<br>让每一次相遇，化为照亮长夜的星光。</p><div class="featured-name"><span class="rarity badge" style="--rarity:var(--UR)">UR</span>${featured.title} · ${featured.name}<span>${featured.english}</span></div><button class="feature-inspect" data-action="detail" data-id="${featured.id}">阅览神话档案 <span>↗</span></button></div>
      <div class="hero-corner"><small>MYTHIC CONTRACT</small><span>${featured.quote}</span></div><div class="featured-selector" aria-label="神话角色鉴赏">${['astra','aurelia','noctis','caelum'].map((id,i)=>`<button data-action="feature-select" data-id="${id}" aria-label="鉴赏${C.hero(id).name}" aria-pressed="${id===featuredHero}"><span>0${i+1}</span>${C.hero(id).name}</button>`).join('')}</div>
    </section>
    <section class="summon-bar" aria-label="招募角色">
      <div><div class="pity-label">✧ <b>UR 及以上保底</b><small>再 ${200-state.pity.ur} 次必得</small></div><div class="pity-meter" role="progressbar" aria-label="UR保底进度" aria-valuemin="0" aria-valuemax="200" aria-valuenow="${state.pity.ur}"><span style="width:${state.pity.ur/2}%"></span></div><button class="small-link" data-action="rates">概率与保底规则</button><span class="muted"> &nbsp;·&nbsp; </span><button class="small-link" data-action="history">召唤记录</button>${lastSummon?'<button class="small-link last-summon" data-action="summon-receipt">本批战报 ↗</button>':''}</div>
      <div class="summon-actions"><button class="btn" data-action="draw" data-count="1" ${state.tickets<1?'disabled':''}>召唤一次 <small>✧ 1</small></button><button class="btn primary" data-action="draw" data-count="10" ${state.tickets<10?'disabled':''}>缔结十次 <small>✧ 10 &nbsp; →</small></button><button class="btn bulk-summon-entry" data-action="summon-custom">批量召唤 <small>自定义 · 最高 1 万次</small></button></div>
    </section>
    ${!state.gifts.includes('dawn-v5')?`<aside class="expansion-gift dawn-gift"><div><span class="eyebrow">NEW · 曙光与天穹</span><strong>五位新星，六段全新旅途。</strong><p>领取泰莎、卢恩、50 枚星契与 900 星尘，前往星铸秘境寻获装备。</p></div><button class="btn primary" data-action="claim-dawn">领取曙光礼物 →</button></aside>`:''}
    ${!state.gifts.includes('new-stars-v2')?`<aside class="expansion-gift"><div><span class="eyebrow">NEW · 群星新篇</span><strong>十位新伙伴，已加入星界。</strong><p>领取布兰、芙萝拉与 50 枚星契，组建新的自动战斗阵容。</p></div><button class="btn primary" data-action="claim-gift">领取新篇礼物 →</button></aside>`:''}
    <section class="collection-strip"><div class="section-heading"><h2>群星的回响</h2><button class="small-link" data-tab="collection">我的契约 ${Object.keys(state.owned).length} / ${C.HEROES.length} &nbsp; ↗</button></div><div class="card-row">${['caelum','eirene','ignis','rune','tessa'].map(id=>card(C.hero(id))).join('')}</div><div class="info-note">${C.HEROES.length} 位角色现已加入卡池：N ${C.HEROES.filter(h=>h.rarity==='N').length} 位 · R ${C.HEROES.filter(h=>h.rarity==='R').length} 位 · SR ${C.HEROES.filter(h=>h.rarity==='SR').length} 位 · SSR ${C.HEROES.filter(h=>h.rarity==='SSR').length} 位 · UR ${C.HEROES.filter(h=>h.rarity==='UR').length} 位，另有 ${C.HEROES.filter(h=>h.rarity==='SP').length} 位红色 SP 与 ${C.HEROES.filter(h=>h.rarity==='SSP').length} 位炫光 SSP。招募所得永久加入图鉴，重复角色保留为升星材料，并额外赠送星尘。</div></section>`;
  }
  function collectionPage() {
    const heroes=sortedHeroes().filter(h=>filter==='ALL'||filter==='OWNED'&&state.owned[h.id]||h.rarity===filter);
    return `<section class="gallery"><div class="gallery-top"><p class="eyebrow">THE CELESTIAL ARCHIVE</p><h1>每一次相遇，皆为星契。</h1><p>收藏你的契约者，聆听他们的故事。点击卡牌查看技能、升级或加入旅团。</p></div><div class="tabs-tools">${[['ALL','全部'],['OWNED','已拥有'],...C.RANKS.slice().reverse().map(r=>[r,r])].map(([value,label])=>`<button class="filter ${filter===value?'active':''}" data-action="filter" data-filter="${value}" aria-pressed="${filter===value}">${label}</button>`).join('')}<span class="progress-label">已缔结 ${Object.keys(state.owned).length} / ${C.HEROES.length} &nbsp;·&nbsp; 累计召唤 ${state.pulls} 次</span></div>${heroes.length?`<div class="card-row">${heroes.map(h=>card(h)).join('')}</div>`:'<div class="empty-state">尚未与这颗星相遇。前往星界召唤，缔结新的契约。</div>'}<p class="info-note">战斗获得经验并自动升级，星尘可直接强化一级。每级提升 6% 基础属性与技能数值，初始上限 20 级；消耗同名卡升星，最高可达 5 星、70 级。</p></section>`;
  }
  function teamPage() {
    return `<div class="gallery-top"><p class="eyebrow">YOUR CONSTELLATION</p><h1>让每一颗星，各就其位。</h1><p>最多编入五名不同角色，至少一人即可出战。存活队员中的前两位优先承受单体攻击。</p></div>
      <div class="team-slots">${Array.from({length:5},(_,i)=>{const h=C.hero(state.team[i]);return `<div class="slot ${h?'':'empty'}"><span class="slot-number">0${i+1} &nbsp; ${i<2?'前排 · 承伤':'后排 · 支援'}</span>${h?`${card(h)}<button class="slot-remove" data-action="remove" data-id="${h.id}" aria-label="移出${h.name}">移出旅团 −</button>`:'<div class="slot-empty"><b>＋</b><span>等待契约者</span></div>'}</div>`;}).join('')}</div>
      <section class="candidate-roster" aria-label="可用契约者"><div class="candidate-heading"><div><p class="eyebrow">THE CONTRACTED STARS</p><h2>可用契约者 <small>${Object.keys(state.owned).length} 位</small></h2></div><button class="small-link" data-action="auto-team">推荐编队 ↗</button></div><div class="candidate-toolbar"><p>点击头像加入或移出 · 已编入 <strong>${state.team.length} / 5</strong></p><label for="team-sort">排序 <select id="team-sort" aria-label="契约者排序"><option value="rarity" ${teamSort==='rarity'?'selected':''}>稀有度从高到低</option><option value="level" ${teamSort==='level'?'selected':''}>等级从高到低</option></select></label></div><div class="team-candidates" aria-label="${teamSort==='rarity'?'按稀有度':'按等级'}排序的契约者">${C.availableHeroes(state,teamSort).map(h=>{const position=state.team.indexOf(h.id),selected=position>=0,level=state.levels[h.id]||1;return `<button class="candidate-card rarity-${h.rarity} ${variantClass(h)} ${selected?'in-team':''}" style="${artStyle(h)}" data-action="toggle-team" data-id="${h.id}" aria-pressed="${selected}" aria-label="${selected?'移出':'加入'}旅团：${h.rarity} ${h.name}，等级 ${level}"><span class="candidate-visual">${portrait(h)}<span class="candidate-shade"></span><b class="candidate-rarity">${h.rarity}</b><span class="candidate-level">LV.${level}</span>${selected?`<span class="candidate-selected">✓ ${String(position+1).padStart(2,'0')}</span>`:''}</span><span class="candidate-caption"><strong>${h.name}</strong><small>${selected?'已入队 · 点击移出':'加入旅团 ＋'}</small></span></button>`;}).join('')}</div></section>

      <div class="team-actions"><p>队员会自动分配行动点、治疗和释放技能。搭配前卫、治疗与输出即可启程。</p><button class="btn primary" data-tab="adventure" ${state.team.length?'':'disabled'}>前往星蚀远征 <span>→</span></button></div>`;
  }
  const starsMarkup=id=>`<span class="hero-stars" aria-label="${state.stars[id]||0} 星">${'★'.repeat(state.stars[id]||0)}<span>${'☆'.repeat(5-(state.stars[id]||0))}</span></span>`;
  function gearIcon(slot){const paths={weapon:'M38 7 52 5 50 19 27 42 20 35ZM17 30 32 45M11 48 21 38M8 46 14 52',armor:'M20 8 28 13 36 13 44 8 56 22 46 30 44 54 20 54 18 30 8 22ZM26 26 32 20 38 26 32 35Z',relic:'M32 4 51 20 46 43 32 58 18 43 13 20ZM32 4 23 25 32 58 41 25ZM13 20 51 20M18 43 46 43'};return `<svg viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round" aria-hidden="true"><path d="${paths[slot]}"/></svg>`;}
  const gearBonuses=g=>[g.atk?`攻击 +${g.atk}`:'',g.hp?`生命 +${g.hp}`:'',g.power?`技能 +${Math.round(g.power*10000)/100}%`:''].filter(Boolean).join(' · ');
  function gearArt(g,eager=false){return `<img class="gear-image" src="assets/equipment/${g.id}.png" alt="${g.name}装备原画" width="1024" height="1024" loading="${eager?'eager':'lazy'}" decoding="async">`;}
  function gearCard(item,preview=false){const g=preview?C.equipment(item.template):C.gearStats(item),owner=preview?null:C.gearOwner(state,item.uid),count=preview?C.Inventory.count(state,{template:g.id}):0;return `<button class="gear-card gear-${g.rarity}" style="--rarity:var(--${g.rarity})" data-action="${preview?'gear-design':'gear-detail'}" ${preview?`data-id="${g.id}"`:`data-uid="${item.uid}"`} aria-label="查看${g.rarity}${preview?'装备设计':'装备'} ${g.name}"><span class="gear-type">${C.SLOT_NAMES[g.slot]}<b class="rarity">${g.rarity}</b></span><span class="gear-art">${gearArt(g)}</span><strong>${g.name}</strong>${preview?'':`<span class="gear-enhance-label">强化 +${g.enhance}</span>`+gearStars(g.stars)}<span class="gear-bonuses">${gearBonuses(g)}</span>${preview?'':affixList(g,true)}<span class="gear-owner">${preview?(count?'已收集 '+count+' 件':'等待发现 · 查看获取途径'):owner?C.hero(owner).name+' · 已装备':'库存中 · 可穿戴'}</span></button>`;}
  function gearGallery(){delete dialog.dataset.hero;const titles={N:'旅人的行装',R:'匠人的馈赠',SR:'元素的回响',SSR:'失落的圣器',UR:'群星的神谕',SP:'绯月的王权',SSP:'万象的初光'};showDialog(`${dialogTop('星铸图录')}<p class="gear-gallery-intro">从第一柄旅剑，到一颗初生的恒星。${C.EQUIPMENT.length} 件星铸秘宝，等待与你相遇。绯红 SP 与炫光 SSP 仅在高阶秘境获得。</p>${C.GEAR_RANKS.slice().reverse().map(r=>`<section class="gear-gallery-tier" style="--rarity:var(--${r})"><div class="gear-tier-heading"><span class="rarity">${r}</span><h3>${titles[r]}</h3><small>武器 · 护甲 · 圣物</small></div><div class="gear-grid">${C.EQUIPMENT.filter(g=>g.rarity===r).map(g=>gearCard({template:g.id},true)).join('')}</div></section>`).join('')}`,'gear-gallery-dialog');}
  function gearDesign(id){
    const g=C.equipment(id);if(!g)return;const owned=C.Inventory.page(state,{template:id,limit:1}).items[0],sources=C.DUNGEONS.map((d,i)=>({d,i})).filter(({d})=>d.rates[C.GEAR_RANKS.indexOf(g.rarity)]>0);
    delete dialog.dataset.hero;showDialog(`${dialogTop('星铸秘宝')}<div class="gear-detail gear-${g.rarity}" style="--rarity:var(--${g.rarity})"><div class="gear-detail-art">${gearArt(g,true)}</div><p class="eyebrow">${g.rarity} · ${C.SLOT_NAMES[g.slot]}</p><h2>${g.name}</h2><p>${g.lore}</p><div class="gear-attributes">${gearBonuses(g)}</div><div class="gear-obtain"><strong>仅在星铸秘境获得</strong><p>${sources.map(({d})=>d.name+' · '+g.rarity+' 掉率 '+Number((d.rates[C.GEAR_RANKS.indexOf(g.rarity)]*100).toFixed(4))+'%').join('<br>')}</p><p>同档装备等概率，掉落时独立随机生成 2～4 条副属性。</p>${C.GEAR_RANKS.indexOf(g.rarity)>=5?sources.map(({d,i})=>`<div class="gear-source-gate"><strong>${d.name} · 入场条件</strong><p>${C.dungeonReadiness(state,i).checks.map(c=>c.label).join('<br>')}</p></div>`).join(''):''}</div><div class="detail-actions">${owned?`<button class="btn" data-action="gear-detail" data-uid="${owned.uid}">查看已拥有装备</button>`:''}<button class="btn primary" data-action="go-dungeon">前往装备副本 →</button></div></div>`,'gear-art-dialog');
  }
  function affixList(g,compact=false){return `<div class="gear-affixes ${compact?'compact':''}">${(g.affixes||[]).map(a=>`<div><span>✦ ${C.Gear.format(a)}</span>${a.rolls?`<small>提升 ${a.rolls} 次</small>`:''}</div>`).join('')}${!compact?`<small>随机副属性 · ${g.affixes.length} / 4</small>`:''}</div>`;}
  function enhancementPanel(uid){const a=C.gearEnhancement(state,uid);return `<section class="enhance-panel">${lastEnhancement?.uid===uid?`<p class="enhance-feedback" role="status">✦ 强化 +${lastEnhancement.level} · ${lastEnhancement.change.added?'新增':'提升'} ${C.Gear.format({id:lastEnhancement.change.id,value:lastEnhancement.change.delta})}</p>`:''}<div class="ascension-title"><strong>星铸强化 +${a.level}</strong><span>最高 +15</span></div><p>每次提升主属性，并随机提升一条副属性；未满四条时有 35% 概率新增一条。</p><div class="gear-star-preview"><span>当前<small>${gearBonuses(a.before)}</small></span><b>→</b><span>+${Math.min(15,a.level+1)}<small>${gearBonuses(a.after)}</small></span></div><button class="btn primary" data-action="gear-enhance" data-uid="${uid}" data-level="${a.level}" ${a.ready?'':'disabled'}>${a.level===15?'强化圆满':`强化一次 · ❖ ${a.cost}`}</button></section>`;}
  function equipmentPage(){
    if(!state.owned[equipmentHero])equipmentHero=state.team[0]||Object.keys(state.owned)[0];
    const h=C.hero(equipmentHero),st=C.stats(state,h.id),loadout=C.equipped(state,h.id);
    const inventoryFilter={rarity:gearFilter,slot:slotFilter},total=C.Inventory.count(state,inventoryFilter),pages=Math.max(1,Math.ceil(total/GEAR_PAGE_SIZE));
    gearPage=Math.max(0,Math.min(gearPage,pages-1));const items=C.Inventory.page(state,{...inventoryFilter,offset:gearPage*GEAR_PAGE_SIZE,limit:GEAR_PAGE_SIZE}).items;
    const pagination=`<div class="inventory-pagination" aria-label="装备库存分页"><span>共 ${total.toLocaleString()} 件 · 每页 ${GEAR_PAGE_SIZE} 件</span><div><button class="btn" data-action="gear-page" data-page="0" ${gearPage===0?'disabled':''}>首页</button><button class="btn" data-action="gear-page" data-page="${gearPage-1}" ${gearPage===0?'disabled':''}>上一页</button><label>第 <input id="gear-page-number" type="number" min="1" max="${pages}" value="${gearPage+1}" aria-label="装备库存页码"> / ${pages.toLocaleString()} 页</label><button class="btn" data-action="gear-page" data-page="${gearPage+1}" ${gearPage===pages-1?'disabled':''}>下一页</button><button class="btn" data-action="gear-page" data-page="${pages-1}" ${gearPage===pages-1?'disabled':''}>末页</button></div></div>`;

    return `<div class="gallery-top"><p class="eyebrow">THE CELESTIAL ARMORY · VOL. 05</p><h1>以星为铸，整装启程。</h1><p>${C.EQUIPMENT.length} 种装备，涵盖 N～SSP，仅在星铸秘境掉落。每件随机获得 2～4 条副属性，可强化至 +15、觉醒至 5 星。</p></div>
    <section class="armory-masterworks" aria-label="神话装备鉴赏"><div class="masterworks-copy"><p class="eyebrow">BEYOND THE MYTHIC</p><h2>绯月加冕，初光降临。</h2><p>SP 绯红王权 · SSP 炫光初生。<br>跨越终局试炼，寻获更高阶的星铸秘宝。</p><button class="btn" data-action="gear-gallery">浏览全部 ${C.EQUIPMENT.length} 件装备 ↗</button></div><div class="masterworks-art">${['weapon-sp','armor-ssp','relic-ssp'].map(id=>{const g=C.equipment(id);return `<button class="masterwork" data-action="gear-design" data-id="${id}" aria-label="欣赏${g.rarity}装备 ${g.name}">${gearArt(g,true)}<span><small>${g.rarity} · ${C.SLOT_NAMES[g.slot]}</small><strong>${g.name}</strong></span></button>`;}).join('')}</div></section>
    ${!state.gifts.includes('armory-v3')?`<aside class="expansion-gift"><div><span class="eyebrow">旅团整备补给</span><strong>启程，前往星铸秘境。</strong><p>领取 600 星尘整备资金；挑战初火锻炉，获得你的第一件随机词条装备。</p></div><button class="btn primary" data-action="claim-armory">领取整备资金 →</button></aside>`:''}
    <section class="armory-loadout"><div class="loadout-head"><div><p class="eyebrow">当前契约者</p><label for="equipment-hero" class="sr-label">选择装备角色</label><select id="equipment-hero">${C.HEROES.filter(h=>state.owned[h.id]).map(h=>`<option value="${h.id}" ${equipmentHero===h.id?'selected':''}>${h.name} · ${h.rarity} · LV.${state.levels[h.id]}</option>`).join('')}</select></div><div class="loadout-stats"><span>生命 <b>${st.hp}</b></span><span>攻击 <b>${st.atk}</b></span><span>装备技能 <b>+${Math.round(st.bonus.power*10000)/100}%</b></span></div><button class="small-link" data-action="detail" data-id="${h.id}">角色与升星 ↗</button></div><div class="loadout-slots">${Object.entries(C.SLOT_NAMES).map(([slot,name])=>{const g=loadout.find(g=>g.slot===slot);return `<button class="loadout-slot ${g?'filled':''}" style="--rarity:var(--${g?.rarity||'N'})" data-action="${g?'gear-detail':'gear-slot'}" ${g?`data-uid="${g.uid}"`:`data-slot="${slot}"`}><span class="slot-icon">${g?gearArt(g):gearIcon(slot)}</span><span><small>${name}${g?' · '+g.rarity:''}</small><strong>${g?g.name:'尚未装备'}</strong><small>${g?gearBonuses(g):'从下方库存选择'}</small></span></button>`;}).join('')}</div><p class="loadout-note">每人可装备三件，每件只能由一名角色使用。更换时原装备返回库存；属性在下次出征时生效。</p></section>
    <div class="dungeon-entry"><div><small>THE CELESTIAL FORGE</small><strong>星铸秘境 · 装备唯一掉落地</strong><p>八档难度，随机品质与 2～4 条副属性。通关后可批量扫荡。</p></div><button class="btn primary" data-action="go-dungeon">挑战装备副本 →</button></div><div class="section-heading"><h2>星铸库存 <small>${C.Inventory.count(state).toLocaleString()} 件</small></h2><button class="small-link" data-action="gear-rates">掉落规则 ↗</button></div><div class="tabs-tools">${['ALL',...C.GEAR_RANKS.slice().reverse()].map(r=>`<button class="filter ${gearFilter===r?'active':''}" data-action="gear-filter" data-filter="${r}" aria-pressed="${gearFilter===r}">${r==='ALL'?'全部稀有度':r}</button>`).join('')}<label class="slot-select">类型 <select id="gear-slot-filter"><option value="ALL">全部类型</option>${Object.entries(C.SLOT_NAMES).map(([id,name])=>`<option value="${id}" ${slotFilter===id?'selected':''}>${name}</option>`).join('')}</select></label></div>${pagination}<div class="gear-grid">${items.length?items.map(item=>gearCard(item)).join(''):`<div class="empty-state">${C.Inventory.count(state)?'当前筛选没有装备。试试其他稀有度或装备类型。':'这里还没有装备。前往星铸秘境挑战守卫，发现随机词条装备。'}</div>`}</div>`;
  }
  function gearDetail(uid){
    const item=C.Inventory.get(state,uid);if(!item)return;const g=C.gearStats(item),owner=C.gearOwner(state,uid),id=equipmentHero&&state.owned[equipmentHero]?equipmentHero:state.team[0]||Object.keys(state.owned)[0],h=C.hero(id),old=C.equipped(state,id).find(x=>x.slot===g.slot),before=C.stats(state,id),copy=C.clone(state);
    if(owner)C.unequip(copy,owner,g.slot);C.equip(copy,id,uid);const after=C.stats(copy,id),delta=n=>n>0?'+'+n:String(n);
    delete dialog.dataset.hero;
    showDialog(`${dialogTop('星铸装备')}<div class="gear-detail gear-${g.rarity}" style="--rarity:var(--${g.rarity})"><div class="gear-detail-art">${gearArt(g,true)}</div><p class="eyebrow">${g.rarity} · ${C.SLOT_NAMES[g.slot]}</p><h2>${g.name}</h2>${gearStars(g.stars)}<span class="gear-enhance-label">强化 +${g.enhance}</span><p>${g.lore}</p><div class="gear-attributes">${gearBonuses(g)}</div>${affixList(g)}<p>${owner?`当前佩戴者：${C.hero(owner).name}`:'库存中的装备'}</p>${owner!==id?`<div class="gear-compare"><strong>装备给 ${h.name}</strong><span>替换：${old?old.name:'空装备栏'}</span><span>生命 ${before.hp} → ${after.hp}（${delta(after.hp-before.hp)}）</span><span>攻击 ${before.atk} → ${after.atk}（${delta(after.atk-before.atk)}）</span><span>装备技能加成 ${Math.round(before.bonus.power*10000)/100}% → ${Math.round(after.bonus.power*10000)/100}%</span></div>`:''}<div class="detail-actions">${owner?`<button class="btn" data-action="unequip" data-id="${owner}" data-slot="${g.slot}">从${C.hero(owner).name}卸下</button>`:''}${owner!==id?`<button class="btn primary" data-action="equip" data-id="${id}" data-uid="${uid}" ${owner?'disabled':''}>${owner?'先卸下后可重新分配':'装备给'+h.name}</button>`:''}<button class="btn" data-action="go-equipment" data-id="${id}">选择其他角色</button></div>${enhancementPanel(uid)}${gearAscensionPanel(uid)}</div>`,'gear-art-dialog');
  }
  const gearStars=stars=>`<span class="hero-stars gear-stars" aria-label="装备 ${stars||0} 星">${'★'.repeat(stars||0)}<span>${'☆'.repeat(5-(stars||0))}</span><small>${stars||0} / 5</small></span>`;
  function gearAscensionPanel(uid){const a=C.gearAscension(state,uid);return `<section class="ascension-panel gear-ascension"><div class="ascension-title"><strong>星铸觉醒</strong><span>装备 #${uid}</span></div><p>每星提升 25% 初始主属性，并随机提升或新增一条副属性；最高 5 星。</p>${a.stars===5?'<p class="star-complete">✦ 星铸圆满 · 觉醒倍率 225%（另计强化）</p>':`<div class="gear-star-preview"><span>${a.stars} 星<small>${gearBonuses(a.before)}</small></span><b>→</b><span>${a.stars+1} 星<small>${gearBonuses(a.after)}</small></span></div><p>消耗同名 0 星、未强化闲置装备 ×1（可用 ${a.materialCount.toLocaleString()} 件）<br>星尘 ${a.cost}（持有 ${state.dust}）</p><button class="btn primary" data-action="gear-ascend" data-uid="${uid}" ${a.ready?'':'disabled'}>${!a.materials.length?'缺少同名 0 星、未强化闲置装备':state.dust<a.cost?'星尘不足':`升至 ${a.stars+1} 星 →`}</button>`}</section>`;}
  function confirmGearAscension(uid){
    const a=C.gearAscension(state,uid);if(!a||!a.ready)return;
    delete dialog.dataset.hero;
    showDialog(`${dialogTop('确认装备升星')}<div class="gear-upgrade-confirm" style="--rarity:var(--${a.before.rarity})"><div class="upgrade-art">${gearArt(a.before,true)}</div><p class="eyebrow">${a.before.rarity} · 装备 #${uid}</p><h3>${a.before.name}</h3><div class="gear-star-preview"><span>${a.stars} 星<small>${gearBonuses(a.before)}</small></span><b>→</b><span>${a.stars+1} 星<small>${gearBonuses(a.after)}</small></span></div><label for="gear-material">选择消耗的同名装备（展示前 40 件闲置材料）</label><select id="gear-material">${a.materials.map(id=>`<option value="${id}">#${id} · ${C.gearStats(C.Inventory.get(state,id)).affixes.map(C.Gear.format).join(' / ')}</option>`).join('')}</select><p>消耗所选装备 ×1 与 <strong>${a.cost} 星尘</strong>。<br>主装备 #${uid} 保留，属性在下次出征生效。</p><div class="detail-actions"><button class="btn" data-action="gear-detail" data-uid="${uid}">返回</button><button class="btn primary" data-action="confirm-gear-ascend" data-uid="${uid}" data-stars="${a.stars}">确认升星 · ❖ ${a.cost}</button></div></div>`,'gear-art-dialog');
  }
  function gearRules(){delete dialog.dataset.hero;showDialog(`${dialogTop('星铸秘境 · 装备规则')}<div class="help-copy"><p>装备仅在星铸秘境胜利或扫荡中掉落，每轮一件；主线远征不掉装备。装备品质、模板、2～4 条不重复副属性及数值均独立随机生成。</p><div class="gear-rates-scroll"><table class="rate-table"><thead><tr><th>秘境</th>${C.GEAR_RANKS.map(r=>`<th>${r}</th>`).join('')}</tr></thead><tbody>${C.DUNGEONS.map(d=>`<tr><td>${d.name}</td>${d.rates.map(n=>`<td>${Number((n*100).toFixed(4))}%</td>`).join('')}</tr>`).join('')}</tbody></table></div><h3>绯红与初光 · 高阶秘境</h3><p>前六档秘境不掉落 SP / SSP。绯月王庭有 1% 概率获得 SP；零界星殿有 0.1% 概率获得 SSP，其余为 SP。同档三件等概率，不设装备保底。每轮独立抽取，首通也不保证稀有掉落。</p><p>高阶秘境的主线进度、前置副本、全队等级和装备门槛会逐项显示。首通后可扫荡，扫荡同样检查阵容和装备条件。</p><h3>强化与觉醒</h3><p>强化最高 +15，每级增加 6% 初始主属性，费用随等级和稀有度提高。每次强化额外随机提升一条副属性；少于四条时有 35% 概率新增。副属性效果真实计入出战属性，伤害减免合计上限 35%。</p><p>装备觉醒最高 5 星，每星增加 25% 初始主属性，同时提升或新增一条副属性。强化与觉醒的主属性倍率相乘。材料必须同名、0 星、未强化、未穿戴；养成过的装备不会被误当材料。</p><p>已有装备与穿戴关系保留；旧装备自动补齐固定保存的随机副属性，刷新不会重抽。</p></div>`);}
  function ascensionPanel(id){const a=C.ascension(state,id);return `<section class="ascension-panel"><div class="ascension-title"><strong>星阶觉醒</strong>${starsMarkup(id)}</div><div class="star-road">${Array.from({length:6},(_,i)=>`<span class="${i<=a.stars?'reached':''}"><b>${i} 星</b><small>上限 ${20+i*10}</small></span>`).join('')}</div><p>${a.stars===5?'星阶已圆满。最高等级 70 级。':`下一星条件：LV.${a.cap}（当前 ${state.levels[id]}） · 同名卡 1 张（持有 ${a.copies} 张）`}</p><p>每星增加 15% 基础生命、攻击及技能效果；保留当前等级，解锁额外 10 级。</p><button class="btn primary" data-action="ascend" data-id="${id}" ${a.ready?'':'disabled'}>${a.stars===5?'已达最高 5 星':`升至 ${a.stars+1} 星 · 消耗同名卡 ×1`}</button></section>`;}
  const skipControl=()=>`<label class="auto-skip"><input type="checkbox" data-auto-skip ${state.battleSettings.autoSkip?'checked':''}>自动跳过战斗动画 <small>保留剧情与完整结算</small></label>`;
  function storyChoice(stage){const c=C.Story.choices.find(x=>x.stage===stage);if(!c||!state.clears.includes(stage))return '';const selected=state.storyChoices[stage];return `<section class="story-choice"><h3>${c.title}</h3>${selected!==undefined?`<p>已记录：${c.options[selected].label}</p><p>${c.options[selected].reply}</p>`:`<p>你的决定影响阵营态度与终章回响，不改变战斗数值。决定后记入本地存档。</p><div class="choice-options">${c.options.map((o,i)=>`<button class="btn" data-action="story-choice" data-stage="${stage}" data-choice="${i}"><strong>${o.label}</strong><small>${o.cost}</small></button>`).join('')}</div>`}</section>`;}
  function chapterBrief(){const scene=C.Story.scenes[Math.min(region*3+2,Math.max(region*3,state.clears.length))];return `<section class="story-brief"><p class="eyebrow">CHAPTER ${region+1} · ${C.Story.chapters[region][0]}</p><h3>${scene.question}</h3><blockquote>“${scene.quote}”<cite>— ${scene.speaker}</cite></blockquote><div class="journey-tools"><button class="btn" data-action="story-journal">世界与旅途档案 ↗</button>${skipControl()}</div></section>`;}
  function storyJournal(){delete dialog.dataset.hero;const reputation=C.Story.reputation(state);showDialog(`${dialogTop('长夜纪事 · 世界与旅途')}<div class="story-journal"><p class="eyebrow">THE PRICE OF DAWN</p><h2>照亮一座城的光，来自谁的长夜？</h2><p>千年日蚀下，星寰依靠旧契分配有限星光。没有登记在册的人先失去名字，再失去被世界记住的资格。八方联盟共同维持供光，也争夺它的解释权。旅团在救援途中寻找一份能让承担代价的人亲自签署的新契约。</p><details><summary>共同的敌人：无名议会</summary><p>议长曾参与制定旧契，如今主张彻底断契；他要终止失名，也愿意让中心城邦承担骤然断光的伤亡。议会内部的归名派寻求身份与追责，断契派要求摧毁机制，复仇派则不接受和谈。</p></details><h3>联盟的承诺与利益</h3><div class="faction-grid">${C.Story.factions.map(f=>`<article><h3>${f.name} <small>态度 ${reputation[f.id]>0?'+':''}${reputation[f.id]}</small></h3><p>${f.promise}</p><p><b>所守利益：</b>${f.interest}</p>${state.clears.includes(35)?`<p><b>幕后：</b>${f.secret}</p>`:'<small>更多内情随旅途揭晓。</small>'}</article>`).join('')}</div><h3>旅途记录 · ${state.clears.length} / 48</h3>${C.Story.scenes.filter(x=>x.stage===0||state.clears.includes(x.stage-1)||state.clears.includes(x.stage)).map(x=>`<details><summary>${x.stage+1}. ${x.title} · ${state.clears.includes(x.stage)?'已完成':'进行中'}</summary><p>${x.before}</p><blockquote>${x.speaker}：“${x.quote}”</blockquote>${state.clears.includes(x.stage)?`<p>${x.after}</p>${storyChoice(x.stage)}`:''}</details>`).join('')}${state.clears.includes(47)?`<section class="story-brief"><h3>终章 · 群星回响</h3><p>${C.Story.epilogue(state)}</p></section>`:''}</div>`,'story-dialog');}
  function resultActions(){const next=C.nextExpedition(state,currentBattle);return `<div class="journey-tools result-actions">${next?`<button class="btn primary" data-action="battle" data-stage="${next.stage}" data-mode="${next.mode}" ${next.ready?'':'disabled'}>下一征程 · ${next.name} →</button>`:currentBattle.phase==='win'?'<span>本条征程已全部完成</span>':''}<button class="btn" data-action="battle" data-stage="${currentBattle.stage}" data-mode="${currentBattle.mode}">再次挑战</button><button class="btn" data-action="leave-battle">返回章节</button>${currentBattle.phase==='win'?`<button class="btn" data-action="sweep-open" data-stage="${currentBattle.stage}" data-mode="${currentBattle.mode}">批量扫荡</button>`:''}${skipControl()}</div>${next&&!next.ready?`<p class="info-note">${next.error}</p>`:''}`;}
  function storyResult(){if(currentBattle.mode==='dungeon'||currentBattle.phase!=='win')return '';const scene=C.Story.scenes[currentBattle.stage];return `<section class="story-brief"><p class="eyebrow">AFTER THE BATTLE · ${scene.title}</p><blockquote>“${scene.quote}”<cite>— ${scene.speaker}</cite></blockquote><p>${scene.after}</p>${storyChoice(currentBattle.stage)}${currentBattle.stage===47?`<p>${C.Story.epilogue(state)}</p>`:''}<button class="small-link" data-action="story-journal">查看旅途与阵营档案 ↗</button></section>`;}
  function adventurePage(){
    const area=C.REGIONS[region];
    return `<div class="gallery-top"><p class="eyebrow">THE LONG ECLIPSE · 16 REGIONS / 48 STAGES</p><h1>向日蚀深处，启程。</h1><p>16 个区域，48 道关卡。主线获得星契、星尘与经验；装备请前往星铸秘境。通关后可批量扫荡。</p></div><div class="expedition-progress"><span>主线进度 <b>${state.clears.length} / ${C.STAGES.length}</b></span><div><i style="width:${state.clears.length/C.STAGES.length*100}%"></i></div><button class="small-link" data-action="go-dungeon">装备副本 ↗</button></div>${chapterBrief()}<div class="region-tabs">${C.REGIONS.map((r,i)=>`<button style="--region:${r.color}" class="region-tab ${region===i?'active':''}" data-action="region" data-region="${i}" aria-pressed="${region===i}"><span>${r.glyph}</span><div><small>${String(i+1).padStart(2,'0')} · ${C.STAGES.filter((s,n)=>s.region===i&&state.clears.includes(n)).length}/3</small><strong>${r.name}</strong></div></button>`).join('')}</div><div class="region-heading" style="--region:${area.color}"><span>${area.glyph}</span><div><p class="eyebrow">${area.english}</p><h2>${area.name}</h2><p>${area.desc}</p></div></div><div class="stages">${C.STAGES.map((d,i)=>d.region===region?stageCard(d,i,'story'): '').join('')}</div><p class="info-note">失败获得 40% 经验，撤退无奖励。每次出征恢复全队生命。</p>`;
  }
  function finalRequirements(){const p=C.finalReadiness(state);return `<div class="final-requirements"><strong>终局挑战 · 入场检验 ${p.ready?'✓':'未达成'}</strong><p>五人满编 · 全员 UR 以上 · 每人 LV.60 以上 · 每人三个部位均为 SSR 以上装备</p>${p.rows.map(r=>`<div>${C.hero(r.id).name}<span>${r.rarity?'✓':'×'} 稀有度　${r.level?'✓':'×'} 等级　${r.equipment?'✓':'×'} 装备</span></div>`).join('')}</div>`;}
  function dungeonPage(){return `<div class="gallery-top"><p class="eyebrow">THE CELESTIAL FORGE</p><h1>星铸秘境。</h1><p>穿越古老锻炉，寻获属于你的秘宝。每次胜利掉落一件装备，随机生成 2～4 条副属性。</p></div><div class="dungeon-banner"><div><span>唯一装备掉落地</span><h2>每一件，都有不同的命运。</h2><p>随机品质 · 随机词条 · 自由强化 · 通关后批量扫荡</p></div><button class="btn" data-action="gear-rates">掉落与强化规则 ↗</button></div>${skipControl()}<div class="stages dungeon-stages">${C.DUNGEONS.map((d,i)=>stageCard(d,i,'dungeon')).join('')}</div>`;}
  function dungeonRequirements(i){const p=C.dungeonReadiness(state,i);return `<div class="forge-requirements"><strong>高阶入场检验 ${p.ready?'✓ 已达成':'· 未达成'}</strong>${p.checks.map(c=>`<div class="${c.met?'met':'unmet'}"><span aria-hidden="true">${c.met?'✓':'○'}</span><span>${c.label}</span></div>`).join('')}<small>首次通关后开放扫荡；每次扫荡仍需满足全部条件。</small></div>`;}
  function stageCard(d,i,mode){
    const dungeon=mode==='dungeon',access=dungeon?C.dungeonReadiness(state,i):null,cleared=(dungeon?state.dungeonClears:state.clears).includes(i),unlocked=dungeon?access.unlocked:(i===0||state.clears.includes(i-1)),ready=dungeon?access.ready:!d.final||C.finalReadiness(state).ready,area=C.REGIONS[d.region];
    return `<article class="stage region-${d.theme} ${d.boss?'boss-stage':''} ${d.gate?'sovereign-stage':''}"><div class="stage-art"><span class="stage-num">${dungeon?'F'+(i+1):String(i+1).padStart(2,'0')}</span><span class="stage-emblem">${d.gate?i===6?'♛':'✧':dungeon?'⚒':d.boss?'♛':area.glyph}</span><span class="stage-difficulty">${d.gate?'高阶装备试炼':dungeon?'装备试炼':d.final?'终局试炼':d.boss?'区域首领':'主线关卡'} · ${d.final||d.gate?'最低':'建议'} LV.${d.level}</span></div><div class="stage-info"><p class="eyebrow">${d.subtitle}${cleared?' · CLEARED':''}</p><h2>${d.name}</h2><p>${dungeon?d.loot+' · 每件随机 2～4 条副属性':d.desc}</p><div class="stage-reward">${dungeon?`❖ ${d.repeatDust}`:cleared?`重访 ✧ 3 · ❖ ${d.repeatDust}`:`首通 ✧ ${d.reward} · ❖ ${d.dust}`} · ${d.xp} EXP / 人</div>${dungeon?'<div class="dungeon-drop">✦ 随机装备 ×1 · 独立词条</div>':''}${d.gate?dungeonRequirements(i):d.final?finalRequirements():''}<button class="btn primary" data-action="battle" data-stage="${i}" data-mode="${mode}" ${!unlocked||!state.team.length||!ready?'disabled':''}>${!unlocked?d.gate?'完成前置关卡后解锁':dungeon?`主线第 ${d.unlock+1} 关解锁`:'通关上一关解锁':!ready?d.gate?'高阶阵容未达标':'终局阵容未达标':cleared?'再次挑战 →':'自动出征 →'}</button><button class="btn sweep-entry" data-action="sweep-open" data-stage="${i}" data-mode="${mode}" ${!cleared||!state.team.length||!ready?'disabled':''}>${cleared?'批量扫荡 »':'首次通关解锁扫荡'}</button></div></article>`;
  }
  function openSweep(stage,count=10,mode='story'){
    if(player&&!player.finished){toast('请先完成或结束当前战斗。');return;}
    const preview=C.sweepPreview(state,stage,count,mode);if(preview.error){toast(preview.error);return;}
    const def=C.battleStage({stage,mode});delete dialog.dataset.hero;
    showDialog(`${dialogTop('批量扫荡')}<div class="sweep-banner region-${def.theme}"><span class="sweep-sigil" aria-hidden="true">${C.REGIONS[def.region].glyph}</span><div><p class="eyebrow">CLEARED · ${mode==='dungeon'?'秘境 F'+(stage+1):'主线第 '+(stage+1)+' 关'}</p><h3>${def.name}</h3><p>已通关 · 无需消耗资源 · 立即结算</p></div></div>
      <div class="sweep-selector"><label for="sweep-count">扫荡轮数 <small>自定义 1～${C.MAX_SWEEP_ROUNDS.toLocaleString()} 轮</small></label><input id="sweep-count" type="number" min="1" max="${C.MAX_SWEEP_ROUNDS}" step="1" value="${count}" inputmode="numeric" aria-describedby="sweep-error"><div class="sweep-presets" aria-label="快捷选择扫荡轮数">${[10,100,1000,10000,100000,1000000].map(n=>`<button data-action="sweep-preset" data-count="${n}" aria-pressed="${n===count}">${n>=10000?n/10000+' 万':n.toLocaleString()} 轮</button>`).join('')}</div></div>
      <p id="sweep-error" class="sweep-error" role="alert"></p><div id="sweep-preview" aria-live="polite" aria-atomic="true"></div>
      <p class="sweep-note">${mode==='dungeon'?'每轮独立抽取装备与词条。':'主线仅结算星契、星尘与经验，不掉装备。'}达到当前星级上限后不再积累经验，升星后可继续成长。</p><div class="sweep-actions"><button class="btn" data-action="close">取消</button><button class="btn primary" data-action="sweep-confirm">开始扫荡</button></div>`,'sweep-dialog');
    pendingSweep={stage,mode};updateSweepPreview();
  }
  function updateSweepPreview(){
    if(!pendingSweep)return;
    const input=dialog.querySelector('#sweep-count'),count=Number(input.value),p=C.sweepPreview(state,pendingSweep.stage,count,pendingSweep.mode);
    const error=dialog.querySelector('#sweep-error'),button=dialog.querySelector('[data-action="sweep-confirm"]');
    error.textContent=p.error||'';input.setAttribute('aria-invalid',String(!!p.error));button.disabled=!!p.error;
    button.textContent=p.error?'请输入有效轮数':`开始扫荡 ${count.toLocaleString()} 轮 →`;
    dialog.querySelectorAll('[data-action="sweep-preset"]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.count)===count)));
    dialog.querySelector('#sweep-preview').innerHTML=p.error?'':`<div class="sweep-section-title"><h3>预计收获</h3><span>${count.toLocaleString()} 轮重访奖励</span></div>${sweepResources(p)}<div class="sweep-section-title"><h3>历练旅团</h3><span>经验分别发给每位队员</span></div><div class="sweep-team">${p.team.map(id=>{const h=C.hero(id),xp=C.experienceProgress(state,id);return `<div class="sweep-member" style="${artStyle(h)}">${portrait(h)}<span><strong>${h.name}</strong><small>LV.${xp.level} · ${state.stars[id]||0} 星</small></span><b>${xp.needed?'最多 +'+p.xpPerHero.toLocaleString()+' EXP':'当前星级已满'}</b></div>`;}).join('')}</div>`;
  }
  function sweepResources(p){return `<div class="sweep-resources"><div><span>✧ 星契</span><strong>+${p.tickets.toLocaleString()}</strong></div><div><span>❖ 星尘</span><strong>+${p.dust.toLocaleString()}</strong></div><div><span>◇ 随机装备</span><strong>${(p.gearCount??p.gear.length).toLocaleString()}<small> 件</small></strong></div></div>`;}
  // Work on a detached state and publish it only after the browser accepts the
  // entire save. A failed worker/save cannot partially charge or award a batch.
  async function executeBatch(type,args){
    if(batchRunning)return null;batchRunning=true;
    showDialog(`<div class="bulk-working" role="status" aria-live="polite"><span class="bulk-orbit">✧</span><p class="eyebrow">THE STARS ARE ALIGNING</p><h2>正在${type==='sweep'?'扫荡':'召唤'} ${args.count.toLocaleString()} 次</h2><p id="bulk-progress">正在结算奖励，请稍候…</p><p class="sweep-note">完成后自动保存。</p></div>`,'bulk-working-dialog');
    const next=C.clone(state);
    try{
      let packet;
      if(args.count>100){
        packet=await new Promise((resolve,reject)=>{
          const worker=new Worker('bulk-worker.js');
          const timer=setTimeout(()=>{worker.terminate();reject(new Error('本批结算超时，未扣除或发放任何资源，请重试。'));},60000);
          const finish=(callback,value)=>{clearTimeout(timer);worker.terminate();callback(value);};
          worker.onmessage=({data})=>{if(data.progress!==undefined){const el=document.getElementById('bulk-progress');if(el)el.textContent=`正在结算装备掉落 · ${Math.round(data.progress*100)}%`;return;}if(data.error)finish(reject,new Error(data.error));else finish(resolve,data);};
          worker.onerror=()=>finish(reject,new Error('结算服务未能启动，本批资源没有变化。请刷新后重试。'));
          worker.postMessage({state:next,type,args});
        });
      }else packet={state:next,result:type==='sweep'?C.sweep(next,args.stage,args.count,Math.random,args.mode):C.draw(next,args.count)};
      if(packet.result.error)throw new Error(packet.result.error);
      packet.state.audio=state.audio;packet.state.muted=state.muted;
      try{localStorage.setItem(SAVE_KEY,JSON.stringify(packet.state));}catch{throw new Error('本批未完成：浏览器无法保存进度。资源保持原样，请释放存储空间后重试。');}
      state=packet.state;storageOkay=true;updateWallet();return packet.result;
    }catch(error){dialog.close();toast(error.message);return null;}
    finally{batchRunning=false;}
  }
  async function runSweep(){
    if(!pendingSweep||batchRunning)return;
    const {stage,mode}=pendingSweep,count=Number(dialog.querySelector('#sweep-count').value);
    const preview=C.sweepPreview(state,stage,count,mode);if(preview.error){updateSweepPreview();return;}
    pendingSweep=null;const result=await executeBatch('sweep',{stage,mode,count});if(!result)return;
    lastSweep=result;if(mode==='story')region=C.STAGES[stage].region;stopBattle();render();showSweepResults(result);soundscape.settlement(true,result);
  }
  function showSweepResults(r){
    const groups=new Map((r.gearGroups||[]).map(g=>[g.item.template,g]));for(const item of r.gearGroups?[]:r.gear){const group=groups.get(item.template);if(group)group.count++;else groups.set(item.template,{item,count:1});}
    const sorted=[...groups.values()].sort((a,b)=>C.GEAR_RANKS.indexOf(C.equipment(b.item.template).rarity)-C.GEAR_RANKS.indexOf(C.equipment(a.item.template).rarity));
    delete dialog.dataset.hero;
    showDialog(`${dialogTop('扫荡战报')}<div class="sweep-complete"><span aria-hidden="true">✧</span><p class="eyebrow">EXPEDITION COMPLETE</p><h3>${r.count.toLocaleString()} 轮扫荡完成</h3><p>${C.battleStage(r).name} · 全部奖励已存入旅团</p></div>${!storageOkay?'<p class="save-warning" role="alert">浏览器存储不可用，刷新后奖励可能丢失。</p>':''}${sweepResources(r)}
      <section class="experience-results"><div class="section-heading"><h3>旅团成长</h3><small>当前星级满级后停止积累经验</small></div>${r.experience.map(x=>{const h=C.hero(x.id);return `<div class="experience-row ${x.level>x.fromLevel?'level-up':''}"><span class="rarity" style="--rarity:${h.variant==='prism'?'#c7f4ff':'var(--'+h.rarity+')'}">${h.rarity}</span><div><strong>${h.name}</strong><span class="xp-level">LV.${x.fromLevel}${x.level>x.fromLevel?' → '+x.level+' · 升级！':''}</span><small class="sweep-earned">${x.needed?`结算经验 ${x.xp} / ${x.needed}`:'已达当前星级上限'}</small></div><b>${x.earned?'+'+x.earned.toLocaleString()+' EXP':'已满级'}</b></div>`;}).join('')}</section>
      ${sorted.length?`<section class="sweep-loot"><div class="sweep-section-title"><h3>星铸战利品</h3><span>共 ${(r.gearCount??r.gear.length).toLocaleString()} 件 · ${groups.size} 种</span></div><div class="sweep-rarities">${C.GEAR_RANKS.slice().reverse().map(rank=>{const count=sorted.filter(g=>C.equipment(g.item.template).rarity===rank).reduce((n,g)=>n+g.count,0);return count?`<span style="--rarity:var(--${rank})"><b class="rarity">${rank}</b> × ${count.toLocaleString()}</span>`:'';}).join('')}</div><div class="gear-grid">${sorted.map(g=>`<div class="sweep-loot-group">${gearCard(g.item)}<span class="sweep-quantity">本批获得 × ${g.count.toLocaleString()}</span></div>`).join('')}</div><p class="sweep-note">同款装备合并展示，每一件都已独立入库，词条独立随机；此处展示其中一件，可在装备库逐件查看。</p></section>`:''}
      <div class="sweep-actions"><button class="btn" data-action="close">返回章节</button><button class="btn" data-action="go-equipment">装备整备 ↗</button><button class="btn primary" data-action="sweep-open" data-stage="${r.stage}" data-mode="${r.mode}" data-count="${r.count}">再扫荡 ${r.count.toLocaleString()} 轮 »</button></div>`,'sweep-dialog sweep-results-dialog');
    dialog.scrollTop=0;
  }
  function combatHud(b){return `<div class="combat-hud" aria-label="队伍战斗状态">${b.allies.map(a=>{const h=C.hero(a.id);return `<article class="combat-hud-member ${a.hp<=0?'fallen':''}" style="${artStyle(h)}" aria-label="${h.name}，生命${a.hp}/${a.maxHp}"><div class="hud-avatar">${portrait(h)}<small>${h.rarity}</small></div><div><strong>${h.name}</strong><span>LV.${a.level||state.levels[a.id]} ${a.shield?'· 盾 '+a.shield:''}</span><div class="hud-health"><i style="width:${100*a.hp/a.maxHp}%"></i></div><small>${a.hp.toLocaleString()} / ${a.maxHp.toLocaleString()}</small></div></article>`;}).join('')}</div>`;}
  function battlePage() {
    const b=currentBattle,def=C.battleStage(b),finished=['win','lose'].includes(b.phase)&&!!player?.finished;
    if(finished)return `<div class="battle-header"><div><p class="eyebrow">${def.subtitle}</p><h1>${def.name}</h1></div></div>${resultPanel()}<details class="combat-record"><summary>查看本场战斗记录</summary>${b.log.map(t=>`<p>${esc(t)}</p>`).join('')}</details>`;
    return `<div class="battle-header"><div><p class="eyebrow">${def.subtitle} · AUTO BATTLE</p><h1>${def.name}</h1></div><div class="battle-round"><span class="auto-indicator">✦ 自动战斗</span><span class="round-label">回合 ${String(b.round).padStart(2,'0')}</span><span class="ap-display">行动点 ${b.ap}</span><button class="small-link" data-action="retreat">撤退</button></div></div>
      <section class="battle-theatre theatre-3d ${b.field?'field-active':''} ${finished?'is-finished':''}" aria-label="三维自动战斗场景">
        <div class="battle-viewport"><div class="world-loading" role="status">正在准备 3D 战场…</div></div>
        <div class="battle-caption" role="status">${finished?(b.phase==='win'?'星光归来 · 远征胜利':'休整之后，再度启程'):lastEvent?esc(lastEvent.label):'旅团就绪 · 即将自动交战'}</div>
        <div class="world-toolbar"><span>✦ ${b.mode==='dungeon'?'星铸秘境':C.REGIONS[def.region].name} · ${def.boss?'首领讨伐':'自动远征'}</span><div class="camera-tools"><button data-action="cinematic-camera" aria-pressed="${battleScene?.cinematic!==false}">${battleScene?.cinematic===false?'动态镜头：关':'动态镜头：开'}</button><button data-action="reset-camera" aria-label="重置战场视角">重置视角 ↺</button></div></div>
        ${b.field?`<div class="field-announcement">✧ 星蚀领域 · ${b.field} 回合</div>`:''}
        ${sceneLoading?'<div class="scene-notice" role="status">正在加载角色与骨骼动画…</div>':sceneError?`<div class="scene-notice scene-error" role="alert"><strong>3D 战场暂未载入</strong><span>${esc(sceneError)}</span><button class="btn" data-action="retry-scene">重新加载战场</button></div>`:''}
      </section>
      ${combatHud(b)}
      ${finished?resultPanel():`<div class="playback-bar"><div class="playback-copy"><b id="playback-state">${player?.paused?'战斗已暂停':'旅团正在自动作战'}</b><span>技能、治疗与目标选择均由队员自动完成</span></div><div class="playback-actions">${skipControl()}<button class="btn" data-action="pause-battle">${player?.paused?'继续战斗':'暂停战斗'}</button><div class="speed-switch" aria-label="战斗播放速度">${[1,2,4].map(n=>`<button data-action="speed" data-speed="${n}" aria-pressed="${(player?.speed||1)===n}">${n}×</button>`).join('')}</div><button class="btn soft" data-action="skip-battle">跳过动画 →</button></div></div>`}
      <details class="combat-record"><summary>战斗记录 · 查看技能与伤害</summary><div class="battle-log" aria-label="战斗记录">${b.log.slice(-25).map(t=>`<p>${esc(t)}</p>`).join('')}</div></details>`;
  }
  function resultPanel(){const won=currentBattle.phase==='win';return `<div class="result-panel">${resultActions()}${storyResult()}<p class="eyebrow">${won?'EXPEDITION COMPLETE':'THE STARS AWAIT YOUR RETURN'}</p><h2>${won?'远征胜利':'暂别战场'}</h2><p>${won?`${reward?.first?'首次通关':'重访'}奖励已领取：${reward?.tickets||0} 星契 · ${reward?.dust||0} 星尘`:'本次获得 40% 成长经验。调整阵容或强化角色后再来挑战。'}</p><div class="experience-results"><div class="section-heading"><h3>旅团成长</h3><small>全体参战成员共享历练 · 包含退场成员</small></div>${(reward?.experience||[]).map(r=>{const h=C.hero(r.id);return `<div class="experience-row ${r.level>r.fromLevel?'level-up':''}"><span class="rarity" style="--rarity:${h.variant==='prism'?'#c7f4ff':'var(--'+h.rarity+')'}">${h.rarity}</span><div><strong>${h.name}</strong><span class="xp-level">LV.${r.fromLevel}${r.level>r.fromLevel?' → '+r.level+' · 升级！':''}</span>${experienceBar(r.id)}</div><b>${r.earned?'+'+r.earned+' EXP':'已满级'}</b></div>`;}).join('')}</div>${reward?.gear?.length?`<section class="loot-results"><p class="eyebrow">EXPEDITION SPOILS</p><h3>发现星铸装备</h3><div class="gear-grid">${reward.gear.map(item=>gearCard(item)).join('')}</div><button class="small-link" data-action="go-equipment">前往装备与整备 →</button></section>`:''}</div>`;}
  function heroPolitics(h){const f=C.Story.factions.find(f=>f.members.includes(h.id)),links=C.Story.relationships.filter(r=>r.ids.includes(h.id));return `<details class="hero-politics"><summary>阵营立场与人物关系</summary>${f?`<p><b>${f.name}</b> · ${f.promise}</p><p>共同利益：${f.interest}</p>`:'<p>独立契约者 · 保留自己的立场，不接受任何阵营的无条件代表。</p>'}${links.map(r=>`<p><b>${r.title}</b><br>${r.text}</p>`).join('')}</details>`;}
  function detail(id){
    const h=C.hero(id);if(!h)return;
    if(C.sealed(state,h)){delete dialog.dataset.hero;showDialog(`${dialogTop('未知契约')}<div class="sealed-dossier ${variantClass(h)}"><div class="sealed-dossier-symbol" aria-hidden="true">✧</div><p class="eyebrow">${h.rarity} · ${h.variant==='prism'?'炫光封印':'绯红封印'}</p><h2>？？？</h2><p>尚未回应的星，不会留下名字。</p><p>召唤获得后，立绘、真名与契约之力将一同揭晓。</p><strong>每次召唤概率 ${mysteryRate(h)}</strong><button class="btn primary" data-action="go-summon">前往星界召唤 →</button></div>`);return;}
    const own=!!state.owned[id],s=C.stats(state,id),cost=40+s.level*20;
    showDialog(`${dialogTop('契约者档案')}<div class="detail-layout" style="${artStyle(h)}"><div class="detail-portrait rarity-${h.rarity} ${variantClass(h)}">${portrait(h,true)}${cardOrnament(h)}<span class="rarity detail-rarity">${h.rarity}</span></div><div class="detail-text"><p class="eyebrow">${h.english} · ${h.title}</p><h2>${h.name}</h2><p class="muted" style="font-size:12px">${h.role} &nbsp; / &nbsp; ${own?'已缔结 · LV. '+s.level:'尚未缔结'}</p><p class="quote">“${h.quote}”</p><p class="story">${h.story}</p>${heroPolitics(h)}<div class="stats"><span>生命<b>${s.hp}</b></span><span>攻击<b>${s.atk}</b></span><span>技能消耗<b>${h.cost} AP</b></span></div>${own?experienceBar(id)+ascensionPanel(id):''}<div class="detail-skill"><strong>✧ ${h.skill}</strong><p>${h.detail}</p>${s.scale>1?'<p>成长与装备加成：伤害、治疗与护盾数值提升 '+Math.round((s.scale-1)*100)+'%。</p>':''}</div><div class="detail-actions">${own?`<button class="btn primary" data-action="upgrade" data-id="${id}" ${state.dust<cost||s.level>=C.levelCap(state,id)?'disabled':''}>${s.level>=C.levelCap(state,id)?'当前星级已满':'星尘强化 · ❖ '+cost}</button><button class="btn" data-action="toggle-team" data-id="${id}">${state.team.includes(id)?'移出旅团':'加入旅团'}</button><button class="btn" data-action="go-equipment" data-id="${id}">装备管理 · ${C.equipped(state,id).length}/3</button>`:`<button class="btn primary" data-action="go-summon">前往召唤 →</button>${id==='astra'?'<button class="btn" data-action="preview-ur">UR 演出预览</button>':''}`}</div></div></div>`);
    dialog.dataset.hero=id;
  }
  function openSummon(count=100){
    showDialog(`${dialogTop('批量召唤')}<div class="bulk-summon-heading"><p class="eyebrow">A THOUSAND STARS, ONE COVENANT</p><h3>一次，唤来万千星光。</h3><p>逐次抽取 · 保底连续累计 · 同名卡全部保留</p></div><div class="sweep-selector"><label for="summon-count">自定义召唤次数 <small>1～10,000 次</small></label><input id="summon-count" type="number" min="1" max="10000" step="1" value="${count}" inputmode="numeric" aria-describedby="summon-error"><div class="sweep-presets">${[10,100,1000,10000].map(n=>`<button data-action="summon-preset" data-count="${n}">${n.toLocaleString()} 次</button>`).join('')}</div></div><p id="summon-error" class="sweep-error" role="alert"></p><div id="summon-preview" aria-live="polite"></div><p class="sweep-note">每次消耗 1 枚星契，批量召唤概率与单抽一致。超过十次时按角色汇总战报，同名 UR 及以上的演出合并播放，可跳过。</p><div class="sweep-actions"><button class="btn" data-action="close">取消</button><button class="btn primary" data-action="summon-confirm">确认召唤</button></div>`,'sweep-dialog bulk-summon-dialog');updateSummonPreview();
  }
  function updateSummonPreview(){
    const input=dialog.querySelector('#summon-count');if(!input)return;
    const count=Number(input.value),p=C.drawPreview(state,count),button=dialog.querySelector('[data-action="summon-confirm"]');
    input.setAttribute('aria-invalid',String(!!p.error));dialog.querySelector('#summon-error').textContent=p.error||'';button.disabled=!!p.error;
    button.textContent=p.error?'请输入有效次数或补充星契':`召唤 ${count.toLocaleString()} 次 · ✧ ${count.toLocaleString()}`;
    dialog.querySelector('#summon-preview').innerHTML=`<div class="bulk-cost"><span>持有星契 <b>${state.tickets.toLocaleString()}</b></span><span>${p.error?'完成主线远征与扫荡可获得星契':`消耗 <b>${p.cost.toLocaleString()}</b> · 剩余 <b>${p.remaining.toLocaleString()}</b>`}</span></div>`;
    dialog.querySelectorAll('[data-action="summon-preset"]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.count)===count)));
  }
  async function drawCards(count){
    if(busy||batchRunning)return;const preview=C.drawPreview(state,count);if(preview.error){toast(preview.error);updateSummonPreview();return;}
    const r=await executeBatch('draw',{count});if(!r)return;
    lastSummon=r.cards;render();presentSummon(r.cards);
  }
  function stopSummon(){if(!summonSequence)return;summonSequence.dispose();summonSequence=null;soundscape.stopEffects();busy=false;}
  function presentSummon(cards,preview=false){
    stopSummon();
    let heroes=cards.map(r=>C.hero(r.id)).filter(h=>['UR','SP','SSP'].includes(h.rarity));
    if(cards.length>10)heroes=[...new Map(heroes.map(h=>[h.id,h])).values()];
    if(!heroes.length){reveal(cards,preview);sound('summon');return;}
    delete dialog.dataset.hero;showDialog('', 'summon-cinematic-dialog');busy=true;
    const sequence=new window.EclipseSummon.Sequence(heroes,{
      reducedMotion,
      onShow:(h,index,total)=>{soundscape.stopEffects();dialog.innerHTML=window.EclipseSummon.markup(h,index,total);if(cards.length>10)dialog.querySelector('.summon-theater').insertAdjacentHTML('beforeend',`<p class="batch-cinematic-note">本批 ${cards.length.toLocaleString()} 次 · ${h.name} ×${cards.filter(r=>r.id===h.id).length} · 同名演出合并</p>`);dialog.querySelector('[data-action="skip-summon"]').focus({preventScroll:true});sound('summon-charge');},
      onReveal:h=>{const theater=dialog.querySelector('.summon-theater');if(!theater)return;theater.dataset.phase='reveal';dialog.querySelector('[data-action="next-summon"]').disabled=false;sound(h.variant==='prism'?'sp-prism':h.rarity==='SP'?'sp':'ur');},
      onDone:()=>{summonSequence=null;busy=false;soundscape.stopEffects();reveal(cards,preview);}
    });summonSequence=sequence;sequence.start();
  }
  function reveal(cards,preview=false){
    delete dialog.dataset.hero;
    if(cards.length>10){revealBulk(cards);return;}
    showDialog(`${dialogTop(preview?'终焉星神 · 演出预览':'群星回应了你的呼唤')}<p class="summon-subtitle">${preview?'预览不消耗星契，不计入收集与保底':'契约已缔结 · 新角色已加入图鉴 · 重复卡已保留为升星材料，并额外获得星尘'}</p><div class="reveal-grid ${cards.length===1?'single':''}">${cards.map((r,i)=>{const h=C.hero(r.id);return `<button class="reveal-card rarity-${h.rarity} ${variantClass(h)} ${['UR','SP','SSP'].includes(h.rarity)?'ur':''}" style="${artStyle(h)};--delay:${i}" data-action="detail" data-id="${h.id}" aria-label="查看召唤结果${h.rarity} ${h.name}">${portrait(h,true)}${cardOrnament(h)}${rarity(h)}<div class="reveal-caption"><h3>${h.name}</h3><small class="${r.isNew?'new':''}">${preview?'领域 · 终焉展开':r.isNew?'NEW · 新的契约':`同名卡 +1 · 星尘 +${r.dust}`}${r.guarantee?' · '+r.guarantee:''}</small></div></button>`;}).join('')}</div><div class="summon-finish"><button class="btn" data-action="close">收下星光</button>${preview?'':`<button class="btn primary" data-action="draw" data-count="10" ${state.tickets<10?'disabled':''}>再缔结十次 · ✧ 10</button><button class="small-link" data-action="go-team">前往编队 →</button>`}</div>`, 'summon-dialog summon-flash');dialog.querySelector('.close')?.focus({preventScroll:true});
  }
  function revealBulk(cards){
    const groups=new Map();for(const r of cards){const old=groups.get(r.id);if(old){old.count++;old.dust+=r.dust;old.isNew ||= r.isNew;}else groups.set(r.id,{...r,count:1});}
    const sorted=[...groups.values()].sort((a,b)=>C.rankOf(C.hero(b.id))-C.rankOf(C.hero(a.id))),dust=cards.reduce((n,r)=>n+r.dust,0),fresh=sorted.filter(r=>r.isNew).length;
    showDialog(`${dialogTop('万千星光 · 召唤战报')}<div class="bulk-summary"><p class="eyebrow">COVENANTS SEALED</p><h3>${cards.length.toLocaleString()} 次召唤完成</h3><p>获得 ${groups.size} 位角色的契约 · 新解锁 ${fresh} 位 · 额外星尘 +${dust.toLocaleString()}</p><p class="sweep-note">所有同名卡已保留；每一次召唤均已计入保底。点击角色查看档案。</p></div><div class="sweep-rarities">${C.RANKS.slice().reverse().map(rank=>{const n=sorted.filter(r=>C.hero(r.id).rarity===rank).reduce((a,r)=>a+r.count,0);return n?`<span style="--rarity:var(--${rank})"><b class="rarity">${rank}</b> × ${n.toLocaleString()}</span>`:'';}).join('')}</div><div class="reveal-grid bulk-reveal-grid">${sorted.map((r,i)=>{const h=C.hero(r.id);return `<button class="reveal-card rarity-${h.rarity} ${variantClass(h)}" style="${artStyle(h)};--delay:${Math.min(i,5)}" data-action="detail" data-id="${h.id}" aria-label="${h.rarity} ${h.name}，获得 ${r.count} 张">${portrait(h,true)}${cardOrnament(h)}${rarity(h)}<span class="bulk-card-count">× ${r.count.toLocaleString()}</span><div class="reveal-caption"><h3>${h.name}</h3><small class="${r.isNew?'new':''}">${r.isNew?'NEW · 首次缔结':'契约已收集'} · 星尘 +${r.dust.toLocaleString()}</small></div></button>`;}).join('')}</div><div class="summon-finish"><button class="btn" data-action="close">收下星光</button><button class="btn primary" data-action="draw" data-count="${cards.length}" ${state.tickets<cards.length?'disabled':''}>再召唤 ${cards.length.toLocaleString()} 次</button><button class="btn" data-action="summon-custom">自定义次数</button></div>`,'summon-dialog bulk-results-dialog');dialog.scrollTop=0;
  }
  function rules(){delete dialog.dataset.hero;showDialog(`${dialogTop('召唤概率与保底')}<div class="help-copy"><p>常驻卡池共有 ${C.HEROES.length} 位角色。以下为每次召唤的基础概率，单抽、十连与批量召唤完全相同。</p><table class="rate-table"><thead><tr><th>稀有度</th><th>包含角色</th><th>基础概率</th></tr></thead><tbody>${C.HEROES.filter(h=>C.rankOf(h)>=5).reverse().map(h=>`<tr><td class="${variantClass(h)}">${h.rarity} · ${h.variant==='prism'?'炫光':'红色'}</td><td>${C.sealed(state,h)?'？？？':h.name}</td><td>${mysteryRate(h)}</td></tr>`).join('')}${C.RANKS.slice(0,5).reverse().map(r=>`<tr><td class="rarity" style="--rarity:var(--${r})">${r}</td><td>${C.HEROES.filter(h=>h.rarity===r).map(h=>h.name).join('、')}</td><td>${(C.RATES[C.RANKS.indexOf(r)]*100).toFixed(r==='N'?3:1).replace(/\.0$/,'')}%</td></tr>`).join('')}</tbody></table><p>七位红色 SP 各为万分之一，四位炫光 SSP 各为十万分之一；SP 总概率为 0.07%，SSP 为 0.004%，合计 0.074%。SP 与 SSP 均不设保底，保底不会改变它们的概率。N 至 UR 同档内等概率，单个角色概率为该档总概率除以该档角色数量。</p><h3>保底持续累计，不按十连批次重置</h3><p>连续 10 次内必得 SR 或以上，80 次内必得 SSR 或以上，200 次内必得 UR 或以上。获得某档或更高稀有度，重置对应档位计数；同时触发时兑现最高档。自然抽中 SP 或 SSP 时保留该角色，并重置全部保底计数。保底不保证指定角色。</p><p>距 SR 或以上：${10-state.pity.sr} 次 · SSR 或以上：${80-state.pity.ssr} 次 · UR 或以上：${200-state.pity.ur} 次。</p><h3>封印与召唤演出</h3><p>未抽中的 SP 与 SSP 在图鉴中显示“？？？”，获得后才解锁档案与动态立绘。UR、红色 SP、炫光 SSP 各有专属召唤演出；十连中的稀有契约按抽取顺序播放，可跳过。超过十次的批量召唤合并同名稀有角色演出，结果按角色汇总。奖励在演出前保存，跳过或关闭不会丢失角色。</p><h3>重复角色</h3><p>重复卡保留为升星材料，N / R / SR / SSR / UR / SP / SSP 分别额外获得 8 / 15 / 30 / 80 / 200 / 600 / 600 星尘。所有资源均为免费试玩资源。</p></div>`);}
  function help(){delete dialog.dataset.hero;showDialog(`${dialogTop('旅团长，欢迎来到星界')}<div class="help-copy"><h3>01 · 缔结你的契约</h3><p>你已拥有米洛、岚雀与绯织，以及 200 枚免费星契。前往星界召唤进行单抽、十连或自定义最多 10,000 次的批量召唤，召唤到的角色会立刻加入图鉴。</p><h3>02 · 组建旅团</h3><p>在「旅团编队」点击头像小卡加入最多五名不同角色。可用契约者默认按稀有度从高到低排序，也可按等级排序；同稀有度优先显示高等级，同等级优先显示高稀有度。越靠前的存活角色越容易承受攻击。可使用推荐编队，也可移出后重新加入来调整顺序。</p><h3>03 · 策略远征</h3><p>每回合共享 5 点行动点，上回合最多保留 2 点。出征后角色会自动选择目标并使用普攻、技能或防御。每名角色每回合行动一次。无需点击角色和技能，直接观看战斗即可。</p><p>米洛自动治疗生命比例最低的存活队友；塞勒涅护盾保护全队；阿斯忒拉的领域每场限用一次。敌方每第三回合发动全体攻击。</p><h3>04 · 让群星成长</h3><p>每位参战成员获得章节标注的完整经验，战败获得 40%，撤退没有经验。经验满后自动升级，多余经验保留，达到当前星级上限后不再积累。星尘可直接强化一级，每级增加 6% 基础属性与技能效果。</p><h3>05 · 同名卡升星</h3><p>0 星上限 20 级。达到 20 / 30 / 40 / 50 / 60 级时，消耗一张额外的同名卡升至下一星，最高 5 星、70 级。每星增加 15% 基础属性与技能效果，保留原等级。角色稀有度不变。抽到重复卡会保留卡片，并额外赠送星尘。</p><h3>06 · 装备与远征</h3><p>装备仅在星铸秘境掉落，品质与 2～4 条副属性随机。强化每次提升主属性并提升或新增一条副属性，最高 +15。武器加攻击，护甲加生命，圣物加属性与技能。SP / SSP 分别为绯红与炫光装备，仅在绯月王庭和零界星殿获得。每名角色各穿戴一件，各件只能由一人使用，可卸下转交。全部装备在出征时计入战斗属性。点击库存装备可升星，消耗一件同名、0 星、未强化且未穿戴的装备与星尘；每星提升 25% 初始属性，最高 5 星，无等级限制。主装备可以保持穿戴，已升星装备不会被作为材料。</p><h3>07 · 批量扫荡</h3><p>首次通关后，可在关卡下方选择「批量扫荡」。输入 1～1,000,000 的整数，也可快捷选择最高 100 万轮。无需消耗资源，也无需播放战斗，按重访奖励立即结算：主线每轮 3 星契、该关卡星尘、当前全队经验；装备秘境不产出星契，每轮掉落一件随机词条装备。经验受当前星级上限限制；不重复领取首通奖励，不自动解锁下一关。同款装备在战报中合并展示，实际各自存入库存。</p><h3>存档与体验范围</h3><p>收集、等级、编队与章节进度自动保存在当前浏览器；进行中的战斗不保存。切换浏览器或清除网站数据不会保留进度。当前为108名角色、48关、16个区域和8档装备秘境的 3D 自动战斗试玩版。拖动战场可以旋转视角，声音设置可调整音量与环境音乐。支持暂停、1× / 2× / 4×倍速与跳过动画；离开战斗页面或切换到后台时自动暂停。</p></div><div class="summon-finish"><button class="btn primary" data-action="close">星途由此开始 →</button></div>`);}
  function toggleTeam(id){if(!state.owned[id])return;const next=state.team.includes(id)?state.team.filter(x=>x!==id):[...state.team,id];if(!C.setTeam(state,next)){toast('旅团最多五人，请先移出一位角色。');return;}persist();render();toast(state.team.includes(id)?`${C.hero(id).name}已加入旅团`:`${C.hero(id).name}已移出旅团`);if(dialog.open&&dialog.dataset.hero===id)detail(id);}
  function syncPlayback(){
    soundscape.setLobby(!currentBattle||player?.finished||dialog.open||page!==(currentBattle.mode==='dungeon'?'dungeon':'adventure'));
    if(!player){soundscape.setSuspended(document.hidden);return;}
    player.setBlocked(document.hidden||page!==(currentBattle?.mode==='dungeon'?'dungeon':'adventure')||dialog.open||sceneLoading||!!sceneError);playbackState();
  }
  function playbackState(){
    if(!player)return;
    const visible=!document.hidden&&page===(currentBattle?.mode==='dungeon'?'dungeon':'adventure')&&!dialog.open;
    battleScene?.setPlayback({running:visible&&(player.running||player.finished),speed:player.speed});
    soundscape.setLobby(player.finished||dialog.open||player.paused||page!==(currentBattle?.mode==='dungeon'?'dungeon':'adventure'));soundscape.setSuspended(document.hidden);
    const el=document.getElementById('playback-state');if(el)el.textContent=sceneLoading?'正在准备 3D 战场':sceneError?'战场载入中断':player.paused?'战斗已暂停':player.blocked?'战斗暂时暂停':'旅团正在自动作战';
    const toggle=main.querySelector('[data-action="pause-battle"]');if(toggle){toggle.textContent=player.paused?'继续战斗':'暂停战斗';toggle.disabled=sceneLoading||!!sceneError;}
    main.querySelectorAll('[data-action="speed"]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.speed)===player.speed)));
  }
  function stopBattle(){sceneVersion++;player?.stop();battleScene?.dispose();battleScene=null;player=null;currentBattle=null;lastEvent=null;sceneLoading=false;sceneError='';soundscape.setBattle(false);soundscape.stopEffects();}
  async function loadBattleScene(b,version){
    let scene;
    try{
      const {BattleScene}=await import('./battle3d.js');
      if(version!==sceneVersion||currentBattle!==b)return;
      const host=main.querySelector('.battle-viewport')||Object.assign(document.createElement('div'),{className:'battle-viewport'});host.replaceChildren();
      scene=new BattleScene(host,b,C,{onImpact:ev=>{if(version===sceneVersion)soundscape.combat(ev,player?.speed||1,false,true);},onProgress:(done,total)=>{const el=main.querySelector('.scene-notice');if(el&&version===sceneVersion)el.textContent=`正在加载 3D 角色 ${done} / ${total}`;},onError:()=>{if(version!==sceneVersion)return;sceneError='画面已中断，请重新加载；也可跳过演出完成本场战斗。';render();syncPlayback();}});
      battleScene=scene;await scene.ready;
      if(version!==sceneVersion||currentBattle!==b){scene.dispose();return;}
      sceneLoading=false;render();if(player.finished)scene.finish(b.phase==='win');syncPlayback();
    }catch(e){
      if(version!==sceneVersion)return;scene?.dispose();battleScene=null;sceneLoading=false;sceneError='请重新加载战场。若浏览器不支持 3D，也可以跳过演出完成结算。';console.error('3D scene:',e);render();syncPlayback();
    }
  }
  function startBattle(stage,mode='story'){
    const b=C.battle(state,stage,mode);if(b.error){toast(b.error);return;}
    stopBattle();currentBattle=b;reward=null;lastEvent=null;sceneLoading=true;page=mode==='dungeon'?'dungeon':'adventure';history.replaceState(null,'','#'+page);
    player=new window.BattlePlayer({battle:b,step:C.autoStep,onState:playbackState,onStep:ev=>{if(currentBattle!==b)return;lastEvent=ev;render();if(ev){battleScene?.playEvent(ev);if(battleScene&&ev.kind==='attack'&&ev.fx==='slash')sound('step');}},onFinish:()=>{if(currentBattle!==b)return;reward=C.claim(state,b);persist();battleScene?.finish(b.phase==='win');soundscape.setBattle(false);soundscape.stopEffects();soundscape.settlement(b.phase==='win',reward);battleScene?.dispose();battleScene=null;sceneVersion++;sceneLoading=false;render();requestAnimationFrame(()=>main.querySelector('.result-actions button:not(:disabled)')?.focus({preventScroll:true}));}});
    if(state.battleSettings.autoSkip){sceneLoading=false;player.skip();window.scrollTo({top:0,behavior:'instant'});return;}
    render();player.setBlocked(true);player.start();sound('start');soundscape.setBattle(true,C.battleStage(b));syncPlayback();loadBattleScene(b,sceneVersion);window.scrollTo({top:0,behavior:'instant'});
  }
  function audioSettings(){delete dialog.dataset.hero;showDialog(`${dialogTop('声音设置')}<div class="sound-settings"><p>刀剑、箭矢、元素法术与治疗拥有不同声音。全页面环境音乐、刀剑与命中采样、元素法术、锻造强化和召唤演出均有独立音效。首次点击或按 Enter 开启，浏览器恢复后可再次点击声音按钮。</p><label for="master-volume">总体音量 <output id="master-volume-value">${state.audio.volume}%</output></label><input id="master-volume" type="range" min="0" max="100" value="${state.audio.volume}" data-audio="volume"><label for="music-volume">环境音乐 <output id="music-volume-value">${state.audio.music}%</output></label><input id="music-volume" type="range" min="0" max="100" value="${state.audio.music}" data-audio="music"><label class="music-toggle"><input type="checkbox" data-audio="musicEnabled" ${state.audio.musicEnabled?'checked':''}>启用环境与战斗音乐</label><div class="audio-status" role="status" id="audio-status"></div><button class="btn primary" data-action="enable-sound">开启声音并试听召唤</button><div class="sound-preview"><button class="btn" data-action="preview-sound" data-fx="slash">试听剑击</button><button class="btn" data-action="preview-sound" data-fx="fire">试听火焰</button><button class="btn" data-action="preview-sound" data-fx="heal">试听治疗</button><button class="btn" data-action="preview-ui-sound" data-fx="ascend">试听升星</button><button class="btn" data-action="preview-ui-sound" data-fx="loot">试听掉落</button></div><p>音量与音乐设置会随存档保留。开启声音不会消耗游戏资源。</p></div>`);}
  function enableSound(){state.muted=false;if(!state.audio.volume)state.audio.volume=65;soundscape.configure(state.audio,false);persist();sound('summon');const slider=document.getElementById('master-volume');if(slider){slider.value=state.audio.volume;document.getElementById('master-volume-value').textContent=state.audio.volume+'%';}}
  function activateSound(e){if(state.muted||e.target.closest?.('#sound'))return;if(e.type==='keydown'&&!['Enter',' '].includes(e.key))return;soundscape.unlock().then(ready=>{if(ready)updateWallet();});}
  document.addEventListener('pointerdown',activateSound,{capture:true});
  document.addEventListener('keydown',activateSound,{capture:true});
  soundscape.onStatus=()=>updateWallet();
  setInterval(()=>{const el=document.getElementById('audio-status');if(!el)return;const status=state.muted?'已静音':!state.audio.volume?'总体音量为 0':soundscape.ctx?.state==='running'?'声音已开启':soundscape.ctx?'声音暂停，点击下方重新开启':'等待点击开启声音';const level=soundscape.signalLevel();if(level>.002)el.dataset.lastSignal=String(Date.now());const audible=Date.now()-Number(el.dataset.lastSignal||0)<1500;el.textContent=status+(soundscape.audioError?' · '+soundscape.audioError:'')+(audible?' · 正在输出音频':'')+` · 音效素材 ${soundscape.buffers.size}/11`;el.dataset.active=String(level>0.002);},150);
  document.addEventListener('click',e=>{
    if(batchRunning)return;
    const button=e.target.closest('button, a.brand');if(!button||button.disabled)return;
    if(button.matches('a.brand')){e.preventDefault();navigate('summon');return;}
    if(button.dataset.tab){navigate(button.dataset.tab);sound('page');return;}
    const action=button.dataset.action,id=button.dataset.id;
    if(['close','detail','rates','filter','history','gear-gallery','gear-design','gear-detail','gear-filter','gear-slot','gear-rates','gear-ascend'].includes(action))sound();
    if(action==='close'){dialog.close();delete dialog.dataset.hero;}
    else if(action==='feature-select'){featuredHero=id;render();sound('travel');}
    else if(action==='detail')detail(id);
    else if(action==='draw')drawCards(Number(button.dataset.count));
    else if(action==='summon-custom')openSummon();
    else if(action==='summon-preset'){dialog.querySelector('#summon-count').value=button.dataset.count;updateSummonPreview();}
    else if(action==='summon-confirm')drawCards(Number(dialog.querySelector('#summon-count').value));
    else if(action==='summon-receipt'&&lastSummon)reveal(lastSummon);
    else if(action==='rates')rules();
    else if(action==='filter'){filter=button.dataset.filter;render();}
    else if(action==='history'){delete dialog.dataset.hero;showDialog(`${dialogTop('召唤记录')}<p class="info-note">最近 30 次召唤 · 累计 ${state.pulls} 次</p><div class="history-list">${state.history.length?state.history.map(r=>{const h=C.hero(r.id);return `<div class="history-line"><small>第 ${r.pull} 次</small><span style="${artStyle(h)}">${rarity(h)} &nbsp; ${h.name}</span><small>${r.guarantee||'星界召唤'}</small></div>`;}).join(''):'<p class="info-note">还没有召唤记录，群星正在等待你的回应。</p>'}</div>`);}
    else if(action==='upgrade'){const result=C.upgrade(state,id);if(result.error){toast(result.error);return;}persist();render();detail(id);toast(`${C.hero(id).name}提升至 ${result.level} 级`);sound('level');}
    else if(action==='region'){region=Number(button.dataset.region);render();sound('travel');}
    else if(action==='ascend'){const r=C.ascend(state,id);if(r.error){toast(r.error);return;}persist();render();detail(id);dialog.classList.add('ascended');sound('ascend');toast(`${C.hero(id).name}觉醒至 ${r.stars} 星！等级上限提升至 ${r.cap}。`);}
    else if(action==='claim-armory'){if(C.claimArmory(state)){persist();render();sound('loot');toast('已获得 600 星尘，前往星铸秘境获取装备。');}}
    else if(action==='go-equipment'){dialog.close();if(id)equipmentHero=id;gearFilter='ALL';slotFilter='ALL';navigate('equipment');}
    else if(action==='gear-gallery')gearGallery();
    else if(action==='gear-design')gearDesign(id);
    else if(action==='gear-expedition'||action==='go-dungeon'){dialog.close();if(currentBattle&&player?.finished)stopBattle();navigate('dungeon');}
    else if(action==='gear-enhance'){const uid=Number(button.dataset.uid);button.disabled=true;const r=C.enhanceGear(state,uid,Number(button.dataset.level));if(r.error){toast(r.error);gearDetail(uid);return;}lastEnhancement={uid,...r};persist();render();gearDetail(uid);sound('enhance');toast(`强化 +${r.level} · ${r.change.added?'新增':'提升'}${C.Gear.AFFIXES.find(a=>a.id===r.change.id).name}`);}
    else if(action==='gear-ascend')confirmGearAscension(Number(button.dataset.uid));
    else if(action==='confirm-gear-ascend'){const uid=Number(button.dataset.uid),material=Number(dialog.querySelector('#gear-material')?.value);button.disabled=true;const r=C.ascendGear(state,uid,material,Number(button.dataset.stars));if(r.error){toast(r.error);gearDetail(uid);return;}persist();render();gearDetail(uid);dialog.classList.add('ascended');sound('ascend');toast(`${C.gearStats(C.Inventory.get(state,uid)).name}已升至 ${r.stars} 星！`);}
    else if(action==='claim-dawn'){if(C.claimDawn(state)){persist();render();sound('summon');toast('已领取泰莎、卢恩、50 枚星契与 900 星尘。');}}
    else if(action==='gear-detail')gearDetail(Number(button.dataset.uid));
    else if(action==='gear-page'){gearPage=Number(button.dataset.page);render();main.querySelector('.inventory-pagination')?.scrollIntoView({block:'start'});}
    else if(action==='gear-filter'){gearPage=0;gearFilter=button.dataset.filter;render();}
    else if(action==='gear-slot'){gearFilter='ALL';slotFilter=button.dataset.slot;gearPage=0;render();main.querySelector('.gear-grid')?.scrollIntoView({behavior:'smooth',block:'center'});}
    else if(action==='gear-rates')gearRules();
    else if(action==='equip'){const r=C.equip(state,id,Number(button.dataset.uid));if(r.error){toast(r.error);return;}persist();render();gearDetail(Number(button.dataset.uid));sound('equip');toast('装备已穿戴，下次出征生效。');}
    else if(action==='unequip'){C.unequip(state,id,button.dataset.slot);persist();render();dialog.close();sound('unequip');toast('已卸下，装备保留在库存。');}
    else if(action==='enable-sound')enableSound();
    else if(action==='preview-ui-sound')sound(button.dataset.fx);
    else if(action==='toggle-team' ||action==='remove')toggleTeam(id);
    else if(action==='auto-team'){C.setTeam(state,C.recommendTeam(state));persist();render();toast('推荐编队已保存：承伤在前，治疗与领域在后。');}
    else if(action==='go-summon'){dialog.close();navigate('summon');}
    else if(action==='go-team'){dialog.close();navigate('team');}
    else if(action==='preview-ur'){presentSummon([{id:'astra'}],true);}
    else if(action==='skip-summon')summonSequence?.finish();
    else if(action==='next-summon')summonSequence?.advance();
    else if(action==='sweep-open')openSweep(Number(button.dataset.stage),Number(button.dataset.count)||10,button.dataset.mode||'story');
    else if(action==='sweep-preset'&&pendingSweep){dialog.querySelector('#sweep-count').value=button.dataset.count;updateSweepPreview();}
    else if(action==='sweep-confirm')runSweep();
    else if(action==='sweep-receipt'&&lastSweep)showSweepResults(lastSweep);
    else if(action==='story-journal')storyJournal();
    else if(action==='story-choice'){const r=C.Story.choose(state,Number(button.dataset.stage),Number(button.dataset.choice));if(r.error)toast(r.error);else {persist();render();if(dialog.open)storyJournal();toast('决定已写入旅途档案。');}}
    else if(action==='battle')startBattle(Number(button.dataset.stage),button.dataset.mode||'story');
    else if(action==='pause-battle'&&player)player.setPaused(!player.paused);
    else if(action==='speed'&&player)player.setSpeed(Number(button.dataset.speed));
    else if(action==='skip-battle'&&player){soundscape.stopEffects();player.skip();}
    else if(action==='cinematic-camera'&&battleScene){battleScene.setCinematic(!battleScene.cinematic);render();}
    else if(action==='reset-camera')battleScene?.resetCamera();
    else if(action==='retry-scene'&&currentBattle){battleScene?.dispose();battleScene=null;sceneLoading=true;sceneError='';sceneVersion++;render();syncPlayback();loadBattleScene(currentBattle,sceneVersion);}
    else if(action==='preview-sound'){soundscape.combat({actor:{side:'ally'},fx:button.dataset.fx,kind:'skill',impacts:[{type:button.dataset.fx==='heal'?'heal':'damage',value:100}]},1,true);}
    else if(action==='claim-gift'){const gift=C.claimExpansion(state);if(gift){persist();render();toast('已领取50枚星契、布兰与芙萝拉。可前往旅团编队加入新伙伴。');sound('summon');}}
    else if(action==='retreat'){if(['win','lose'].includes(currentBattle.phase)){player?.finish();stopBattle();render();return;}delete dialog.dataset.hero;showDialog(`${dialogTop('暂时撤回营地？')}<p class="info-note">本次战斗将结束，不会扣除星契或星尘。下次挑战时全队恢复生命。</p><div class="summon-finish"><button class="btn" data-action="close">继续战斗</button><button class="btn danger" data-action="confirm-retreat">确认撤退</button></div>`);}
    else if(action==='confirm-retreat'){dialog.close();stopBattle();render();}
    else if(action==='leave-battle'){if(currentBattle.mode!=='dungeon')region=Math.min(C.REGIONS.length-1,Math.floor((currentBattle.stage+(currentBattle.phase==='win'?1:0))/3));stopBattle();render();}
  });
  document.addEventListener('change',e=>{if(batchRunning)return;if(e.target.matches('[data-auto-skip]')){state.battleSettings.autoSkip=e.target.checked;persist();if(e.target.checked&&player&&!player.finished){soundscape.stopEffects();player.skip();}return;}if(e.target.id==='team-sort'){teamSort=e.target.value==='level'?'level':'rarity';render();document.getElementById('team-sort')?.focus({preventScroll:true});}if(e.target.id==='gear-page-number'){const n=Number(e.target.value);if(Number.isSafeInteger(n)&&n>=1){gearPage=n-1;render();}}if(e.target.id==='equipment-hero'){equipmentHero=e.target.value;render();}if(e.target.id==='gear-slot-filter'){slotFilter=e.target.value;gearPage=0;render();requestAnimationFrame(()=>main.querySelector('.result-actions button:not(:disabled)')?.focus({preventScroll:true}));}});
  document.getElementById('help').addEventListener('click',help);
  document.getElementById('sound').addEventListener('click',()=>{if(state.muted||soundscape.ctx?.state!=='running'||state.audio.volume===0){enableSound();return;}state.muted=true;soundscape.configure(state.audio,true);persist();});
  document.getElementById('audio-settings').addEventListener('click',audioSettings);
  document.addEventListener('input',e=>{const field=e.target.dataset.audio;if(!['volume','music','musicEnabled'].includes(field))return;state.audio[field]=field==='musicEnabled'?e.target.checked:Math.max(0,Math.min(100,Number(e.target.value)));soundscape.unlock();soundscape.configure(state.audio,state.muted);persist();const output=document.getElementById(e.target.id+'-value');if(output)output.textContent=e.target.value+'%';});
  dialog.addEventListener('click',e=>{if(e.target===dialog&&!batchRunning){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
  dialog.addEventListener('cancel',e=>{if(batchRunning)e.preventDefault();});
  dialog.addEventListener('close',()=>{if(dialog.open)return;stopSummon();pendingSweep=null;syncPlayback();});
  document.addEventListener('input',e=>{if(e.target.id==='sweep-count')updateSweepPreview();if(e.target.id==='summon-count')updateSummonPreview();});
  document.addEventListener('visibilitychange',()=>{syncPlayback();if(!document.hidden&&soundscape.ctx&&!state.muted)soundscape.unlock();});
  window.addEventListener('pageshow',()=>{syncPlayback();if(soundscape.ctx&&!state.muted)soundscape.unlock();});
  window.addEventListener('pagehide',()=>{summonSequence?.finish();player?.setBlocked(true);soundscape.setSuspended(true);});
  window.addEventListener('pageshow',syncPlayback);
  window.addEventListener('hashchange',()=>{const p=location.hash.slice(1);if(['summon','collection','team','equipment','adventure','dungeon'].includes(p)){page=p;render();syncPlayback();}});
  if(QA)document.querySelector('.footer').firstElementChild.textContent='测试存档 · 不影响正式试玩进度';
  persist();render();syncPlayback();
})();
