(function(root){'use strict';
const Data=typeof module!=='undefined'&&module.exports?require('./covenant-data.js'):root.EclipseCovenantData;
const Skills=typeof module!=='undefined'&&module.exports?require('./covenant-skills.js'):root.EclipseCovenantSkills;
const PHASES=['焰','潮','霆','岚','辉','幽'],FX={焰:'fire',潮:'tide',霆:'lightning',岚:'arrow',辉:'solar',幽:'time'};
const clamp=(n,min,max)=>Math.max(min,Math.min(max,Number(n)||0));
function install(Base){
 const C={...Base,skillVersion:15,SkillData:Data};
 const heroes=Base.HEROES.map(h=>{const d=Data.heroes[h.id];if(!d)throw Error('Missing skill '+h.id);return {...h,kit:d,phase:d.phase,role:d.role+' · '+d.phase,cost:d.cost,skill:d.active.split('：')[0],detail:d.active.split('：').slice(1).join('：'),ultimateName:d.ultimate.split('：')[0],fx:FX[d.phase],color:Data.phases.find(p=>p.id===d.phase).color};});
 C.HEROES=heroes;C.hero=id=>heroes.find(h=>h.id===id);C.availableHeroes=(s,sort)=>Base.availableHeroes(s,sort).map(h=>C.hero(h.id));
 const guards=['守护','反击','护盾','推进','站位'],healers=['续航','净化'],support=['调度','标记','记录','均衡','联结','转移','见证','契约','资源','时序','共鸣','解约'];
 for(const h of heroes){const r=[.94,.97,1,1.03,1.06,1.08,1.08][Base.rankOf(h)],role=h.kit.role;h.hp=(guards.includes(role)?420:healers.includes(role)?345:350)*r;h.atk=(guards.includes(role)?66:healers.includes(role)?70:support.includes(role)?72:82)*r;}
 C.stats=(s,id)=>{const old=Base.stats(s,id),h=C.hero(id),role=h.kit.role,r=[.94,.97,1,1.03,1.06,1.08,1.08][Base.rankOf(h)],hp=guards.includes(role)?420:healers.includes(role)?345:350,atk=guards.includes(role)?66:healers.includes(role)?70:support.includes(role)?72:82,scale=(1+(old.level-1)*.06)*(1+old.stars*.04),g=old.bonus;return {...old,hp:Math.round((hp*r*scale+g.hp)*(1+g.hpPercent)),atk:Math.round((atk*r*scale+g.atk)*(1+g.atkPercent)),scale:scale*(1+g.power),baseScale:scale,skillBonus:1+g.power};};
 function settings(s){const raw=s.battleSettings||{};return {...raw,autoSkip:raw.autoSkip===true,tactic:['balanced','burst','sustain'].includes(raw.tactic)?raw.tactic:'balanced',healAt:clamp(raw.healAt??.68,.3,.85),allowSacrifice:raw.allowSacrifice!==false,policies:Object.fromEntries(Object.entries(raw.policies||{}).filter(([id])=>C.hero(id)).map(([id,entry])=>{const p=entry&&typeof entry==='object'?entry:{};return [id,{partner:C.hero(p.partner)?p.partner:null,partner2:C.hero(p.partner2)?p.partner2:null,stance:p.stance==='release'?'release':'store',mode:['auto','save','attack','support','wait'].includes(p.mode)?p.mode:'auto',target:['auto','boss','healer','back'].includes(p.target)?p.target:'auto'}];}))};}
 const restore=Base.restoreState;C.restoreState=raw=>{const s=restore(raw);s.battleSettings=settings(raw||s);return s;};C.freshState=()=>{const s=Base.freshState();s.battleSettings=settings(s);return s;};
 const living=b=>b.allies.filter(a=>a.hp>0),foes=b=>b.enemies.filter(e=>e.hp>0);
 function initAlly(a){Object.assign(a,{energy:0,readyRound:1,m:{},statuses:[],wards:a.shield?[{value:a.shield,source:null,expires:3,recycled:false}]:[],dots:[],debts:[],revived:false,shield:a.shield||0});}
 C.prepareBattle=(b,s,{replaceStats=false}={})=>{
  b.skillVersion=15;b.tactics=settings(s);b.actionDebt=0;b.extraAP=0;b.extraEnergy=0;b.actionSerial=0;b.reactionSerial=0;b.dispatchDepth=0;b.enemyQueue=null;b.field=0;b.domain=null;b.lastReaction=null;b.usedUltimates=[];
  b.report={damage:{},healing:{},assists:{},guarding:{},cleanses:{},poise:{},combos:0,breaks:0,protection:0,passive:0};b.log=['星契共鸣 · 普攻免费，主动技消耗行动点；每人3契能可释放终式。'];
  for(const a of b.allies){if(replaceStats){const n=C.stats(s,a.id);Object.assign(a,{hp:n.hp,maxHp:n.hp,atk:n.atk,scale:n.scale,skillBonus:n.skillBonus});}a.skillBonus??=1;initAlly(a);a.m.yesterday=a.hp;if(a.id==='pero')a.m.crates=2;if(a.id==='cassia')a.m.medicine=3;if(a.id==='deluge')a.m.release=b.tactics.policies?.deluge?.stance==='release'?1:0;}
  b._heroPhase=Object.fromEntries(b.allies.map(a=>[a.id,C.hero(a.id).phase]));const def=b.definition||Base.battleStage(b),boss=def?.boss?b.enemies.reduce((a,e)=>e.maxHp>a.maxHp?e:a):null;
  if(def?.final&&b.mode!=='explore'){boss.hp=boss.maxHp=Math.round(boss.maxHp*.85);boss.atk=Math.round(boss.atk*.65);}
  b.enemies.forEach((e,i)=>{Object.assign(e,{marks:[],dots:[],statuses:[],turns:0,poise:boss===e?100:45,maxPoise:boss===e?100:45,weak:PHASES[((b.stage||0)+i)%6],resist:PHASES[((b.stage||0)+i+3)%6],shield:0,burn:0,frozen:0,marked:false,exposedUntil:0,sturdyUntil:0,delayedRound:0});if(boss===e)e.boss={phase:'charge',charge:3,cycle:0,ward:0,maxWard:0};else delete e.boss;
   if(def?.final&&e===boss)e.finalAct=1;e.profile=def?.final?(e===boss?'shield':['shield','healer'][i%2]):['assault','shield','burn','buff','healer','summon','seal','charge'][((b.stage||0)+i)%8];
   if(e.profile==='shield'){e.shield=Math.round(e.maxHp*.14);e.statuses.push({key:'fortify',value:.15,expires:3,source:null});}
  });const start=event(b,null,'setup','契约缔结');for(const a of b.allies)if(['piscia','vega'].includes(a.id)){const candidates=living(b).filter(x=>x!==a),p=source(b,b.tactics.policies?.[a.id]?.partner)||candidates[0]||a,q=candidates.find(x=>x.id===b.tactics.policies?.[a.id]?.partner2&&x!==p)||candidates.find(x=>x!==p)||a;a.m.pair=[p.id,q.id];a.m.warp=p.id;a.m.weft=q.id;}dispatch(b,start,'setup');dispatch(b,start,'roundStart');return b;
 };
 C.battle=(s,stage,mode='story')=>{const b=Base.battle(s,stage,mode);if(b.error)return b;return C.prepareBattle(b,s,{replaceStats:true});};
 function log(b,text){b.log.push(text);if(b.log.length>100)b.log.shift();}
 function addReport(b,key,id,n){if(n>0)b.report[key][id]=(b.report[key][id]||0)+n;}
 function event(b,actor,kind,label){const h=actor?.side==='ally'?C.hero(actor.id):null;return {actor,kind,label,fx:h?.fx||'enemy',color:h?.color||'#ee9ba9',rarity:h?.rarity,ultimate:kind==='ultimate',impacts:[],combos:[]};}
 function status(u,key,b){return u?.statuses?.find(s=>s.key===key&&s.expires>b.round);}
 function put(u,key,value,b,rounds=2,source=null){if(!u||u.hp<=0)return;if(['reduce','attackDown','poiseBoost'].includes(key)){const old=status(u,key,b);if(old&&old.value>value)return;}u.statuses=u.statuses.filter(s=>s.key!==key);u.statuses.push({key,value,expires:b.round+rounds,source});if(key==='route'||key==='calibrated')u.marked=true;if(key==='sleep')u.sleepSpared=false;}
 function source(b,id){return b.allies.find(a=>a.id===id);}
 function dispatch(b,ev,key,data={}){if(b.suppressPassives||b.dispatchDepth>=3)return;b.dispatchDepth++;try{for(const a of [...living(b)])Skills.passive(context(b,a,ev),key,data);}finally{b.dispatchDepth--;}}
 function statPower(a){return a.atk*(a.skillBonus||1);}
 function ward(b,a,to,amount,ev,{recycled=false,copied=false}={}){if(!to||to.hp<=0)return 0;let adjusted=amount*(1+(status(to,'shieldBoost',b)?.value||0))*(1-(status(a,'shieldPenalty',b)?.value||0));if(a?.id==='petra')adjusted+=statPower(a)*.15*(a.m.bearing||0);let ceiling=to.maxHp*.35;if(a?.id==='helia'&&recycled){const own=to.wards.filter(w=>w.source===a.id).reduce((n,w)=>n+w.value,0);ceiling=Math.min(ceiling,to.shield+Math.max(0,to.maxHp*.12-own));}if(a?.id==='petra'&&ev.kind==='skill')ceiling=to.maxHp*.25;const n=Math.max(0,Math.round(Math.min(adjusted,ceiling-to.shield)));if(!n)return 0;to.wards.push({value:n,initial:n,source:a?.id||null,expires:b.round+2,recycled});to.shield+=n;ev.impacts.push({side:'ally',id:to.id,type:'shield',value:n});if(status(to,'shieldBoost',b))to.statuses=to.statuses.filter(s=>s.key!=='shieldBoost');if(status(a,'shieldPenalty',b))a.statuses=a.statuses.filter(s=>s.key!=='shieldPenalty');if(!copied)dispatch(b,ev,'shield',{actor:a,to,value:n});return n;}
 function heal(b,a,to,amount,ev,{copied=false}={}){if(!to||to.hp<=0)return 0;let power=amount*(1-(status(to,'seal',b)?.value||0))*(1+(status(a,'healOutput',b)?.value||0));const med=status(to,'medicine',b);if(med){power*=1.2;to.statuses=to.statuses.filter(s=>s!==med);}power*=1+(status(to,'healBoost',b)?.value||0);if(status(a,'healOutput',b))a.statuses=a.statuses.filter(s=>s.key!=='healOutput');let n=Math.max(0,Math.min(to.maxHp-to.hp,Math.round(power)));if(a?.id==='eirene'&&a!==to){if(a.m.healRound!==b.round){a.m.healRound=b.round;a.m.healTotal=0;}n=Math.min(n,Math.max(0,statPower(a)*4-(a.m.healTotal||0)));n=Math.floor(n);a.m.healTotal=(a.m.healTotal||0)+n;}to.hp+=n;ev.impacts.push({side:'ally',id:to.id,type:'heal',value:n});if(a)addReport(b,'healing',a.id,n);if(!copied)dispatch(b,ev,'heal',{actor:a,to,value:n,overflow:Math.max(0,Math.round(power)-n)});return n;}
 function cleanse(b,a,to,ev,{dotOnly=false,key=null}={}){if(!to||to.hp<=0)return false;let removed=null;if(to.dots.length&&(!key||key==='burn'))removed=to.dots.shift();else if(!dotOnly){const i=to.statuses.findIndex(s=>['seal','obscure','delay','enemyMark','attackDown'].includes(s.key)&&(!key||key===s.key));if(i>=0)removed=to.statuses.splice(i,1)[0];}if(removed){if(a)addReport(b,'cleanses',a.id,1);dispatch(b,ev,'cleanse',{actor:a,to,removed});ev.combos.push('净化 · '+C.hero(to.id).name);}return removed;}
 function breakPoise(b,a,e,amount,ev){if(!e||e.hp<=0)return 0;let n=amount;if(C.hero(a?.id)?.phase===e.weak)n*=1.25;if(status(e,'cold',b))n*=1.1;if(status(a,'poiseBoost',b))n*=1+status(a,'poiseBoost',b).value;if(b.blessings?.includes('frost'))n*=1.25;if(b.domain?.id==='aurelia'&&a){const domain=b.domain;if(domain.boostRound!==b.round){domain.boostRound=b.round;domain.boosted=[];}if(!domain.boosted.includes(a.id)){domain.boosted.push(a.id);n+=100*domain.power/Math.max(1,living(b).length);}}n=Math.max(0,Math.min(e.poise,Math.round(n)));e.poise-=n;if(a)addReport(b,'poise',a.id,n);
  if(e.poise===0&&e.sturdyUntil<=b.round&&e.exposedUntil<=b.round){e.needsRecovery=true;e.exposedUntil=b.round+1;e.sturdyUntil=b.round+2;e.interrupted=true;b.report.breaks++;ev.combos.push('破韧 · '+e.name);if(e.boss){e.boss.phase='exposed';e.boss.charge=3;e.boss.cycle++;}dispatch(b,ev,'break',{actor:a,target:e});}return n;}
 function removeShield(b,a,e,amount,ev,{direct=false}={}){if(!e||e.hp<=0)return 0;if(!direct&&status(e,'crack',b)){amount*=1+status(e,'crack',b).value;e.statuses=e.statuses.filter(s=>s.key!=='crack');}if(!direct&&status(e,'firstBeat',b))amount*=1+status(e,'firstBeat',b).value;const n=Math.min(e.shield,Math.max(0,Math.round(amount)));e.shield-=n;if(n){ev.impacts.push({side:'enemy',id:e.id,type:'absorb',value:n});dispatch(b,ev,'enemyShield',{actor:a,target:e,value:n,broken:e.shield===0});}return n;}
 function hurtEnemy(b,a,e,amount,ev,{passive=false,poise=0,reaction=false,dotDamage=false}={}){if(!e||e.hp<=0)return 0;let hit=Math.max(0,amount)*(1+(e.exposedUntil>b.round?.25:0));if(!reaction&&b.enemies.indexOf(e)>=2&&foes(b).some(x=>b.enemies.indexOf(x)<2)&&!status(e,'route',b)&&!status(e,'bypass',b)&&!(a?.id==='lynx'&&a.m.opening)&&!(a?.id==='undine'&&a.shield))hit*=.75;if(!reaction&&!dotDamage&&C.hero(a?.id)?.phase===e.resist)hit*=.85;if(b.blessings?.includes('hunt')&&status(e,'route',b))hit*=1.2;if(status(e,'weakHit',b))hit*=1.15;if(a&&status(a,'attackUp',b))hit*=1+status(a,'attackUp',b).value;const absorb=removeShield(b,a,e,hit,ev,{direct:true});hit=Math.round(hit)-absorb;const n=Math.max(0,Math.min(e.hp,hit));e.hp-=n;ev.impacts.push({side:'enemy',id:e.id,type:'damage',value:n});if(a)addReport(b,'damage',a.id,n);else b.report.passive+=n;
  if(n>0){if(status(e,'sleep',b)){dispatch(b,ev,'wake',{actor:a,target:e});e.wakeCount=(e.wakeCount||0)+1;}e.statuses=e.statuses.filter(s=>s.key!=='sleep');dispatch(b,ev,'hit',{actor:a,target:e,value:n,passive,reaction});}if(poise&&e.hp>0){breakPoise(b,a,e,poise,ev);if(status(a,'poiseBoost',b)?.source==='capri')a.statuses=a.statuses.filter(s=>s.key!=='poiseBoost');}if(e.hp<=0)dispatch(b,ev,'enemyDeath',{actor:a,target:e});return n;}
 function hurtAlly(b,e,to,amount,ev,{cost=false,transferred=false}={}){if(!to||to.hp<=0)return 0;let hit=Math.max(0,Math.round(amount));if(cost){const n=Math.min(to.hp-1,hit);to.hp-=n;ev.impacts.push({side:'ally',id:to.id,type:'damage',value:n});dispatch(b,ev,'cost',{to,value:n});return n;}
  const before={to,enemy:e,amount:hit,transferred,aoe:!!ev.sweep,dot:!e};dispatch(b,ev,'beforeHit',before);hit=before.amount;
  const protect=!transferred&&!(ev.sweep&&['bran','garde'].includes(status(to,'protect',b)?.source))&&status(to,'protect',b),protector=protect&&source(b,protect.source);if(protector&&protector.hp>0&&protector!==to){const n=Math.round(hit*Math.min(.4,protect.value));to.statuses=to.statuses.filter(s=>s!==protect);hurtAlly(b,e,protector,n,ev,{transferred:true});hit-=n;b.report.protection+=n;addReport(b,'guarding',protector.id,n);if(protector.id==='orion'&&e)mark(b,protector,e,'霆',ev);}
  const delay=status(to,'delayDamage',b);if(delay){const n=Math.min(hit*.5,delay.value);to.debts.push({amount:Math.round(n),due:b.round+1});hit-=n;to.statuses=to.statuses.filter(s=>s!==delay);}
  const reduction=Math.min(.6,(to.mitigation||0)+(to.guard?.5:0)+(status(to,'reduce',b)?.value||0)+(b.domain?.id==='aurora'?(to.shield?b.domain.power:.1):0));hit=Math.round(hit*(1-reduction));if(status(to,'reduce',b))to.statuses=to.statuses.filter(s=>s.key!=='reduce');
  const shieldBefore=to.shield;for(const w of [...to.wards]){if(hit<=0)break;const n=Math.min(w.value,hit);w.value-=n;hit-=n;to.shield-=n;if(n){ev.impacts.push({side:'ally',id:to.id,type:'absorb',value:n});b.report.protection+=n;if(w.source)addReport(b,'guarding',w.source,n);}if(w.value===0){to.wards=to.wards.filter(x=>x!==w);if(!w.recycled)dispatch(b,ev,'shieldBreak',{to,owner:source(b,w.source),original:w.initial||n,enemy:e});}}
  if(hit>=to.hp&&to.m.lamp&&!to.m.lampSpent){hit=to.hp-1;to.m.lampSpent=true;to.m.lamp=false;ev.combos.push('归灯 · '+C.hero(to.id).name);dispatch(b,ev,'saved',{to});}
  const n=Math.min(to.hp,Math.max(0,hit));to.hp-=n;ev.impacts.push({side:'ally',id:to.id,type:'damage',value:n});dispatch(b,ev,'hurt',{to,enemy:e,value:n,transferred,shieldBefore});if(to.hp<=0){dispatch(b,ev,'death',{to});if(b.blessings?.includes('resolve')&&!to.revived)revive(b,null,to,.15,ev);}return n;}
 function revive(b,a,to,fraction,ev){if(!to||to.hp>0||to.revived)return false;to.revived=true;to.hp=Math.max(1,Math.round(to.maxHp*fraction));ev.impacts.push({side:'ally',id:to.id,type:'heal',value:to.hp});if(a)addReport(b,'healing',a.id,to.hp);ev.combos.push('复苏 · '+C.hero(to.id).name);return true;}
 function gainEnergy(b,a,n=1){const amount=Math.min(n,3-a.energy,2-b.extraEnergy,a.m.energyRound===b.round?0:1);if(amount>0){a.energy+=amount;b.extraEnergy+=amount;a.m.energyRound=b.round;}return amount;}
 function gainAP(b,n){const amount=Math.max(0,Math.min(n,2-b.extraAP,7-b.ap));b.ap+=amount;b.extraAP+=amount;return amount;}
 function mark(b,a,e,p,ev){if(!e||e.hp<=0)return;const old=e.marks.find(m=>m.phase!==p);if(old){if(ev.reactionDone)return;e.marks=e.marks.filter(m=>m!==old);e.marks=e.marks.filter(m=>m.expires>e.turns);ev.reactionDone=true;react(b,a,e,old,p,ev);}else{e.marks.push({phase:p,source:a.id,power:statPower(a),expires:e.turns+2});if(e.marks.length>2)e.marks.shift();}}
 function react(b,a,e,old,p,ev){const r=Data.reactions.find(r=>r.pair.includes(old.phase)&&r.pair.includes(p)),B=((source(b,old.source)?.atk||old.power)+a.atk)/2,pair=r.pair.join(''),low=[...living(b)].sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0],other=foes(b).find(x=>x!==e);b.report.combos++;b.reactionSerial++;addReport(b,'assists',old.source,1);ev.combos.push(r.name);const damage=n=>hurtEnemy(b,a,e,B*n,ev,{reaction:true}),sh=n=>ward(b,a,low,B*n,ev),hp=n=>heal(b,a,low,B*n,ev);
  switch(pair){case '焰潮':damage(.8);sh(.4);break;case '焰霆':damage(1);if(e.shield)removeShield(b,a,e,B*.8,ev);else breakPoise(b,a,e,20,ev);break;case '焰岚':damage(.6);if(other){other.marks.push({phase:'焰',source:old.phase==='焰'?old.source:a.id,power:B,expires:other.turns+2});other.marks=other.marks.slice(-2);}else damage(.3);break;case '焰辉':damage(.5);hp(.6);break;case '焰幽':dot(e,'eclipse',a,B*.55,b,2);break;case '潮霆':damage(.8);if(other)hurtEnemy(b,a,other,B*.4,ev,{reaction:true});else breakPoise(b,a,e,15,ev);break;case '潮岚':damage(.6);breakPoise(b,a,e,status(e,'cold',b)?30:20,ev);break;case '潮辉':hp(.8);if(!cleanse(b,a,low,ev,{dotOnly:true}))hp(.2);break;case '潮幽':if(e.boss)breakPoise(b,a,e,25,ev);else if((e.wakeCount||0)<2)put(e,'sleep',1,b,2,a.id);else breakPoise(b,a,e,15,ev);break;case '霆岚':damage(.8);{const next=living(b).find(x=>!x.acted&&x!==a);if(next)put(next,'nextAttackPoise',15,b,1,a.id);}break;case '霆辉':breakPoise(b,a,e,20,ev);sh(.6);break;case '霆幽':damage(.7);if(!dispel(e))breakPoise(b,a,e,15,ev);break;case '岚辉':sh(.7);if(!cleanse(b,a,low,ev,{key:'delay'}))sh(.2);break;case '岚幽':damage(.6);put(e,'nextAttackDown',.15,b,2,a.id);break;case '辉幽':if(!cleanse(b,a,low,ev))hp(.4);put(low,'reduce',.2,b,1,a.id);break;}
  e.lastReactionRound=b.round;e.lastReactionSerial=b.actionSerial;if(r.pair.includes('焰'))e.consumedFire=true;b.lastReaction={name:r.name,pair:r.pair,B,source:a.id};dispatch(b,ev,'reaction',{actor:a,target:e,donor:source(b,old.source),pair:r.pair,name:r.name});
  if(b.domain?.id==='astra'&&b.domain.lastRound!==b.round){b.domain.lastRound=b.round;b.suppressPassives=true;try{echoReaction(b,source(b,b.domain.source),e,pair,B*b.domain.power,ev,true);}finally{b.suppressPassives=false;}}
 }
 function echoReaction(b,a,e,pair,B,ev,includeDamage){
  if(!a||!e)return;const low=[...living(b)].sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0],other=foes(b).find(x=>x!==e),damage={焰潮:.8,焰霆:1,焰岚:other?.6:.9,焰辉:.5,焰幽:1.1,潮霆:.8,潮岚:.6,霆岚:.8,霆幽:.7,岚幽:.6}[pair]||0;
  if(includeDamage&&damage)hurtEnemy(b,a,e,B*damage,ev,{reaction:true,passive:true});
  switch(pair){
   case '焰潮':ward(b,a,low,B*.4,ev,{copied:true});break;
   case '焰霆':if(e.shield)removeShield(b,a,e,B*.8,ev);else breakPoise(b,a,e,includeDamage?10:20,ev);break;
   case '焰辉':heal(b,a,low,B*.6,ev,{copied:true});break;
   case '潮霆':if(other&&includeDamage)hurtEnemy(b,a,other,B*.4,ev,{reaction:true,passive:true});else if(!other)breakPoise(b,a,e,includeDamage?8:15,ev);break;
   case '潮岚':breakPoise(b,a,e,includeDamage?10:20,ev);break;
   case '潮辉':heal(b,a,low,B*.8,ev,{copied:true});if(!cleanse(b,a,low,ev,{dotOnly:true}))heal(b,a,low,B*.2,ev,{copied:true});break;
   case '潮幽':if(e.boss)breakPoise(b,a,e,includeDamage?12:25,ev);else put(e,'sleep',1,b,2,a.id);break;
   case '霆岚':{const next=living(b).find(x=>!x.acted&&x!==a);if(next)put(next,'nextAttackPoise',includeDamage?8:15,b,1,a.id);}break;
   case '霆辉':breakPoise(b,a,e,includeDamage?10:20,ev);ward(b,a,low,B*.6,ev,{copied:true});break;
   case '霆幽':if(!dispel(e))breakPoise(b,a,e,includeDamage?8:15,ev);break;
   case '岚辉':ward(b,a,low,B*.7,ev,{copied:true});if(!cleanse(b,a,low,ev,{key:'delay'}))ward(b,a,low,B*.2,ev,{copied:true});break;
   case '岚幽':put(e,'nextAttackDown',includeDamage?.075:.15,b,1,a.id);break;
   case '辉幽':if(!cleanse(b,a,low,ev))heal(b,a,low,B*.4,ev,{copied:true});put(low,'reduce',includeDamage?.1:.2,b,1,a.id);break;
  }
 }
 function dot(target,key,a,power,b,turns=2){if(!target||target.hp<=0)return;target.dots=target.dots.filter(d=>!((key==='eclipse'||d.source===a.id)&&d.key===key));target.dots.push({key,source:a.id,power:Math.round(power),turns,extended:false});if(target.dots.length>3)target.dots.sort((x,y)=>y.power*y.turns-x.power*x.turns).pop();target.burn=target.dots.length;}
 function dispel(e){if(!e)return false;const i=e.statuses.findIndex(s=>['attackUp','fortify','obscure','regen'].includes(s.key));return i>=0?e.statuses.splice(i,1)[0]:false;}
 function context(b,a,ev,target){const h=C.hero(a.id),e=target||foes(b)[0],p=statPower(a),all=()=>living(b),lowest=[...all()].sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0],low=()=>lowest?.hp>0?lowest:all()[0],partner=()=>source(b,b.tactics.policies?.[a.id]?.partner)||all().find(x=>x!==a)||a;
  return {b,a,e,h,p,ev,all,foes:()=>foes(b),low,partner,phaseOf:id=>C.hero(id)?.phase,find:id=>source(b,id),status:(u,k)=>status(u,k,b),has:(u,k)=>!!status(u,k,b),get:k=>a.m[k]||0,set:(k,v)=>a.m[k]=v,inc:(k,n=1,max=3)=>a.m[k]=Math.max(0,Math.min(max,(a.m[k]||0)+n)),take:k=>{const n=a.m[k]||0;a.m[k]=0;return n;},once:k=>{const key='once:'+k;if(a.m[key]===b.round)return false;a.m[key]=b.round;return true;},
   hit:(to=e,m=1,poise=10,passive=false)=>hurtEnemy(b,a,to,p*m,ev,{poise,passive}),rawHit:(to,n)=>hurtEnemy(b,a,to,n,ev,{passive:true}),aoe:(m=1)=>foes(b).forEach(t=>hurtEnemy(b,a,t,p*m*.45,ev,{poise:10})),heal:(to=low(),m=1,copied=false)=>heal(b,a,to,p*m,ev,{copied}),rawHeal:(to,n,copied=false)=>heal(b,a,to,n,ev,{copied}),shield:(to=low(),m=.7,recycled=false)=>ward(b,a,to,p*m,ev,{recycled}),rawShield:(to,n,recycled=false,copied=false)=>ward(b,a,to,n,ev,{recycled,copied}),poise:(to=e,n=20)=>breakPoise(b,a,to,n,ev),shred:(to=e,m=1)=>removeShield(b,a,to,p*m,ev),clean:(to=low(),dotOnly=false,key=null)=>cleanse(b,a,to,ev,{dotOnly,key}),buff:(to,key,value,rounds=2)=>put(to,key,value,b,rounds,a.id),dot:(to=e,m=.55,turns=2,key=a.id)=>dot(to,key,a,p*m,b,turns),hot:(to=low(),m=.5)=>put(to,'hot:'+a.id,p*m,b,2,a.id),cost:f=>hurtAlly(b,null,a,a.hp*f,ev,{cost:true}),protect:(to=partner(),value=.3)=>put(to,'protect',value,b,1,a.id),mark:(to=e,phase=h.phase)=>mark(b,a,to,phase,ev),markAs:(to,from)=>mark(b,from,to,C.hero(from.id).phase,ev),energy:to=>gainEnergy(b,to),ap:n=>gainAP(b,n),dispel:(to=e)=>{const removed=dispel(to);if(removed)dispatch(b,ev,'removedBuff',{actor:a,to,removed});return removed;},removeBuff:to=>{const i=to.statuses.findIndex(s=>['attackUp','healBoost','poiseBoost'].includes(s.key));if(i<0)return false;const removed=to.statuses.splice(i,1)[0];dispatch(b,ev,'removedBuff',{actor:a,to,removed});return removed;},revive:(to,f=.2)=>revive(b,a,to,f,ev),
   cold:(to=e)=>{if(to.boss){if(to.coldRound!==b.round){to.coldRound=b.round;breakPoise(b,a,to,10,ev);}}else put(to,'cold',1,b,2,a.id);if(status(to,'coordinate',b)){breakPoise(b,a,to,10,ev);to.statuses=to.statuses.filter(s=>s.key!=='coordinate');}dispatch(b,ev,'cold',{actor:a,target:to});},route:(to=e)=>put(to,'route',1,b,2,a.id),front:()=>all().slice(0,2),domain:(id,power)=>{if(!b.domain){b.domain={id,source:a.id,power,expires:b.round+2,lastRound:0};b.field=2;}},shift:to=>{if(to&&!to.acted){b.priority=to.id;}},consumeShields:(units,f=.25,owner=null)=>{let sum=0;for(const u of units)for(const w of u.wards){if(owner&&w.source!==owner)continue;const n=Math.floor(w.value*f);w.value-=n;u.shield-=n;sum+=n;}return sum;},
   copyReaction:()=>{if(!b.lastReaction)return;const r=b.lastReaction;b.suppressPassives=true;try{hurtEnemy(b,a,e,r.B*.8,ev,{reaction:true,passive:true});echoReaction(b,a,e,r.pair.join(''),r.B,ev,false);}finally{b.suppressPassives=false;}},notes:t=>ev.combos.push(t)
  };}
 function outcome(b,ev){if(foes(b).length&&living(b).length)return false;if(!foes(b).length){for(const a of living(b)){const n=a.debts.reduce((s,d)=>s+d.amount,0);a.debts=[];if(n){a.hp=Math.max(0,a.hp-n);ev.impacts.push({side:'ally',id:a.id,type:'damage',value:n});}}}b.phase=living(b).length?'win':'lose';log(b,b.phase==='win'?'远征胜利，星契仍在回响。':'旅团撤回营地。调整星相与保护顺序后再试。');return true;}
 function skillCost(b,a){return Math.max(0,C.hero(a.id).cost-(status(a,'discount',b)?.value||0)-(a.id==='flint'&&!a.m.firstSkill?1:0));}
 C.action=(b,id,type,targetId=0)=>{if(b.phase!=='player')return {error:'当前无法行动。'};const a=source(b,id),h=C.hero(id),e=b.enemies.find(e=>e.id===targetId);if(!a||a.hp<=0||a.acted)return {error:'角色当前无法行动。'};if(!['attack','guard','skill','ultimate'].includes(type))return {error:'未知行动。'};if(type!=='guard'&&(!e||e.hp<=0))return {error:'目标已退场。'};const cost=type==='skill'?skillCost(b,a):0;if(cost>b.ap)return {error:'行动点不足。'};if(type==='skill'&&a.readyRound>b.round)return {error:'主动技冷却中。'};const ev=event(b,{side:'ally',id},type,type==='attack'?'普通攻击':type==='guard'?'防御':type==='ultimate'?h.ultimateName:h.skill),ctx=context(b,a,ev,e);if(type==='skill'&&id==='severin'&&!Skills.useful(ctx))return {error:'本轮预支预算不足，请等待下一轮。'};if(type==='ultimate'&&(a.energy<3||!Skills.ready(ctx)))return {error:'终式条件尚未满足。'};
  a.acted=true;b.actionSerial++;b.ap-=cost;b.priority=null;ev.actionSerial=b.actionSerial;ev.skillKey=type;a.m.lastType=type;
  for(const d of [...a.dots]){hurtAlly(b,null,a,d.power,ev);d.turns--;}a.dots=a.dots.filter(d=>d.turns>0);if(a.hp<=0){outcome(b,ev);return {ok:true,event:ev};}
  if(type==='guard'){a.guard=true;ev.impacts.push({side:'ally',id,type:'guard',value:0});}
  else if(type==='attack'){dispatch(b,ev,'beforeAttack',{actor:a,target:e});if(!a.m.silentAttack){hurtEnemy(b,a,e,a.atk,ev,{poise:5});}else{breakPoise(b,a,e,5,ev);a.m.silentAttack=false;}if(a.m.nextPhase){mark(b,a,e,a.m.nextPhase,ev);delete a.m.nextPhase;}if(a.m.mechanical){b.suppressPassives=true;try{hurtEnemy(b,a,e,a.atk*.4,ev,{passive:true});}finally{b.suppressPassives=false;}mark(b,a,e,'霆',ev);a.m.mechanical=false;}if(status(a,'prepare',b)){gainEnergy(b,a);a.statuses=a.statuses.filter(s=>s.key!=='prepare');}if(status(a,'nextAttackPoise',b)){breakPoise(b,a,e,status(a,'nextAttackPoise',b).value,ev);a.statuses=a.statuses.filter(s=>s.key!=='nextAttackPoise');}if(status(e,'weakPoise',b)){breakPoise(b,a,e,10,ev);e.statuses=e.statuses.filter(s=>s.key!=='weakPoise');}dispatch(b,ev,'attack',{actor:a,target:e});if(a.id==='lynx')a.m.opening=false;}
  else{if(type==='ultimate'){a.energy=0;a.m.ultUses=(a.m.ultUses||0)+1;Skills.run(ctx,'ultimate');}else{a.readyRound=b.round+2;a.m.firstSkill=true;a.statuses=a.statuses.filter(s=>s.key!=='discount');Skills.run(ctx,'active');if(!ev.skipMark)mark(b,a,ctx.e,ev.phaseOverride||h.phase,ev);dispatch(b,ev,'cooldown',{actor:a});}}
  dispatch(b,ev,'action',{actor:a,target:e,type});if(type!=='ultimate')a.energy=Math.min(3,a.energy+1);b.lastActor=id;b.lastTarget=e?.id;for(const txt of ev.combos)log(b,txt);log(b,`${h.name} · ${ev.label}${ev.combos.length?' → '+ev.combos.join(' / '):''}`);outcome(b,ev);return {ok:true,event:ev};};
 function round(b){const ev=event(b,null,'round',`第 ${b.round+1} 回合`);dispatch(b,ev,'roundEnd');for(const a of living(b)){for(const s of [...a.statuses])if(s.key.startsWith('hot:'))heal(b,source(b,s.source),a,s.value,ev);const expired=a.wards.filter(w=>w.expires<=b.round+1);a.wards=a.wards.filter(w=>w.expires>b.round+1);for(const w of expired){a.shield-=w.value;dispatch(b,ev,'shieldExpire',{to:a,owner:source(b,w.source),value:w.value,recycled:w.recycled});}}
  b.round++;b.ap=Math.max(0,Math.min(7,5+Math.min(b.ap,2)-b.actionDebt+(b.blessings?.includes('pulse')?1:0)));b.actionDebt=0;b.extraAP=b.blessings?.includes('pulse')?1:0;b.extraEnergy=0;b.phase='player';b.enemyQueue=null;b.enemyCursor=-1;
  if(b.domain?.expires<=b.round)b.domain=null;b.field=b.domain?b.domain.expires-b.round:0;
  for(const a of b.allies){const delayed=status(a,'delayedHeal',b);if(delayed)heal(b,source(b,delayed.source),a,delayed.value,ev,{copied:true});if(a.m.firstNext){b.priority=a.id;a.m.firstNext=false;}a.acted=false;a.guard=false;a.statuses=a.statuses.filter(s=>s.expires>b.round);for(const d of a.debts.filter(d=>d.due<=b.round)){const paid=Math.min(a.hp,d.amount);a.hp=Math.max(0,a.hp-d.amount);dispatch(b,ev,'cost',{to:a,value:paid});ev.impacts.push({side:'ally',id:a.id,type:'damage',value:d.amount});}a.debts=a.debts.filter(d=>d.due>b.round);if(b.blessings?.includes('spring')&&a.hp>0)heal(b,null,a,a.maxHp*.08,ev);}
  for(const e of foes(b)){e.statuses=e.statuses.filter(s=>s.expires>b.round);e.marked=!!status(e,'route',b);if(e.exposedUntil<=b.round&&e.needsRecovery&&!status(e,'noRecover',b)){e.poise=e.maxPoise;e.needsRecovery=false;if(e.boss)e.boss.phase='charge';}e.interrupted=false;}
  dispatch(b,ev,'roundStart');if(b.round>60){b.phase='lose';log(b,'日蚀加深，旅团撤回。');}else outcome(b,ev);return {ok:true,event:ev};}
 C.enemyStep=b=>{if(['win','lose'].includes(b.phase))return {done:true};if(b.phase==='player'){b.phase='enemy';b.enemyQueue=foes(b).map(e=>e.id);b.enemyCursor=0;}if(!b.enemyQueue)b.enemyQueue=foes(b).map(e=>e.id);
  const id=b.enemyQueue[b.enemyCursor++];if(id===undefined)return round(b);const e=b.enemies.find(e=>e.id===id);if(!e||e.hp<=0)return {ok:true,event:event(b,null,'enemy','敌方已退场')};const ev=event(b,{side:'enemy',id},'enemy','敌方行动');
  if(e.dotRound!==b.round){e.dotRound=b.round;for(const d of [...e.dots]){const before=e.hp+e.shield;hurtEnemy(b,source(b,d.source),e,d.power*(b.blessings?.includes('ember')?1.4:1),ev,{passive:true,dotDamage:true,reaction:d.key==='eclipse'});d.turns--;if(e.hp+e.shield<before)dispatch(b,ev,'dot',{actor:source(b,d.source),target:e,dot:d});if(e.hp<=0)break;}e.dots=e.dots.filter(d=>d.turns>0);e.burn=e.dots.length;}if(outcome(b,ev)||e.hp<=0)return {ok:true,event:ev};
  const delayStatuses=e.statuses.filter(s=>['cold','sleep'].includes(s.key)&&s.expires>b.round),delayed=!e.boss&&delayStatuses.some(s=>!s.delayUsed);if(delayed&&e.delayedRound!==b.round){delayStatuses.forEach(s=>s.delayUsed=true);e.delayedRound=b.round;b.enemyQueue.push(e.id);ev.label='寒缚 · 行动延后';return {ok:true,event:ev};}
  e.turns++;e.marks=e.marks.filter(m=>m.expires>e.turns);if(e.deferredHeal){e.hp=Math.min(e.maxHp,e.hp+e.deferredHeal);e.deferredHeal=0;}if(e.interrupted){e.interrupted=false;ev.label='破韧 · 蓄力被打断';return {ok:true,event:ev};}
  if(outcome(b,ev))return {ok:true,event:ev};if(e.finalAct){const act=e.hp/e.maxHp>.66?1:e.hp/e.maxHp>.33?2:3;if(act!==e.finalAct){e.finalAct=act;e.profile=act===2?'extract':'charge';e.shield=0;ev.combos.push(act===2?'终章第二幕 · 名录抽取':'终章第三幕 · 终焉蓄力');}}const alive=living(b),front=alive.slice(0,2),strong=e.boss?--e.boss.charge<=0:e.profile==='charge'&&(e.charge=(e.charge??3)-1)<=0,sweep=strong||b.round%3===0,taunt=status(e,'taunt',b),target=(taunt&&source(b,taunt.source)?.hp>0?source(b,taunt.source):front[(b.round+e.id)%front.length]),targets=sweep?alive:[target];ev.sweep=sweep;ev.label=strong?'蚀心重击':sweep?'暗潮横扫':'暗影突袭';
  if(e.profile==='healer'&&b.round%3===2){const healTarget=foes(b).sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0],n=Math.min(healTarget.maxHp-healTarget.hp,Math.round(e.atk*1.5));const sealed=Math.round(n*(1-(status(healTarget,'seal',b)?.value||0))),delayed=Math.round(sealed*(status(healTarget,'deferHeal',b)?.value||0));healTarget.deferredHeal=(healTarget.deferredHeal||0)+delayed;healTarget.hp+=sealed-delayed;ev.impacts.push({side:'enemy',id:healTarget.id,type:'heal',value:sealed-delayed});dispatch(b,ev,'enemyHeal',{target:healTarget,value:sealed-delayed});ev.label='敌方回生';}
  else if(e.profile==='buff'&&b.round%3===1){put(e,'attackUp',.2*(1-(status(e,'buffDamp',b)?.value||0)),b,2);ev.label='蓄势强化';dispatch(b,ev,'enemyBuff',{target:e,key:'attackUp'});}
  else{for(const a of targets){const hit=e.atk*(strong?1.6:sweep?.75:1)*(1+(status(e,'attackUp',b)?.value||0))*(1-Math.max(status(e,'attackDown',b)?.value||0,status(e,'nextAttackDown',b)?.value||0));hurtAlly(b,e,a,hit,ev);if(a.hp>0&&['burn','extract'].includes(e.profile))dot(a,'enemy:'+e.id,{id:'enemy'},e.atk*.2,b,2);if(a.hp>0&&e.profile==='seal'&&!status(a,'sealResist',b)&&!status(a,'statusResist',b)){if(status(a,'reflectStatus',b)){a.statuses=a.statuses.filter(s=>s.key!=='reflectStatus');put(e,'seal',.3,b,2,a.id);ev.combos.push('湖镜 · 反射禁疗');}else{put(a,'seal',.3,b,2);dispatch(b,ev,'status',{to:a,key:'seal'});}}}}
  e.statuses=e.statuses.filter(s=>s.key!=='nextAttackDown');if(e.profile==='shield'&&b.round%3===0){e.shield=Math.round(e.maxHp*.12);dispatch(b,ev,'enemyShieldGain',{target:e});}if(e.profile==='summon'&&b.round%4===0){const a=living(b).sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0];hurtAlly(b,e,a,e.atk*.45,ev);ev.combos.push('残响协击');}
  if(strong){if(e.boss){e.boss.charge=3;e.boss.phase='charge';e.boss.cycle++;}else e.charge=3;}dispatch(b,ev,'enemyAction',{enemy:e,target,targets,harmful:ev.impacts.some(x=>x.side==='ally'&&['damage','absorb'].includes(x.type))});log(b,`${e.name} · ${ev.label}`);outcome(b,ev);return {ok:true,event:ev};};
 C.autoChoice=b=>{const available=living(b).filter(a=>!a.acted),enemies=foes(b);if(!available.length||!enemies.length)return null;let a=available.find(a=>a.id===b.priority)||available[0];const wounded=living(b).some(x=>x.hp/x.maxHp<(b.tactics.tactic==='sustain'?.85:b.tactics.healAt||.68));if(wounded){const rescue=available.find(x=>healers.includes(C.hero(x.id).kit.role)&&x.readyRound<=b.round&&b.ap>=skillCost(b,x));if(rescue)a=rescue;}
  const h=C.hero(a.id),policy=b.tactics.policies?.[a.id]?.mode||'auto';let e=enemies.find(e=>e.boss?.charge===1)||enemies.find(e=>e.profile==='healer')||enemies.find(e=>e.id===b.lastTarget)||enemies[0];const matching=enemies.find(e=>e.marks.some(m=>m.phase!==h.phase));if(matching&&!enemies.some(e=>e.boss?.charge===1))e=matching;
  const targetPolicy=b.tactics.policies?.[a.id]?.target;if(targetPolicy==='boss')e=enemies.find(x=>x.boss)||e;else if(targetPolicy==='healer')e=enemies.find(x=>x.profile==='healer')||e;else if(targetPolicy==='back')e=enemies.find(x=>b.enemies.indexOf(x)>=2)||e;if(h.id==='quill'||h.id==='ignis')e=enemies.find(x=>b.enemies.indexOf(x)>=2)||e;if(h.id==='rhoda')e=enemies.find(x=>!status(x,'route',b))||e;const ctx=context(b,a,event(b,{side:'ally',id:a.id},'preview',''),e),canUlt=a.energy>=3&&Skills.ready(ctx);let type='attack';const wait=policy==='wait'&&((h.id==='mira'&&a.m.dim)||!e.marks.some(m=>m.phase!==h.phase));if(canUlt&&!wait&&policy!=='save'&&policy!=='attack'&&!(b.tactics.tactic==='burst'&&enemies.some(e=>e.boss)&&!enemies.some(e=>e.exposedUntil>b.round)&&!healers.includes(h.kit.role)))type='ultimate';else if(!wait&&a.readyRound<=b.round&&b.ap>=skillCost(b,a)&&policy!=='attack'&&Skills.useful(ctx))type='skill';if(policy==='support'&&type==='attack'&&guards.includes(h.kit.role))type='guard';return {actorId:a.id,type,targetId:e.id};};
 C.autoStep=b=>{if(['win','lose'].includes(b.phase))return {done:true};if(b.phase==='enemy')return C.enemyStep(b);const c=C.autoChoice(b);return c?C.action(b,c.actorId,c.type,c.targetId):C.enemyStep(b);};C.enemyTurn=b=>{let r;do{r=C.enemyStep(b);}while(b.phase==='enemy');return r;};
 C.enemyIntent=(b,e)=>e.hp<=0?'已退场':`${e.marks.map(m=>m.phase).join('·')||'无星痕'} · 弱${e.weak}/抗${e.resist} · 韧性 ${e.poise}/${e.maxPoise} · ${e.exposedUntil>b.round?'破韧易伤':e.boss?(e.finalAct?'终章第'+e.finalAct+'幕 · ':'')+'蓄力 '+e.boss.charge:e.profile==='healer'?'回生者':e.profile==='burn'?'附加灼伤':'准备进攻'}${e.shield?' · 盾 '+e.shield:''}`;
 C.recommendTeam=s=>{const pool=heroes.filter(h=>s.owned[h.id]),score=h=>(s.levels[h.id]||1)*2+(s.stars?.[h.id]||0)*3;pool.sort((a,b)=>score(b)-score(a));const chosen=[],add=h=>{if(h&&!chosen.includes(h))chosen.push(h);};add(pool.find(h=>guards.includes(h.kit.role)));add(pool.find(h=>['调度','标记'].includes(h.kit.role)));add(pool.find(h=>!guards.includes(h.kit.role)&&!healers.includes(h.kit.role)&&!support.includes(h.kit.role)));add(pool.find(h=>healers.includes(h.kit.role)));for(const h of pool)if(chosen.length<5&&!chosen.some(x=>x.phase===h.phase))add(h);for(const h of pool)if(chosen.length<5)add(h);return [...chosen.filter(h=>!healers.includes(h.kit.role)),...chosen.filter(h=>healers.includes(h.kit.role))].map(h=>h.id);};
 C.actionPreview=b=>{const debt=b.allies.reduce((n,a)=>n+a.debts.reduce((sum,d)=>sum+d.amount,0),0),tail=(b.actionDebt?' · 下轮偿还 '+b.actionDebt+' AP':'')+(debt?' · 待结时债 '+Math.round(debt):'');if(b.phase!=='player')return '观察敌方行动与蓄力'+tail;const c=C.autoChoice(b);if(!c)return '本轮行动完成'+tail;const h=C.hero(c.actorId),a=source(b,c.actorId),e=b.enemies.find(x=>x.id===c.targetId);let phase=h.phase;if(h.id==='elysium')phase=C.hero(b.tactics.policies?.elysium?.partner)?.phase||'辉';const old=e.marks.find(m=>m.phase!==phase),reaction=c.type==='skill'&&!['pero','orion'].includes(h.id)&&old?C.reactionPreview(old.phase,phase):null;return '下一行动：'+h.name+' · '+({attack:'普攻',guard:'防御',skill:h.skill,ultimate:h.ultimateName}[c.type])+' → '+e.name+(reaction?' · 预计 '+reaction:'')+(c.type==='skill'?' · '+skillCost(b,a)+' AP':'')+tail;};
 C.battleHint=a=>{if(a.id==='mira')return a.m.dim?'暗态 · 自盾 / 破盾':'明态 · 削韧 / 重击';if(a.id==='deluge')return a.m.release?'放水 · 削韧':'蓄水 · 护盾';const names={needle:'针脚',butterfly:'月蝶',anchor:'星锚',shards:'碎盾',herbs:'药草',dragon:'龙心',song:'潮音',oath:'誓雷',blood:'月血',seal:'封印',ember:'余火',crates:'补给',molten:'熔金',water:'储水',patrol:'巡光',threads:'影线',weave:'织纹',pressure:'锻压',sync:'同步',stock:'储备',stars:'余星',coral:'珊瑚',bearing:'承重',medicine:'药剂',cloth:'织光',emblems:'纹章',cuts:'断钟印',freedom:'解约光'};if(a.id==='elysium')return '颜色 '+(a.m.colors?.length||0)+'/3';if(a.id==='anamnesis')return '见证 '+(a.m.witnesses?.length||0)+'/3';return Object.entries(names).filter(([key])=>a.m[key]>0).slice(0,2).map(([key,name])=>name+' '+Math.round(a.m[key])).join(' · ');};C.skillContext=context;C.reactionPreview=(a,b)=>Data.reactions.find(r=>a!==b&&r.pair.includes(a)&&r.pair.includes(b))?.name||'同相储备';return C;
}
const api={install};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.EclipseCovenant=api;
})(typeof globalThis!=='undefined'?globalThis:this);
