(function(root){'use strict';
const A={},U={};const define=(id,active,ultimate)=>{A[id]=active;U[id]=ultimate;};
const allHeal=(c,n)=>c.all().forEach(a=>c.heal(a,n)),allShield=(c,n)=>c.all().forEach(a=>c.shield(a,n));
const isMine=(c,d)=>d.actor?.id===c.a.id,lowPair=c=>[...c.all()].sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp).slice(0,2),count=(c,key,n=1,max=3)=>c.inc(key,n,max);
function field(c,id,p=1){c.domain(id,p);}
function spend(c,key,base=1){return base+c.take(key)*.35;}
function reduce(c,a,n=.2){c.buff(a,'reduce',n,1);}
function reviveOne(c){const a=c.b.allies.find(a=>a.hp<=0&&!a.revived);return a&&c.revive(a);}
function remainingDots(c,e=c.e){return e.dots.filter(d=>d.source===c.a.id);}
function detonate(c,consume=true,m=1){let n=0;for(const d of remainingDots(c)){n+=d.power*(consume?d.turns:1)*m;}c.rawHit(c.e,Math.min(n,c.p*3));if(consume)c.e.dots=c.e.dots.filter(d=>d.source!==c.a.id);}
function attackAllMarked(c,m=1.6){const targets=c.foes().filter(e=>c.has(e,'route'));if(!targets.length)targets.push(c.e);targets.forEach(e=>c.hit(e,m,15));}
function recovery(c){const n=c.take('stock');c.rawHeal(c.low(),n);}
function rawShieldSplit(c,n,recycled=false){const alive=c.all();alive.forEach(a=>c.rawShield(a,n/alive.length,recycled));}
function fishPair(c){return (c.a.m.pair||[c.partner().id,c.a.id]).map(c.find).filter(a=>a?.hp>0).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp);}
// Every entry supplies its own active and ultimate; all are invoked through the same event pipeline.
define('milo',c=>{c.heal();const d=c.clean(c.low(),true);if(d)c.rawShield(c.low(),Math.min(c.p*.8,(d.power||0)*(d.turns||1)));},c=>{allHeal(c,.85);c.set('extendName',c.b.round);if(c.b.lastReaction?.name!=='归名'&&!c.low().m.lampSpent)c.low().m.lamp=true;});
define('lark',c=>{c.hit(c.e,.6);c.route();c.buff(c.e,'bypass',1,1);},c=>{const p=!c.partner().acted?c.partner():c.all().find(a=>!a.acted);c.shift(p);if(p)c.buff(p,'discount',1,1);});
define('scarlet',c=>{c.hit(c.e,1.2);c.shred(c.e,.8);},c=>{const n=c.take('needle');c.hit(c.e,1.2+n*.6,20);c.shield(c.low(),n*.4);});
define('selene',c=>{const a=c.all().filter(x=>c.b.allies.indexOf(x)>=2).sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0]||c.low();c.shield(a,1.2);c.protect(a,.4);},c=>{const n=c.take('butterfly');allShield(c,.7+n*.2);c.heal(c.low(),n*.4);c.mark(c.e,'幽');});
define('astra',c=>{c.e=c.foes().sort((a,b)=>b.poise-a.poise)[0];c.hit(c.e,1.2,25);c.protect(c.low(),.2);},c=>field(c,'astra',.5+c.take('anchor')*.1));
define('bran',c=>{c.shield(c.partner(),.7);c.protect(c.partner(),.35);},c=>{const n=c.take('shards');c.all().forEach(a=>reduce(c,a,.1*n));});
define('flora',c=>{const a=c.low();if(c.has(a,'hot:flora'))c.clean(a);else c.hot(a,.65);},c=>{const n=c.take('herbs');allHeal(c,.7+n*.35);lowPair(c).slice(0,n).forEach(a=>c.clean(a));c.mark(c.e,'潮');});
define('nix',c=>{c.hit(c.e,1,20);c.cold();},c=>{c.poise(c.e,40);c.cold();});
define('vesper',c=>{const n=c.hit(c.e,1.2);c.rawHeal(c.a,n*.5);c.buff(c.e,'seal',.2,2);},c=>{const n=c.take('feast'),dealt=c.rawHit(c.e,c.p*1.2+n);c.rawHeal(c.low(),dealt*.5);});
define('aurelia',c=>{c.shield(c.partner(),1.2);c.buff(c.partner(),'poiseBoost',.3,2);},c=>field(c,'aurelia',.2+c.take('dragon')*.1));
define('finch',c=>{const a=c.find(c.a.m.repair);if(a&&a.m.repairedRound!==c.b.round&&(!a.m.repairedRound||c.b.round-a.m.repairedRound>=2)){a.readyRound=Math.max(c.b.round,a.readyRound-1);a.m.repairedRound=c.b.round;}},c=>{c.partner().m.mechanical=true;});
define('quill',c=>{c.hit(c.e,.6);c.route();},c=>{const targets=c.foes().filter(e=>c.has(e,'route'));(targets.length?targets:[c.e]).forEach(e=>{c.hit(e,1.2,15);c.shield(c.low(),.4);});});
define('lyra',c=>{c.heal(c.low(),c.low().hp/c.low().maxHp<.35?2:1.2);},c=>{const n=c.take('song');allHeal(c,.9+n*.3);const a=c.low();if(a.dots.length){const d=a.dots.shift(),amount=Math.min(d.power*d.turns,c.p*1.5);a.debts.push({amount,due:c.b.round+1});}});
define('orion',c=>{c.shield(c.partner(),1.2);c.protect(c.partner(),.3);c.ev.skipMark=true;},c=>{const n=c.take('oath');c.foes().forEach(e=>c.hit(e,.9+n*.2,10+n*5));});
define('noctis',c=>c.buff(c.partner(),'delayDamage',c.p*2,1),c=>{const a=c.partner(),n=Math.min(Math.max(0,(a.m.yesterday||a.hp)-a.hp),c.p*2.4);c.rawHeal(a,n);c.a.debts.push({amount:Math.round(n*.5),due:c.b.round+1});});
define('tessa',c=>{if(!c.clean())c.shield(c.low(),.4);c.heal(c.low(),1);},c=>{c.all().forEach(a=>c.heal(a,a.shield?.8:1.2));c.mark(c.e,'辉');});
define('rune',c=>{c.buff(c.e,'coordinate',1,2);c.hit(c.e,.6,15);},c=>{c.foes().filter(e=>e.marks.some(m=>m.phase==='潮')).forEach(e=>c.poise(e,20));c.all().forEach(a=>c.buff(a,'delayResist',1,1));});
define('ignis',c=>{c.hit(c.e,1.3);const other=c.foes().find(e=>e!==c.e);if(other)c.hit(other,.39,5);},c=>{const n=c.take('charge'),target=c.foes().find((e,i)=>i>=2)||c.e;c.hit(target,1.5+n*.2,30+n*(c.foes().length>2?5:2));});
define('eirene',c=>c.heal(c.low(),2.4),c=>{let n=0;for(const a of c.all()){n+=a.m.lily||0;a.m.lily=0;}allHeal(c,1+n*.2);c.all().slice(0,n).forEach(a=>c.clean(a));c.shield(c.low(),.7);});
define('caelum',c=>{reduce(c,c.low(),.3);if(c.low().m.feather)c.poise(c.e,15);},c=>{const n=c.b.allies.reduce((s,a)=>s+(a.m.feather?1:0),c.a.m.selfFeather?1:0);c.b.allies.forEach(a=>a.m.feather=false);c.a.m.selfFeather=false;c.hit(c.e,1.5+Math.min(3,n)*.4,30);allShield(c,Math.max(0,n-3)*.3);});
define('seraphine',c=>{c.cost(.08);c.inc('seal',1,3);c.buff(c.e,'bloodClaim',1,2);c.hit(c.e,1);},c=>{const n=c.take('seal'),blood=c.take('blood');c.rawHit(c.e,c.p*(1.5+n*.3)+blood);c.buff(c.e,'attackDown',.25,1);});
define('ragnar',c=>c.front().forEach(a=>c.shield(a,.7)),c=>{const n=c.take('ember');let hit=0;c.foes().forEach(e=>hit+=c.hit(e,.7+n*.2,15));const back=c.all().slice(2);for(const a of back)c.rawShield(a,Math.min(c.p*1.2,hit*.25)/Math.max(1,back.length));});
define('elysium',c=>{const id=c.b.tactics.policies?.elysium?.partner;c.ev.phaseOverride=id?c.phaseOf(id)||'辉':'辉';c.hit(c.e,.96);},c=>{c.a.m.colors=[];c.copyReaction();});
define('pero',c=>{const a=c.all().filter(x=>c.b.allies.indexOf(x)>=2).sort((x,y)=>x.hp/x.maxHp-y.hp/y.maxHp)[0]||c.low();c.shield(a,.7);c.a.m.nextPhase='岚';c.ev.skipMark=true;},c=>{const n=c.take('crates');if(n)lowPair(c).slice(0,n).forEach(a=>c.heal(a,1.2));else reduce(c,c.low(),.2);});
define('wren',c=>{c.route();c.buff(c.e,'weakPoise',.2,2);},c=>{const other=c.foes().find(e=>e!==c.e);c.route();if(other)c.route(other);for(const e of [c.e,other].filter(Boolean)){c.buff(e,'taunt',1,1);c.status(e,'taunt').source=c.front()[0]?.id;}});
define('keres',c=>{const n=c.get('molten');c.hit(c.e,.8,15);c.shred(c.e,n?2:1.2);if(n)c.inc('molten',-1);},c=>{const n=c.take('molten'),amount=c.shred(c.e,Math.min(2.4,1+n*.45));rawShieldSplit(c,amount);});
define('vireo',c=>{c.all().slice(-2).forEach(a=>c.hot(a,.65));},c=>{let pool=c.take('water');for(const a of [...c.all()].sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)){const n=c.rawHeal(a,pool,true);pool-=n;}rawShieldSplit(c,pool);});
define('sirius',c=>{c.route();reduce(c,c.low(),.25);},c=>{const n=c.take('patrol');attackAllMarked(c,1.5+n*.3);if(c.foes().length===1)c.poise(c.e,n*5);});
define('moss',c=>{c.clean(c.low(),true);c.heal();if(c.get('remnants')){c.inc('remnants',-1);c.shield(c.low(),.4);}},c=>{const n=c.take('remnants');c.all().forEach(a=>c.hot(a,.3+n*.2));c.mark(c.e,'潮');});
define('mistral',c=>{c.cold();c.hit(c.e,.4,10);},c=>c.foes().forEach(e=>c.poise(e,c.has(e,'cold')?30:20)));
define('cinder',c=>c.hit(c.e,c.has(c.e,'route')?1.3:1,15),c=>{c.hit(c.e,2,25);const other=c.foes().find(e=>e!==c.e&&e.lastReactionRound);if(other)c.hit(other,1.2,10);});
define('nyx',c=>c.shield(c.partner(),.4),c=>{const n=c.take('threads'),a=c.low(),d=c.clean(a,true);if(d)c.rawHit(c.e,Math.min(c.p*(1+n*.4),d.power*d.turns));else c.shield(a,.5+n*.35);});
define('vega',c=>{const p=c.find(c.a.m.warp)||c.partner(),q=c.find(c.a.m.weft)||c.a;c.a.m.warp=p.id;c.a.m.weft=q.id;c.buff(p,'linked',q.id,2);c.buff(q,'linked',p.id,2);},c=>field(c,'vega',c.take('weave')));
define('tam',c=>{c.hit(c.e,.6,15);c.buff(c.e,'crack',.2,2);},c=>c.foes().forEach(e=>c.poise(e,c.has(e,'crack')?35:20)));
define('sela',c=>{c.route();c.shift(c.partner());},c=>{const n=c.take('receipts');c.all().filter(a=>!a.acted).slice(0,n).forEach(a=>c.buff(a,'discount',1,1));});
define('bront',c=>{c.hit(c.e,1,15);c.shred(c.e,1);c.shield(c.a,.4);},c=>{const n=c.take('pressure');c.foes().forEach(e=>c.poise(e,15+n*5));for(const a of c.all())for(const w of a.wards)if(!w.extended){w.expires++;w.extended=true;}});
define('fula',c=>{c.hit(c.e,1,15);c.buff(c.e,'evidence',c.e.evidence||0,2);},c=>{const n=c.e.evidence||0;c.e.evidence=0;c.hit(c.e,1.4+n*.4,20+n*10);const other=c.foes().find(e=>e!==c.e);if(other)c.hit(other,.5,5);});
define('astreus',c=>{c.clean(c.partner(),false,'delay');if(c.get('sync')>=3)c.all().forEach(a=>c.buff(a,'poiseBoost',.3,1));},c=>{if(c.e.boss){c.e.boss.charge++;c.a.m.freezeCycle=c.e.finalAct||1;}c.all().forEach(a=>c.buff(a,'poiseBoost',.6,1));});
define('lumit',c=>{const p=c.partner();p.hp===p.maxHp?c.shield(p,.7):c.heal(p,1.2);},c=>{const n=c.take('stock'),pair=lowPair(c);pair.forEach(a=>c.rawHeal(a,n/pair.length,true));c.mark(c.e,'辉');});
define('gale',c=>{c.hit(c.e,.8);c.a.m.returnId=c.e.id;c.a.m.returnRound=c.b.round+1;},c=>{if(c.a.m.returnId!==undefined&&c.a.m.returnRound>=c.b.round){const e=c.foes().find(e=>e.id===c.a.m.returnId);if(e)c.hit(e,1.8,20);}delete c.a.m.returnId;});
define('sable',c=>{c.hit(c.e,1);c.buff(c.e,'deferHeal',.25,2);},c=>{const n=c.take('needle'),amount=Math.min(c.p*(.5+n*.5),c.e.deferredHeal||0);c.e.deferredHeal=Math.max(0,(c.e.deferredHeal||0)-amount);c.rawHeal(c.a,amount);c.hit(c.e,1.2,15);});
define('eos',c=>{const a=c.all().find(a=>!a.acted)||c.low();c.shield(a,.4);c.buff(a,'healBoost',.2,1);},c=>{const n=c.take('rites');c.all().forEach(a=>{c.buff(a,'healBoost',.1+n*.1,2);reduce(c,a,.1);});c.mark(c.e,'辉');});
define('solara',c=>{c.heal(c.low(),1.6);if(c.low().m.dyingStar)c.hot(c.low(),.5);},c=>{const n=c.take('stars');allHeal(c,1.2+n*.25);if(n>=3&&!c.a.m.revivedSomeone&&reviveOne(c))c.a.m.revivedSomeone=true;});
define('bram',c=>{const i=c.b.allies.indexOf(c.a),front=i<2;c.b.allies.filter((a,j)=>(j<2)===front&&a.hp>0).forEach(a=>c.shield(a,.4));},c=>c.all().forEach(a=>reduce(c,a,.15)));
define('iris',c=>{c.heal(c.low(),1,true);c.shield(c.low(),.4);},c=>c.rawHeal(c.low(),c.take('record'),true));
define('ferro',c=>{c.buff(c.e,'taunt',1,1);c.shield(c.a,.7);},c=>c.all().forEach(a=>reduce(c,a,.3)));
define('mira',c=>{if(c.get('dim')){c.aoe(1.2);c.shield(c.a,.7);}else c.hit(c.e,1.5,20);},c=>{if(c.get('dim'))c.shred(c.e,3);else c.hit(c.e,2.5,15);});
define('suzu',c=>{c.shred(c.e,.6);c.hit(c.e,.7,20);},c=>{c.all().forEach(a=>c.buff(a,'poiseBoost',.4,1));c.aoe(.6);});
define('dune',c=>{c.route();c.buff(c.e,'revealed',1,2);},c=>{c.all().forEach(a=>c.clean(a,false,'obscure'));c.route();});
define('coral',c=>c.hot(c.low(),.5),c=>{const n=c.take('coral');c.all().forEach(a=>c.shield(a,.3+n*.15+(a.statuses.some(s=>s.key.startsWith('hot:'))?.3:0)));});
define('petra',c=>c.front().forEach(a=>c.shield(a,1.2)),c=>{const n=c.take('bearing');c.all().forEach(a=>reduce(c,a,.2+n*.1));});
define('maris',c=>{c.hit(c.e,.8,20);c.cold();},c=>{c.poise(c.e,40);reduce(c,c.low(),.25);});
define('fen',c=>{c.hit(c.e,.5);c.dot(c.e,.4);},c=>{detonate(c,false);c.all().forEach(a=>c.clean(a,false,'obscure'));});
define('hana',c=>{c.heal();if(c.get('seed')){c.inc('seed',-1);c.clean();}},c=>{const n=c.take('seed');c.all().forEach(a=>c.hot(a,.3+n*.2));c.mark(c.e,'辉');});
define('boreal',c=>{c.hit(c.e,c.e.marks.some(m=>m.phase==='潮')?1:.6,15);c.cold();},c=>{const cold=c.has(c.e,'cold');c.e.statuses=c.e.statuses.filter(s=>s.key!=='cold');c.poise(c.e,cold?40:20);});
define('solis',c=>{c.hit(c.e,.6);const shield=c.consumeShields([c.a],.2);c.dot(c.e,.55,shield?3:2);},c=>detonate(c,false,Math.max(1,c.take('sun'))));
define('helia',c=>allHeal(c,.65),c=>{const amount=c.consumeShields([c.a],1,c.a.id);rawShieldSplit(c,amount);c.heal(c.low(),1.2);});
define('kipp',c=>c.buff(c.partner(),'prepare',1,2),c=>{c.a.guard=true;c.a.m.firstNext=true;});
define('vera',c=>{const n=c.cost(.05);c.rawHeal(c.partner(),n);c.shield(c.partner(),.4);},c=>{const n=c.consumeShields([c.a],1);c.rawShield(c.low(),n);c.all().forEach(a=>reduce(c,a,.1));});
define('lynx',c=>{c.hit(c.e,.6);c.dispel(c.e);},c=>c.hit(c.e,c.e.shield?1:2.2,c.e.shield?40:10));
define('aeolus',c=>{const other=c.foes().find(e=>e!==c.e),m=c.e.marks[0];if(other&&m&&!m.copied){other.marks.push({...m,copied:true,expires:other.turns+2});other.marks=other.marks.slice(-2);}c.hit(c.e,.7);},c=>{const n=c.take('wind');c.foes().forEach(e=>c.poise(e,15+n*5));c.all().forEach(a=>reduce(c,a,.15));});
define('themis',c=>{c.hit(c.e,.8);c.buff(c.e,'attackDown',.2,1);},c=>{const n=c.take('compensation');c.rawHit(c.e,n*.5);c.rawHeal(c.low(),n*.5);});
define('odo',c=>{const h=c.low().statuses.find(s=>s.key.startsWith('hot:')&&!s.extended);if(h){h.expires++;h.extended=true;}else c.heal(c.low(),.7);},c=>{c.all().forEach(a=>c.buff(a,'delayResist',1,1));c.heal(c.low(),1.3);});
define('cassia',c=>{if(c.get('medicine')){c.inc('medicine',-1);allHeal(c,.6);c.clean();}else c.heal(c.low(),.5);},c=>{c.inc('medicine',1,3);c.heal(c.low(),1.3);c.a.readyRound=Math.max(c.a.readyRound,c.b.round+3);});
define('rhoda',c=>{c.route();c.buff(c.e,'meridian',1,2);},c=>{c.foes().filter(e=>c.has(e,'meridian')).slice(0,2).forEach(e=>c.hit(e,.6,10));const a=c.all().find(a=>!a.acted);if(a)c.buff(a,'poiseBoost',.4,1);});
define('cirus',c=>{c.hit(c.e,1.2);const other=c.foes().find(e=>e!==c.e&&c.has(e,'route'));if(other)c.hit(other,.5,10);},c=>{const n=c.take('line');c.hit(c.e,1.7+n*.4,20);const other=c.foes().find(e=>e!==c.e);if(other)c.hit(other,.5,5);});
define('vesna',c=>lowPair(c).forEach(a=>{c.heal(a,.7);c.hot(a,.3);}),c=>{const n=c.get('letters');allHeal(c,.8+n*.2);c.all().forEach(a=>c.clean(a,true));c.set('letters',0);c.a.m.letterIds=[];});
define('tarn',c=>{c.hit(c.e,.6);c.cold();if(c.a.m.mirror===c.e.id)c.shield(c.a,.4);},c=>c.buff(c.a,'reflectStatus',1,2));
define('ario',c=>c.all().slice(-2).forEach(a=>c.shield(a,.4)),c=>{c.all().forEach(a=>c.buff(a,'delayResist',1,1));c.front().forEach(a=>c.shield(a,.7));});
define('libre',c=>{c.route();c.buff(c.e,'petition',1,2);},c=>{if(c.a.m.recordedBuff){c.dispel(c.e);c.buff(c.e,'buffDamp',.2,2);}c.poise(c.e,15);});
define('skor',c=>{c.hit(c.e,.6);c.dot(c.e,c.has(c.e,'seal')?.75:.55);},c=>detonate(c,true));
define('piscia',c=>{const pair=fishPair(c);pair.forEach(a=>c.heal(a,1));c.shield(pair[0],.4);},c=>{const pair=fishPair(c);pair.forEach((a,i)=>c.heal(a,i===0?2.4:1.2));});
define('capri',c=>{c.hit(c.e,.8,15);c.shred(c.e,.7);},c=>{c.hit(c.e,1.2,20);c.shred(c.e,2);c.shield(c.a,.7);});
define('vele',c=>{const a=c.low();if(a.m.shadowLamp){c.clean(a);a.m.shadowLamp=false;}c.heal(a,.7);},c=>{c.all().forEach(a=>c.buff(a,'statusResist',1,1));c.mark(c.e,'幽');});
define('corvus',c=>c.hit(c.e,c.has(c.e,'route')?1.4:1,15),c=>{c.hit(c.e,1.8,20);c.dispel(c.e);});
define('moro',c=>{c.hit(c.e,.7);const n=Math.min(.2,c.e.atk*.1/c.a.atk);c.buff(c.a,'attackUp',n,1);c.buff(c.e,'attackDown',Math.min(.1,c.a.atk*n/c.e.atk),1);c.set('stolen',c.a.atk*n);},c=>{const n=c.take('stolen');c.a.statuses=c.a.statuses.filter(s=>s.key!=='attackUp');c.rawHit(c.e,c.p*1.4+n*2);});
define('selkis',c=>c.front().forEach(a=>c.shield(a,1.2)),c=>{const n=c.take('toll');c.aoe(1+n*.3);c.foes().forEach(e=>c.dispel(e));});
define('wisp',c=>{c.dot(c.e,.4);if(!c.e.boss){c.buff(c.e,'taunt',1,1);c.status(c.e,'taunt').source=c.front()[0]?.id;}},c=>detonate(c,false));
define('flint',c=>c.hit(c.e,.6,c.e.marks.length?10:20),c=>c.hit(c.e,1.2,c.e.consumedFire?35:20));
define('aura',c=>{c.heal(c.low(),.7);c.shield(c.low(),.7);},c=>rawShieldSplit(c,c.take('cloth'),true));
define('luce',c=>{c.hit(c.e,.7,15);if(c.get('refractions')>=7){c.set('refractions',0);c.cold();}},c=>{c.dispel(c.e);c.all().forEach(a=>c.buff(a,'poiseBoost',.3,1));});
define('aurora',c=>{lowPair(c).forEach(a=>c.shield(a,.7));c.buff(c.e,'attackDown',.15,1);},c=>field(c,'aurora',.15+c.take('curtain')*.025));
define('lumen',c=>c.low().statuses.some(s=>s.key.startsWith('hot:'))?c.shield(c.low(),.4):c.heal(c.low(),.7),c=>{c.all().forEach(a=>{const s=c.status(a,'seal');if(s)s.expires--;else c.buff(a,'sealResist',1,1);});c.mark(c.e,'辉');});
define('garde',c=>{c.shield(c.a,1.2);c.protect(c.partner(),.25);},c=>{const n=c.take('stance');c.all().forEach(a=>reduce(c,a,.1+n*.05));});
define('velli',c=>{const a=c.partner(),w=a.wards.find(w=>!w.extended);if(w){w.expires++;w.extended=true;}else c.shield(a,.4);},c=>{c.rawShield(c.partner(),Math.min(c.p*2.2,c.get('broken')||c.p),true);c.mark(c.e,'霆');});
define('egide',c=>allShield(c,.4),c=>{const n=c.take('emblems');c.front().forEach(a=>{c.buff(a,'shieldBoost',.15*n,2);c.clean(a);});});
define('vallum',c=>{c.front().forEach(a=>c.shield(a,.7));c.buff(c.e,'bypass',1,1);},c=>{const n=c.take('advance');c.all().forEach(a=>c.buff(a,'poiseBoost',.15*n,1));c.all().slice(2).forEach(a=>reduce(c,a,.2));});
define('rikka',c=>{c.route();c.buff(c.e,'calibrated',1,1);c.e.calibration=[];},c=>{c.all().filter(a=>!a.acted).forEach(a=>c.buff(a,'attackUp',.25,1));c.e.calibration=[];});
define('brook',c=>c.heal(c.low(),c.low().dots.length?1.4:1),c=>{c.all().forEach(a=>{c.clean(a,true);c.heal(a,.6);});});
define('falla',c=>c.all().forEach(a=>c.hot(a,.3)),c=>c.all().forEach(a=>{const s=c.status(a,'hot:falla');if(s)c.rawHeal(a,s.value);}));
define('undine',c=>c.hit(c.e,c.a.shield?1.6:1.4,15),c=>{const n=c.hit(c.e,2.1,20);c.rawHeal(c.low(),Math.min(c.p,n*.3));});
define('deluge',c=>{if(c.get('release'))c.poise(c.e,30);else c.front().forEach(a=>c.shield(a,1));},c=>{const n=Math.min(c.p*2,c.consumeShields(c.all(),.25));c.foes().forEach(e=>c.poise(e,20+Math.round(n/c.p*10)));});
define('vapor',c=>{const n=c.hit(c.e,1.2);c.rawHeal(c.a,n*.5);},c=>{const asleep=c.has(c.e,'sleep');c.hit(c.e,1.6,35);if(asleep)allShield(c,.4);});
define('yume',c=>{c.heal();if(c.low().m.dreamSeed){c.clean();c.low().m.dreamSeed=false;}},c=>{c.all().forEach(a=>{c.hot(a,.4);if(a.m.dreamSeed)c.shield(a,.4);});c.mark(c.e,'幽');});
define('lull',c=>c.poise(c.e,10),c=>{if(c.e.boss)c.poise(c.e,25);else{const s=c.status(c.e,'sleep');if(s&&!s.extended){s.expires++;s.extended=true;}else c.poise(c.e,20);}});
define('oneira',c=>{c.buff(c.e,'attackDown',.2,1);c.cold();},c=>{const n=c.take('omens');c.all().forEach(a=>reduce(c,a,a===c.low()?.2+n*.1:.1));});
define('somnus',c=>c.buff(c.e,'sleepLock',1,2),c=>{c.e.statuses=c.e.statuses.filter(s=>s.key!=='sleepLock');if(c.e.boss)c.poise(c.e,35);else if(c.b.tactics.policies?.somnus?.mode==='support'){const s=c.status(c.e,'sleep');if(s&&!s.extended){s.expires++;s.extended=true;}}else{c.e.statuses=c.e.statuses.filter(s=>s.key!=='sleep');c.poise(c.e,35);}});
define('somnia',c=>rawShieldSplit(c,c.p*2),c=>{c.buff(c.partner(),'delayedHeal',c.take('pain')*.5,1);});
define('castor',c=>{c.hit(c.e,1);c.buff(c.e,'firstBeat',.3,1);},c=>{c.hit(c.e,2,20);const p=c.all().find(a=>!a.acted)||c.partner();c.shield(p,.7);});
define('pollux',c=>{c.hit(c.e,1.2);if(c.b.lastTarget===c.e.id)c.shred(c.e,.8);},c=>{c.hit(c.e,1.9,25);const a=c.find(c.b.lastActor)||c.partner();reduce(c,a,.2);c.protect(a,.2);});
define('valeria',c=>{c.shield(c.partner(),1.2);c.a.m.recordEnemy=c.e.id;},c=>{if(c.a.m.recordedBuff)c.dispel(c.e);c.all().forEach(a=>c.clean(a));c.a.readyRound=Math.max(c.a.readyRound,c.b.round+3);});
define('severin',c=>{if(c.ap(2)===2)c.b.actionDebt+=1;c.front().forEach(a=>c.shield(a,.4));},c=>{const n=c.ap(2);c.b.actionDebt+=n;allShield(c,.7);});
define('morwen',c=>{c.shield(c.partner(),.7);c.buff(c.partner(),'statusResist',1,1);c.a.m.witness=c.partner().id;},c=>{const a=c.find(c.a.m.witness);if(a&&c.revive(a)){c.a.m.revivedSomeone=true;c.a.readyRound=c.b.round+2;}});
define('thalor',c=>{if(c.b.tactics.policies?.thalor?.mode==='support')c.shield(c.low(),1.2);else c.poise(c.e,30);},c=>{const n=Math.min(c.p*3,c.consumeShields(c.all(),1,c.a.id));c.foes().forEach(e=>c.rawHit(e,c.p*.5+n/Math.max(1,c.foes().length)));});
define('aevor',c=>{c.poise(c.e,40);if(c.e.exposedUntil>c.b.round)c.buff(c.e,'weakRecovery',.3,1);},c=>{c.buff(c.e,'noRecover',1,2);c.a.m.cutCycle=c.e.finalAct||1;c.a.readyRound=c.b.round+2;c.set('cuts',0);});
define('anamnesis',c=>{const a=c.all().find(a=>!c.a.m.witnesses?.includes(a.id))||c.low();c.shield(a,1.2);},c=>{c.a.m.witnesses=[];if(c.b.tactics.policies?.anamnesis?.mode!=='support'&&!c.a.m.revivedSomeone&&reviveOne(c))c.a.m.revivedSomeone=true;else{allHeal(c,1.4);c.all().forEach(a=>c.clean(a));}});
define('causalia',c=>{const a=c.all().find(a=>a.debts.length);if(a){const d=a.debts.shift(),n=Math.floor(d.amount/2);a.debts.push({amount:n,due:c.b.round+1},{amount:d.amount-n,due:c.b.round+2});}c.shield(c.low(),.4);},c=>{const debtor=c.all().find(a=>a.debts.length),p=c.partner();if(debtor&&p!==debtor){const d=debtor.debts[0],n=Math.min(d.amount*.5,p.shield,c.get('debtSeen'));d.amount-=Math.floor(n);let rest=Math.floor(n);for(const w of p.wards){const take=Math.min(w.value,rest);w.value-=take;p.shield-=take;rest-=take;}}});
define('nullion',c=>{const buff=c.removeBuff(c.a);c.dispel(c.e);c.poise(c.e,buff?25:12);},c=>{if(c.b.tactics.policies?.nullion?.mode==='support'){c.all().forEach(a=>{c.clean(a);c.removeBuff(a);});}else{c.shred(c.e,3);c.consumeShields(c.all(),.25);}const light=c.take('freedom');if(light)c.shield(c.low(),light*.2);});
function passive(c,k,d={}){
 const {a,b}=c,m=a.m,mine=isMine(c,d),toSelf=d.to===a,target=d.target;
 // Skill hooks dispatch only three levels deep. Copied healing never re-enters this dispatcher.
 if(['heal','shield'].includes(k)&&d.to&&d.value>0){const link=c.status(d.to,'linked');if(link&&d.actor===a&&c.once('share:'+d.to.id)){const other=c.find(link.value);if(other){if(k==='heal')c.rawHeal(other,d.value*.3,true);else c.rawShield(other,d.value*.3,false,true);}}}
 switch(a.id){
 case 'milo':if(k==='reaction'&&d.name==='归名'&&m.extendName===b.round&&c.once('longName')){const reduce=c.status(c.low(),'reduce');if(reduce)reduce.expires=b.round+2;}if(k==='hurt'&&d.to.hp>0&&d.to.hp/d.to.maxHp<.35&&!d.to.m.lampSpent&&c.once('lamp'))d.to.m.lamp=true;break;
 case 'lark':if(k==='reaction'&&!mine&&d.pair.includes('岚')&&c.once('reply'))c.energy(d.actor);break;
 case 'scarlet':if(k==='reaction'&&d.donor===a&&d.actor!==a&&d.pair.includes('焰'))c.inc('needle',1,3);break;
 case 'selene':if(k==='shieldBreak'&&d.owner===a&&c.get('butterflyRound')!==b.round){c.set('butterflyRound',b.round);c.set('butterflyThis',0);}if(k==='shieldBreak'&&d.owner===a&&c.get('butterflyThis')<2){c.inc('butterflyThis',1,2);c.inc('butterfly',1,4);c.clean(d.to);}break;
 case 'astra':if(k==='reaction'&&!(m.anchorKinds||[]).includes(d.name)){(m.anchorKinds||=[]).push(d.name);c.inc('anchor',1,3);}break;
 case 'bran':if(k==='shieldBreak'&&d.owner===a)c.inc('shards',1,2);break;
 case 'flora':if(k==='heal'&&d.value>0){if(m.gardenRound!==b.round){m.gardenRound=b.round;m.gardenHits=0;}if(m.gardenHits++<2&&c.inc('garden',1,3)>=3){c.set('garden',0);c.inc('herbs',1,3);}}break;
 case 'nix':if(k==='action'&&mine&&target?.boss?.phase==='charge')c.poise(target,10);break;
 case 'vesper':if(k==='enemyHeal')c.inc('feast',d.value,c.p*2);break;
 case 'aurelia':if(k==='shieldBreak'&&c.once('dragon'))c.inc('dragon',1,3);break;
 case 'finch':if(k==='cooldown'&&!mine)m.repair=d.actor.id;break;
 case 'quill':if(k==='attack'&&mine&&b.lastTarget!==target.id&&c.once('map'))c.poise(target,10);break;
 case 'lyra':if(['cleanse','saved'].includes(k)&&c.once('song'))c.inc('song',1,3);break;
 case 'orion':if(k==='hurt'&&d.value>0&&(c.has(d.to,'protect')||d.transferred)){if(m.oathRound!==b.round){m.oathRound=b.round;m.oathHits=0;}if(m.oathHits++<2)c.inc('oath',1,4);}break;
 case 'noctis':if(k==='roundStart')for(const p of c.all())p.m.yesterday=p.hp;break;
 case 'tessa':if(k==='cleanse'&&d.removed.power&&c.once('medicine'))c.buff(d.to,'medicine',1,2);break;
 case 'rune':if(k==='roundEnd')for(const e of c.foes()){const found=e.marks.some(x=>x.source===a.id&&x.phase==='潮');if(found&&m.mapId===e.id&&m.mapRound===b.round-1){c.poise(e,15);m.mapRound=0;}else if(found){m.mapId=e.id;m.mapRound=b.round;}}break;
 case 'ignis':if(k==='hit'&&d.actor&&b.enemies.indexOf(target)>=2){if(m.chargeRound!==b.round){m.chargeRound=b.round;m.chargeHits=0;}if(m.chargeHits++<2)c.inc('charge',1,4);}break;
 case 'eirene':if(k==='cost'&&d.value>0&&d.to.m.lilyRound!==b.round){d.to.m.lilyRound=b.round;d.to.m.lily=1;}break;
 case 'caelum':if(['reaction','shield'].includes(k)&&d.actor){d.actor.m.feather=true;if(d.actor===a)m.selfFeather=true;}break;
 case 'seraphine':if(k==='hurt'&&d.enemy&&d.value>0&&c.has(d.enemy,'bloodClaim')){c.inc('blood',Math.min(d.value*.4,c.p*.6),c.p*2);d.enemy.statuses=d.enemy.statuses.filter(s=>s.key!=='bloodClaim');}break;
 case 'ragnar':if(k==='shieldBreak'){if(m.emberRound!==b.round){m.emberRound=b.round;m.emberHits=0;}if(m.emberHits++<2)c.inc('ember',1,4);}break;
 case 'elysium':if(k==='reaction'&&!(m.colors||[]).includes(d.name)){(m.colors||=[]).push(d.name);m.colors=m.colors.slice(-3);}break;
 case 'pero':if(k==='beforeHit'&&!d.aoe&&!d.dot&&d.to!==a&&b.allies.indexOf(d.to)>=2&&d.amount>=d.to.hp&&c.get('crates')>0){d.amount*=.6;c.inc('crates',-1);c.notes('丢下补给 · 保护归人');}break;
 case 'wren':if(k==='beforeHit'&&d.enemy&&c.has(d.enemy,'route')&&b.allies.indexOf(d.to)>=2&&c.once('windShield'))c.shield(d.to,.4);break;
 case 'keres':if(k==='reaction'&&(mine||d.donor===a))c.inc('molten',1,3);break;
 case 'vireo':if(k==='heal'&&d.overflow>0&&c.once('water'))c.inc('water',d.overflow*.5,c.p*2);break;
 case 'sirius':if(k==='enemyAction'&&c.has(d.enemy,'route')){if(m.lastVictim&&m.lastVictim!==d.target?.id&&c.once('patrol'))c.inc('patrol',1,3);m.lastVictim=d.target?.id;}break;
 case 'moss':if(k==='reaction'&&c.once('remnants'))c.inc('remnants',1,3);break;
 case 'mistral':if(k==='wake'&&d.actor)c.buff(d.actor,'poiseBoost',.3,1);break;
 case 'cinder':if(k==='attack'&&mine&&target.lastReactionSerial===b.actionSerial-1)c.poise(target,12);break;
 case 'nyx':if(k==='reaction'&&(mine||d.donor===a)&&d.pair.includes('幽'))c.inc('threads',1,3);if(k==='shieldExpire'&&d.owner===a&&d.value>0&&c.once('threadExpire'))c.inc('threads',1,3);break;
 case 'vega':if(k==='reaction'&&[m.warp,m.weft].includes(d.actor?.id)&&m.lastWeaver!==d.actor.id){m.lastWeaver=d.actor.id;c.inc('weave',1,3);}if(k==='action'&&d.type==='skill'&&d.actor?.id===m.warp&&b.domain?.id==='vega'&&c.once('weaveMark')){const other=c.find(m.weft);if(other?.hp>0)c.markAs(d.target,other);}break;
 case 'tam':if(k==='beforeAttack'&&mine&&target.shield>0&&c.once('ore'))c.poise(target,10);break;
 case 'sela':if(k==='hit'&&!mine&&d.actor&&c.status(target,'route')?.source===a.id&&c.once('receipt'))c.inc('receipts',1,2);break;
 case 'bront':if(k==='enemyShield'&&d.value>0){if(m.pressRound!==b.round){m.pressRound=b.round;m.pressHits=0;}if(m.pressHits++<2)c.inc('pressure',1,4);}break;
 case 'fula':if(k==='enemyAction'&&d.harmful){if(d.enemy.evidenceRound!==b.round){d.enemy.evidenceRound=b.round;d.enemy.evidence=0;}d.enemy.evidence=Math.min(2,(d.enemy.evidence||0)+1);}if(k==='hit'&&!mine&&d.actor&&c.has(target,'evidence')){c.poise(target,10+5*c.status(target,'evidence').value);target.statuses=target.statuses.filter(s=>s.key!=='evidence');}break;
 case 'astreus':if(k==='action'){const index=b.allies.indexOf(d.actor);if(index>(m.syncIndex??-1))c.inc('sync',1,3);else c.set('sync',1);m.syncIndex=index;}if(k==='roundStart'){m.syncIndex=-1;c.set('sync',0);}break;
 case 'lumit':if(k==='heal'&&d.actor!==a&&d.to===c.partner()&&d.overflow>0)c.inc('stock',d.overflow,c.p);break;
 case 'gale':if(k==='attack'&&mine){if(m.lastAttack!==undefined&&m.lastAttack!==target.id)c.poise(target,10);if(m.returnId===target.id&&m.returnRound===b.round)c.hit(target,.5,0,true);m.lastAttack=target.id;}break;
 case 'sable':if(k==='enemyHeal'&&c.has(d.target,'deferHeal'))c.inc('needle',1,3);break;
 case 'eos':if(k==='shield'||k==='action'&&d.type==='guard')c.inc('rites',1,2);if(k==='roundStart')c.set('rites',0);break;
 case 'solara':if(k==='hurt'&&d.to.hp>0&&d.to.hp/d.to.maxHp<.25&&!d.to.m.dyingStar){d.to.m.dyingStar=true;c.inc('stars',1,5);}break;
 case 'bram':if(k==='beforeHit'&&Math.abs(b.allies.indexOf(d.to)-b.allies.indexOf(a))===1&&d.aoe)d.amount*=.9;break;
 case 'iris':if(k==='heal'&&d.actor!==a&&d.value>0)c.set('record',Math.min(c.p*1.2,d.value));break;
 case 'ferro':if(k==='beforeHit'&&b.allies.slice(0,2).every(x=>x.hp>0)&&b.allies.indexOf(d.to)>=2&&d.aoe)d.amount*=.85;break;
 case 'mira':if(k==='action'&&mine){if(c.get('dim'))c.shield(a,.2);else c.poise(target,5);c.set('dim',c.get('dim')?0:1);}break;
 case 'suzu':if(k==='attack'&&mine&&c.once('hammer'))c.poise(target,5);break;
 case 'dune':if(k==='enemyDeath'&&c.status(target,'route')?.source===a.id&&c.once('moveRoute')){const next=c.foes()[0];if(next)c.route(next);}break;
 case 'coral':if(k==='heal'&&d.value>0&&d.to.statuses.some(s=>s.key.startsWith('hot:'))){if(m.coralRound!==b.round){m.coralRound=b.round;m.coralHits=0;}if(m.coralHits++<2)c.inc('coral',1,4);}break;
 case 'petra':if(k==='roundEnd'&&c.all().some(x=>x.wards.some(w=>w.source===a.id&&w.value>0)))c.inc('bearing',1,2);break;
 case 'maris':if(k==='action'&&mine&&(c.has(target,'coordinate')||c.has(target,'route'))&&c.once('compass'))c.poise(target,10);break;
 case 'fen':if(k==='beforeHit'&&d.dot&&toSelf&&c.foes().some(e=>e.marks.some(x=>x.phase==='焰')))d.amount*=.9;break;
 case 'hana':if(k==='attack'&&mine&&c.inc('seedAttacks',1,2)>=2){c.set('seedAttacks',0);c.inc('seed',1,2);}break;
 case 'boreal':if(k==='attack'&&mine&&c.has(target,'cold')&&c.once('aurora'))c.poise(target,10);break;
 case 'solis':if(k==='dot'&&mine)c.inc('sun',1,3);break;
 case 'helia':if(k==='heal'&&mine&&d.overflow>0)c.rawShield(d.to,Math.min(d.to.maxHp*.12,d.overflow*.5),true);break;
 case 'kipp':if(k==='action'){if(m.lastTeamType==='attack'&&d.type==='skill'&&c.once('shift'))c.buff(d.actor,'poiseBoost',.2,1);m.lastTeamType=d.type;}break;
 case 'vera':if(k==='roundStart'){const f=c.front();if(f.length===2&&Math.abs(f[0].hp/f[0].maxHp-f[1].hp/f[1].maxHp)>.3)c.shield(f.sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0],.4);}break;
 case 'lynx':if(['enemyShield','enemyShieldGain'].includes(k)&&c.once('opening'))m.opening=true;break;
 case 'aeolus':if(k==='reaction'&&d.pair.includes('岚')&&c.once('wind'))c.inc('wind',1,3);break;
 case 'themis':if(k==='hurt'&&!d.transferred)c.inc('compensation',d.value,c.p*2);if(k==='roundStart')c.set('compensation',0);break;
 case 'odo':if(k==='roundEnd')c.heal(c.low(),.3);break;
 case 'cassia':break; // finite medicine stock is seeded at battle start and spent by both skills
 case 'rhoda':if(k==='hit'&&d.actor&&c.foes().some(e=>c.has(e,'meridian'))&&!c.has(target,'meridian')&&c.once('meridian')){c.route(target);c.buff(target,'meridian',1,2);}break;
 case 'cirus':if(k==='attack'&&mine){if(m.lastLine===target.id)c.inc('line',1,2);else c.set('line',0);m.lastLine=target.id;}break;
 case 'vesna':if(k==='heal'&&mine&&d.value>0&&!(m.letterIds||[]).includes(d.to.id)){(m.letterIds||=[]).push(d.to.id);c.inc('letters',1,5);}break;
 case 'tarn':if(k==='hurt'&&toSelf&&d.enemy)m.mirror=d.enemy.id;if(k==='cold'&&target.id===m.mirror){c.poise(target,10);delete m.mirror;}break;
 case 'ario':if(k==='shieldBreak'&&d.owner===a&&c.once('fence:'+d.to.id))c.shield(d.to,.2,true);break;
 case 'libre':if(k==='hit'&&!mine&&d.actor&&c.has(target,'petition')){target.statuses=target.statuses.filter(s=>s.key!=='petition');c.shred(target,.3);}if(k==='enemyBuff'&&c.once('record'))m.recordedBuff=d.key;break;
 case 'skor':break; // burns persist through enemy shield restoration, without ignoring absorption
 case 'piscia':if(['setup','roundStart'].includes(k)&&b.tactics.allowSacrifice){const pair=fishPair(c);if(pair.length===2){c.buff(pair[0],'protect',.2,1);c.status(pair[0],'protect').source=pair[1].id;}}break;
 case 'capri':if(k==='enemyShield'&&mine&&c.inc('horn',1,2)>=2){c.set('horn',0);c.buff(a,'poiseBoost',.4,2);}break;
 case 'vele':if(k==='status'&&['seal','obscure'].includes(d.key)&&c.once('lamp:'+d.to.id))d.to.m.shadowLamp=true;break;
 case 'corvus':if(k==='hit'&&mine&&c.has(target,'route')&&c.once('letter'))c.shred(target,.3);break;
 case 'moro':if(k==='attack'&&mine&&(target.shield||c.has(target,'attackDown'))&&c.once('steal'))c.heal(a,.3);break;
 case 'selkis':if(k==='shieldBreak'&&d.owner===a){if(m.tollRound!==b.round){m.tollRound=b.round;m.tollHits=0;}if(m.tollHits++<2)c.inc('toll',1,4);}break;
 case 'wisp':if(k==='enemyAction'){const dot=d.enemy.dots.find(x=>x.source===a.id&&!x.extended);if(dot&&m.wispTarget&&m.wispTarget!==d.target?.id){dot.turns++;dot.extended=true;}m.wispTarget=d.target?.id;}break;
 case 'flint':break; // first active cost is discounted in the resource validation pipeline
 case 'aura':if(k==='shieldExpire'&&!d.recycled)c.inc('cloth',d.value*.3,c.p*1.5);break;
 case 'luce':if(k==='reaction'){if(m.refRound!==b.round){m.refRound=b.round;m.refHits=0;}if(m.refHits++<2)c.inc('refractions',1,7);}break;
 case 'aurora':if(k==='attack'&&d.actor?.shield){if(m.curtainRound!==b.round){m.curtainRound=b.round;m.curtainHits=0;}if(m.curtainHits++<2)c.inc('curtain',1,4);}break;
 case 'lumen':if(k==='heal'&&d.value>0&&c.once('wick:'+d.to.id))c.hot(d.to,.15);break;
 case 'garde':if(k==='action'&&mine&&d.type==='guard')c.inc('stance',1,3);break;
 case 'velli':if(k==='shieldBreak'&&d.to===c.partner()){c.set('broken',d.original);if(!m.returned){m.returned=true;c.rawShield(d.to,d.original*.2,true);}}break;
 case 'egide':if(k==='shieldBreak'){if(m.crestRound!==b.round){m.crestRound=b.round;m.crestIds=[];}if(!m.crestIds.includes(d.to.id))m.crestIds.push(d.to.id);if(m.crestIds.length>=2&&c.once('crest'))c.inc('emblems',1,3);}break;
 case 'vallum':if(k==='roundEnd'){if(b.allies.slice(0,2).every(a=>a.hp>0)&&c.get('protected'))c.inc('advance',1,3);else c.inc('advance',-1,3);c.set('protected',0);}if(k==='shieldBreak'||k==='shield')c.set('protected',1);break;
 case 'rikka':if(k==='hit'&&d.actor&&c.has(target,'calibrated')){const ids=target.calibration||=[];if(!ids.includes(d.actor.id))ids.push(d.actor.id);if(ids.length>=3&&c.once('calibrate'))c.poise(target,15);}break;
 case 'brook':if(k==='heal'&&mine&&d.value>0&&c.once('waterClean'))c.clean(d.to,true);break;
 case 'falla':if(k==='heal'&&d.actor!==a&&d.value>0)c.buff(a,'healOutput',.2,1);break;
 case 'undine':if(k==='attack'&&mine&&a.hp===a.maxHp)c.poise(target,10);break;
 case 'deluge':if(k==='roundStart'&&b.round>1)c.set('release',c.get('release')?0:1);break;
 case 'vapor':if(k==='attack'&&mine&&target.marks.some(m=>m.phase==='潮')&&c.once('mistHeal'))c.heal(c.low(),.4);break;
 case 'yume':if(k==='hurt'&&d.value>0)d.to.m.hurtRound=b.round;if(k==='roundEnd')c.all().filter(a=>a.m.hurtRound!==b.round).forEach(a=>a.m.dreamSeed=true);break;
 case 'lull':if(k==='beforeAttack'&&c.has(target,'sleep')&&!target.sleepSpared){target.sleepSpared=true;d.actor.m.silentAttack=true;}break;
 case 'oneira':if(k==='shield'&&c.foes().some(e=>e.boss?.charge===1)&&c.once('omen'))c.inc('omens',1,3);break;
 case 'somnus':if(k==='wake'&&c.once('wake:'+target.id))c.poise(target,Math.min(15,5*((target.wakeCount||0)+1)));break;
 case 'somnia':if(k==='hurt'&&d.to===c.partner())c.inc('pain',d.value,c.p*1.2);if(k==='roundStart')c.set('pain',0);break;
 case 'castor':if(k==='attack'&&mine)c.buff(target,'firstBeat',.2,1);if(k==='hit'&&!mine&&d.actor&&c.has(target,'firstBeat')&&c.once('second')){c.poise(target,10);target.statuses=target.statuses.filter(s=>s.key!=='firstBeat');}break;
 case 'pollux':if(k==='attack'&&mine&&b.lastActor!==a.id&&b.lastTarget===target.id&&c.once('echo'))c.poise(target,10);break;
 case 'valeria':if(k==='enemyBuff'&&d.target.id===m.recordEnemy)m.recordedBuff=d.key;if(k==='status'&&d.to===c.partner()&&c.once('exemption')){c.clean(d.to);c.buff(a,'shieldPenalty',.2,2);}break;
 case 'severin':break; // action-point debt is not a cleansable status
 case 'morwen':if(k==='death'&&d.to===c.partner())m.witness=d.to.id;break;
 case 'thalor':if(k==='roundStart'){if(b.tactics.policies?.thalor?.mode==='support')c.shield(c.low(),.4);else c.buff(a,'poiseBoost',.2,1);}break;
 case 'aevor':if(k==='action'&&mine&&target?.boss?.phase==='charge')c.inc('cuts',1,3);break;
 case 'anamnesis':if(['shield','cleanse','reaction'].includes(k)&&d.actor){const list=m.witnesses||=[];if(!list.includes(d.actor.id))list.push(d.actor.id);}break;
 case 'causalia':if(k==='roundEnd')c.set('debtSeen',Math.min(c.p*2.5,c.all().reduce((n,a)=>n+a.debts.reduce((s,d)=>s+d.amount,0),0)));break;
 case 'nullion':if(k==='removedBuff'&&b.allies.includes(d.to)&&c.once('release'))c.inc('freedom',1,3);break;
 default:throw Error('Unimplemented passive '+a.id);
 }
}
function ready(c){const id=c.a.id,m=c.a.m;if(c.b.domain&&['astra','aurelia','vega','aurora'].includes(id))return false;
 if(['lark','sela'].includes(id))return c.all().some(a=>!a.acted&&a!==c.a);
 if(id==='elysium')return (m.colors?.length||0)>=3&&!!c.b.lastReaction;
 if(id==='anamnesis')return (m.witnesses?.length||0)>=3;
 if(id==='morwen')return !m.revivedSomeone&&c.find(m.witness)?.hp===0&&!c.find(m.witness)?.revived;
 if(id==='severin')return (m.ultUses||0)<2&&c.b.extraAP===0&&c.b.ap<=5;
 if(id==='aevor')return !!c.e?.boss&&c.get('cuts')>0&&m.cutCycle!==(c.e.finalAct||1);
 if(id==='astreus')return !!c.e?.boss&&m.freezeCycle!==(c.e.finalAct||1);
 if(id==='somnus')return c.has(c.e,'sleepLock');
 if(id==='causalia')return c.get('debtSeen')>0&& c.all().some(a=>a.debts.length)&&c.partner().shield>0;
 if(['thalor','nullion'].includes(id)&&!c.b.tactics.allowSacrifice&&c.b.tactics.policies?.[id]?.mode!=='support')return false;
 if(id==='iris')return c.get('record')>0&&c.low().hp<c.low().maxHp;
 if(['milo','flora','lyra','tessa','eirene','vireo','moss','lumit','solara','hana','helia','cassia','vesna','piscia','falla','yume'].includes(id))return c.all().some(a=>a.hp/a.maxHp<.8)||id==='solara'&&c.b.allies.some(a=>!a.hp&&!a.revived);
 return true;
}
function useful(c){if(c.a.id==='finch')return !!c.find(c.a.m.repair)&&c.find(c.a.m.repair).readyRound>c.b.round&&c.b.round-(c.find(c.a.m.repair).m.repairedRound||-10)>=2;
 if(c.a.id==='severin')return c.b.extraAP===0&&c.b.ap<=6;
 if(['milo','flora','tessa','lyra','eirene','lumit','iris','hana','odo','cassia','aura','lumen','brook','falla','yume'].includes(c.a.id))return c.all().some(a=>a.hp/a.maxHp<(c.b.tactics.tactic==='sustain'?.95:.85)||a.dots.length)||c.e.marks.some(m=>m.phase!==c.h.phase);
 return true;
}
const api={activeIds:Object.keys(A),ultimateIds:Object.keys(U),run:(c,type)=>{const fn=type==='active'?A[c.a.id]:U[c.a.id];if(!fn)throw Error('Unimplemented skill '+c.a.id);fn(c);},passive,ready,useful};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.EclipseCovenantSkills=api;
})(typeof globalThis!=='undefined'?globalThis:this);
