(function(root){
'use strict';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tactics(C,s){const t=s.battleSettings;return `<section class="tactics-panel"><div><p class="eyebrow">A PLAN BEFORE THE STORM</p><h2>旅团战术</h2><p>前两位为前排。普攻免费；主动技冷却 2 轮。按顺序留下星痕，让下一位队友完成共鸣。</p></div><div class="tactics-controls"><label>行动策略<select id="tactic-select" aria-label="行动策略">${Object.entries(C.TACTICS).map(([id,x])=>`<option value="${id}" ${t.tactic===id?'selected':''}>${x.name}</option>`).join('')}</select></label><label>治疗触发线<select id="heal-select" aria-label="治疗触发线">${[.50,.68,.80].map(n=>`<option value="${n}" ${t.healAt===n?'selected':''}>生命低于 ${Math.round(n*100)}%</option>`).join('')}</select></label><label>战斗画面<select id="renderer-select" aria-label="战斗画面"><option value="illustrated" ${t.renderer!=='legacy'?'selected':''}>立绘剧场 · 2.5D</option><option value="legacy" ${t.renderer==='legacy'?'selected':''}>原版 3D 模型</option></select></label><label class="tactic-check"><input type="checkbox" id="cinematic-select" ${t.cinematic?'checked':''}>稀有角色大招特写</label></div><p class="tactic-summary">${C.TACTICS[t.tactic].desc} ${t.tactic==='sustain'?'稳守模式固定在生命低于 85% 时优先治疗。':''}</p><div class="combo-guide"><span>焰 + 霆 · 裂爆破盾</span><span>潮 + 辉 · 润生净化</span><span>辉 + 幽 · 归名庇护</span><button class="small-link" data-action="skill-rules">查看全部共鸣与规则 ↗</button></div>${window.EclipseCovenantUI.plans(C,s)}</section>`;}
function report(C,b){if(!b.report)return '';const damage=Object.values(b.report.damage).reduce((a,n)=>a+n,0)+(b.report.passive||0),healing=Object.values(b.report.healing).reduce((a,n)=>a+n,0);return `<section class="battle-review"><p class="eyebrow">THE COMPANY'S CHRONICLE</p><h3>协同战报</h3><div class="review-numbers"><span>总伤害<b>${Math.round(damage).toLocaleString()}</b></span><span>有效治疗<b>${Math.round(healing).toLocaleString()}</b></span><span>状态连携<b>${b.report.combos}</b></span><span>韧性击破<b>${b.report.breaks}</b></span><span>保护吸收<b>${b.report.protection}</b></span></div>${b.allies.map(a=>`<div class="review-member"><strong>${C.hero(a.id).name}</strong><span>伤害 ${(b.report.damage[a.id]||0).toLocaleString()}</span><span>治疗 ${(b.report.healing[a.id]||0).toLocaleString()}</span><span>挂痕助攻 ${b.report.assists?.[a.id]||0}</span><span>削韧 ${b.report.poise?.[a.id]||0}</span><span>保护 ${b.report.guarding?.[a.id]||0}</span><span>净化 ${b.report.cleanses?.[a.id]||0}</span></div>`).join('')}${b.report.passive?`<div class="review-member"><strong>持续伤害 / 反击</strong><span>伤害 ${b.report.passive.toLocaleString()}</span><span>—</span></div>`:''}<p>${b.phase==='lose'?'尝试调整接痕顺序、指定保护搭档，或用克制星相削韧打断首领。':'低稀有度的标记、治疗与护盾，也能改变整场战斗。'}</p></section>`;}
function explore(C,s){const e=s.exploration,r=e.run,active=r&&!['complete','failed','retired'].includes(r.phase);const labels={dawn:'曙曜同盟',moon:'暮月议庭',forge:'星铸工盟'};
 let content='';
 if(!active){content=`${r?`<div class="expedition-meta"><span>${{complete:'完整归航',failed:'探索失利',retired:'提前返航'}[r.phase]} · 裂隙 ${r.tier}</span><span>已领取 ${r.bank.tickets+(r.phase==='complete'?10*r.tier:0)} 星契 · ${r.bank.dust+(r.phase==='complete'?300*r.tier:0)} 星尘</span></div>`:''}<div class="explore-start"><div><p class="eyebrow">SIX STEPS INTO THE UNKNOWN</p><h2>${r?.phase==='complete'?'星光，带回了新的航路。':'没有两次完全相同的归途。'}</h2><p>六站路线 · 生命跨战斗保留 · 三选一祝福 · 阵营抉择</p><p>敌人强度随启程阵容与裂隙层级调整，搭配和祝福更重要。编队在启程时锁定。每站保存进度，刷新后可继续；未结算战斗从该站起点重演。失败或提前返航仍带回已经积存的星契与星尘。装备仅在星铸秘境掉落。</p><label>探索强度 <select id="explore-tier">${Array.from({length:Math.min(5,1+e.wins)},(_,i)=>`<option value="${i+1}">裂隙 ${i+1} · ${i===0?'初行':'进阶'}</option>`).join('')}</select></label><button class="btn primary" data-action="explore-start" ${!s.team.length?'disabled':''}>以当前旅团启程 →</button><button class="btn" data-tab="team">调整旅团</button></div><div class="explore-sigil" aria-hidden="true">✧<span>THE UNWRITTEN PATH</span></div></div>`;}
 else{
 const completed=r.step,options=C.exploreOptions(s);content=`<div class="expedition-meta"><span>裂隙 ${r.tier} · 第 ${Math.min(6,r.step+1)} / 6 站</span><span>行囊 ✧ ${r.bank.tickets} · ❖ ${r.bank.dust}</span><button class="small-link" data-action="explore-retire">提前返航并领取积存奖励</button></div><div class="route-map" aria-label="六站探索路线">${C.ROUTES.map((row,i)=>`<div class="route-column ${i<completed?'cleared':i===completed?'current':'locked'}"><small>0${i+1}</small>${row.map(n=>`<div class="route-symbol ${r.path[i]===n?'selected':''}" title="${C.NODE[n].name}">${C.NODE[n].icon}</div>`).join('')}</div>`).join('')}</div><div class="expedition-party">${r.party.map(id=>`<div><strong>${C.hero(id).name}</strong><span>${Math.round(r.hp[id]*100)}% 生命</span><i style="--health:${r.hp[id]*100}%"></i></div>`).join('')}</div>`;
 if(r.phase==='route')content+=`<div class="section-heading"><h2>选择下一站</h2><small>选定后，另一条路线将被放弃</small></div><div class="route-choices">${options.map(n=>`<button class="route-choice" data-action="explore-node" data-node="${n}"><span>${C.NODE[n].icon}</span><h3>${C.NODE[n].name}</h3><p>${C.NODE[n].desc}</p><b>沿此路前行 ↗</b></button>`).join('')}</div>`;
 if(r.phase==='battle')content+=`<div class="route-resume"><h2>${C.NODE[r.node].name}</h2><p>这场遭遇尚未结算。可继续观看，或按已设置的自动跳过完成战斗。</p><button class="btn primary" data-action="explore-resume">继续遭遇 →</button></div>`;
 if(r.phase==='blessing')content+=`<div class="section-heading"><h2>带走一道星光</h2><small>选择一个祝福，本次探索持续生效</small></div><div class="blessing-grid">${C.blessingOffers(s).map(x=>`<button class="route-choice" data-action="explore-blessing" data-id="${x.id}"><span>${x.icon}</span><h3>${x.name}</h3><p>${x.desc}</p><b>选择祝福 →</b></button>`).join('')}</div>`;
 if(r.phase==='event'){const event=C.exploreEvent(s);content+=`<section class="explore-event"><p class="eyebrow">EVERY ALLIANCE HAS A PRICE</p><h2>${event.title}</h2><p>${event.text}</p><div class="route-choices">${event.choices.map((c,i)=>`<button class="route-choice" data-action="explore-event" data-choice="${i}"><h3>${c.name}</h3><p>${c.desc}</p></button>`).join('')}</div></section>`;}
 content+=`<section class="run-blessings"><h3>本次祝福 · ${r.blessings.length}</h3>${r.blessings.length?r.blessings.map(id=>{const x=C.BLESSINGS.find(x=>x.id===id);return `<span title="${x.desc}">${x.icon} ${x.name}</span>`}).join(''):'<p>战斗胜利后，将从三种祝福中选择一种。</p>'}</section>`;
 }
 return `<div class="explore-heading"><div><p class="eyebrow">THE UNWRITTEN EXPEDITION</p><h1>星蚀探索</h1><p>力量决定你能走多远，选择决定你成为谁。</p></div><span class="explore-record">完整通关 <b>${e.wins}</b> 次</span></div>${content}<section class="faction-trust"><h3>盟约回响</h3><p>信任达到 3：曙曜提供开场护盾，暮月提高营火恢复，星铸提高攻击。探索信任独立于主线态度，也会因抉择下降。</p><div>${Object.entries(labels).map(([id,name])=>`<article><span>${name}</span><strong>${e.trust[id]>0?'+':''}${e.trust[id]}</strong><small>${e.trust[id]>=3?'援助已解锁':'信任达到 3 解锁援助'}</small></article>`).join('')}</div></section>`;
}
root.EclipseJourneyUI={tactics,explore,report};
})(window);
