// Generated by npm run portraits:import. Register only files present on disk.
(function(root){const videos={
  "astra": "assets/videos/astra.mp4",
  "aurelia": "assets/videos/aurelia.mp4",
  "noctis": "assets/videos/noctis.mp4",
  "caelum": "assets/videos/caelum.mp4",
  "seraphine": "assets/videos/seraphine.mp4",
  "ragnar": "assets/videos/ragnar.mp4",
  "elysium": "assets/videos/elysium.mp4",
  "sirius": "assets/videos/hero1.mp4",
  "vega": "assets/videos/vega.mp4",
  "astreus": "assets/videos/astreus.mp4",
  "solara": "assets/videos/solara.mp4",
  "valeria": "assets/videos/valeria.mp4",
  "severin": "assets/videos/hero9.mp4",
  "morwen": "assets/videos/hero3.mp4",
  "thalor": "assets/videos/hero4.mp4",
  "aevor": "assets/videos/hero8.mp4",
  "anamnesis": "assets/videos/hero7.mp4",
  "causalia": "assets/videos/hero6.mp4",
  "nullion": "assets/videos/hero5.mp4"
};if(typeof module!=="undefined"&&module.exports)module.exports=videos;else root.EclipsePortraitVideos=videos;})(typeof globalThis!=="undefined"?globalThis:this);
