(function(root){
  const entries = [
    {id:'bran',rarity:'N',sheet:'dawn',index:0,name:'布兰',title:'锈盾守卫',english:'BRAN',role:'护盾 · 前卫',hp:360,atk:42,cost:1,kind:'shieldOne',power:100,fx:'shield',color:'#dfbf87',skill:'旧盾新誓',detail:'为生命比例最低的存活队友赋予100点护盾，持续两个敌方回合。',quote:'旧盾还能挡住风雨。',story:'港口的最后一班岗，他已经守了十年。盾上的每一道裂纹，都记着一次平安归来。'},
    {id:'flora',rarity:'R',sheet:'dawn',index:1,name:'芙萝拉',title:'苔光药师',english:'FLORA',role:'群疗 · 支援',hp:290,atk:46,cost:2,kind:'healAll',power:65,fx:'heal',color:'#89e5b5',skill:'春息药雨',detail:'为全体存活队友恢复65点生命。',quote:'废墟里，也会开出第一朵花。',story:'她把药草种在坠落的星石上。青绿色的微光，是伤者在漫漫长夜里最熟悉的慰藉。'},
    {id:'nix',rarity:'SR',sheet:'dawn',index:2,name:'凛鸦',title:'霜羽猎手',english:'NIX',role:'冰冻 · 控制',hp:310,atk:73,cost:2,kind:'freeze',power:100,fx:'ice',color:'#89d8ff',skill:'寒鸦封缄',detail:'造成100点伤害并冰冻目标，使其跳过下一次攻击。已冰冻目标不会叠加次数。',quote:'听，雪落下之前，箭已经到了。',story:'雪原孤塔的猎手，将名字交给了冰霜。他的箭从不迷路，因为寒鸦早已看见终点。'},
    {id:'vesper',rarity:'SSR',sheet:'dawn',index:3,name:'维斯珀',title:'血蔷薇公爵',english:'VESPER',role:'吸血 · 收割',hp:360,atk:83,cost:2,kind:'drain',power:155,fx:'drain',color:'#f18eaa',skill:'夜宴终曲',detail:'造成155点伤害，恢复实际伤害量50%的自身生命。',quote:'请留下最后一支舞。',story:'沉睡王城的宴会从未散场。他以蔷薇封存伤痕，却始终记得晨光的温度。'},
    {id:'aurelia',rarity:'UR',sheet:'dawn',index:4,name:'奥蕾莉娅',title:'曜龙女帝',english:'AURELIA',role:'群攻 · 神佑',hp:390,atk:89,cost:4,kind:'solar',power:175,fx:'solar',color:'#ffdc87',ultimate:true,skill:'万曜龙临',detail:'全体敌人受到175点伤害，全体队友获得65点护盾。每场战斗限用一次。',quote:'太阳未至，我便是黎明。',story:'她与最后一条曜龙共享心跳。每当金色龙翼展开，世间便多出一寸不被日蚀吞没的光。'},
    {id:'finch',rarity:'N',sheet:'dusk',index:0,name:'菲妮',title:'发条学徒',english:'FINCH',role:'连击 · 输出',hp:285,atk:48,cost:1,kind:'double',power:38,fx:'bolt',color:'#e8c694',skill:'双拍校时',detail:'对同一目标连续造成两次38点伤害。',quote:'修好钟，就能找回明天吧？',story:'她修理一切停下的东西，从老钟到迷途的机械鸟。唯独天空那只大钟，她还在寻找发条。'},
    {id:'quill',rarity:'R',sheet:'dusk',index:1,name:'奎尔',title:'沙羽游侠',english:'QUILL',role:'贯穿 · 猎手',hp:315,atk:63,cost:2,kind:'pierce',power:120,fx:'arrow',color:'#b8d8be',skill:'流沙穿星',detail:'对主目标造成120点伤害，对另一名存活敌人造成50点伤害。',quote:'沙会抹去足迹，风会记住。',story:'沙海的向导独自背负一张没有终点的地图。他将羽毛系在箭尾，作为每个绿洲的路标。'},
    {id:'lyra',rarity:'SR',sheet:'dusk',index:2,name:'莉拉',title:'潮汐咏者',english:'LYRA',role:'治疗 · 护持',hp:325,atk:57,cost:2,kind:'tide',power:85,fx:'tide',color:'#82e4e7',skill:'沧海摇篮',detail:'治疗生命比例最低的队友85点，并为全队赋予35点护盾。',quote:'请让潮声，替你做一个好梦。',story:'海水淹没故乡之后，她从水下带回了一把竖琴。每一个音符，都是尚未说出口的告别。'},
    {id:'orion',rarity:'SSR',sheet:'dusk',index:3,name:'奥里昂',title:'雷誓圣骑',english:'ORION',role:'群攻 · 重装',hp:430,atk:69,cost:3,kind:'storm',power:95,fx:'lightning',color:'#b7acff',skill:'风暴裁庭',detail:'对全体敌人造成95点伤害，并为自身赋予90点护盾。',quote:'誓言，比雷霆先抵达。',story:'他在废弃钟楼上宣誓，以风暴为证。落下的雷光不是惩罚，而是他为旅人点亮的归途。'},
    {id:'noctis',rarity:'UR',sheet:'dusk',index:4,name:'诺克提斯',title:'永夜时君',english:'NOCTIS',role:'时停 · 群控',hp:350,atk:87,cost:4,kind:'time',power:135,fx:'time',color:'#ccb0ff',ultimate:true,skill:'零时星葬',detail:'对全体敌人造成135点伤害并冰冻，使其跳过下一次攻击。每场战斗限用一次。',quote:'这一秒，留给你。',story:'他走过所有已经失落的时间，却为一个约定停在此刻。碎裂的钟盘中，藏着无数未被选择的黎明。'}
  ];
  entries.push(
    {id:'tessa',rarity:'N',art:'tessa',index:0,name:'泰莎',title:'青灯行医',english:'TESSA',role:'治疗 · 支援',hp:305,atk:42,cost:1,kind:'heal',power:100,fx:'heal',color:'#91d6bb',skill:'旅途急救',detail:'为生命比例最低的存活队友恢复100点生命。',quote:'下一站，也一定有人等着我们。',story:'她背着药箱踏遍六域，把每一次日出记进随身的旅行手札。'},
    {id:'rune',rarity:'R',art:'rune',index:0,name:'卢恩',title:'霜图绘师',english:'RUNE',role:'冰冻 · 控制',hp:320,atk:56,cost:2,kind:'freeze',power:88,fx:'ice',color:'#93cafa',skill:'霜痕坐标',detail:'造成88点伤害并冰冻目标，使其跳过下一次攻击。',quote:'地图没有终点，只有尚未抵达的星。',story:'他用冰晶绘下天空的暗流，循着失落航路寻找风暴之上的故乡。'},
    {id:'ignis',rarity:'SR',art:'ignis',index:0,name:'伊格妮丝',title:'赤羽枪骑',english:'IGNIS',role:'贯穿 · 输出',hp:365,atk:76,cost:2,kind:'pierce',power:130,fx:'fire',color:'#ff9269',skill:'赤羽破阵',detail:'对主目标造成130点伤害，对另一名存活敌人造成50点伤害。',quote:'我会把前路，刺出一道晨光。',story:'最后一支赤羽骑兵的旗帜，仍在她的枪尖迎风燃烧。'},
    {id:'eirene',rarity:'SSR',art:'eirene',index:0,name:'伊蕾涅',title:'曙光圣女',english:'EIRENE',role:'群疗 · 护佑',hp:375,atk:58,cost:3,kind:'renew',power:90,fx:'heal',color:'#d0eec1',skill:'万物复苏',detail:'全体存活队友恢复90点生命，并获得40点护盾，持续两个敌方回合。',quote:'黑夜会过去，伤口也会。',story:'当圣域钟声沉寂，她以一朵永不凋零的百合，守着晨曦的归来。'},
    {id:'caelum',rarity:'UR',art:'caelum',index:0,name:'苍曜',title:'星龙天君',english:'CAELUM',role:'群攻 · 回生',hp:400,atk:92,cost:4,kind:'nova',power:180,fx:'solar',color:'#9fcaff',ultimate:true,skill:'六翼创生',detail:'对全体敌人造成180点伤害，为全体存活队友恢复60点生命。每场限用一次。',quote:'越过风暴，你会看见完整的天空。',story:'六翼星龙化为人形，带着破碎星空最后的祝福，自无尽天穹归来。'}
  );
  entries.push(
    {id:'seraphine',rarity:'SP',variant:'crimson',art:'seraphine-sp',name:'瑟拉菲娜',title:'绯月女皇',english:'SERAPHINE',role:'群攻 · 灼蚀',hp:460,atk:109,cost:4,kind:'crimson',power:230,fx:'fire',color:'#ff4569',ultimate:true,skill:'绯月敕令',detail:'全体敌人受到230点伤害，存活敌人附加两次55点灼烧。每场限用一次。',quote:'今夜，月亮只为你加冕。',story:'她以王冠封印绯月，在千年的静默中守住星界裂隙。唯有回应她的人，能看见猩红月光下尚未凋零的蔷薇。'},
    {id:'ragnar',rarity:'SP',variant:'crimson',art:'ragnar-sp',name:'拉格纳',title:'烬日君王',english:'RAGNAR',role:'群攻 · 守御',hp:540,atk:103,cost:4,kind:'ruin',power:210,fx:'solar',color:'#ff604d',ultimate:true,skill:'烬日王座',detail:'全体敌人受到210点伤害，全体存活队友获得120点护盾，持续两个敌方回合。每场限用一次。',quote:'余烬未冷，我的誓言便不会熄灭。',story:'当最后一轮太阳坠入深渊，他扛起破碎王座，将余火铸进巨剑。无人知晓，那看似毁灭的赤焰，一直在为万千生灵取暖。'},
    {id:'elysium',rarity:'SSP',variant:'prism',art:'elysium-sp',name:'伊璃希娅',title:'万象初光',english:'ELYSIUM',role:'创生 · 神佑',hp:520,atk:118,cost:5,kind:'genesis',power:260,fx:'astral',color:'#b8f8ff',ultimate:true,skill:'万象创生',detail:'全体敌人受到260点伤害，全体存活队友恢复120点生命并获得100点护盾，持续两个敌方回合。每场限用一次。',quote:'所有颜色，都曾是同一道光。',story:'在第一颗星诞生之前，她曾将黑暗折射成七种颜色。如今那道初光再次显现，带着所有尚未写下的未来。'}
  );
  entries.push(
    {id:'pero',rarity:'N',art:'pero-v11',sheet:'comet',index:0,name:'佩罗',title:'驿马驮夫',english:'PERO',role:'护盾 · 前卫',hp:340,atk:43,cost:1,kind:'shieldOne',power:95,fx:'shield',color:'#c9b28a',skill:'驮盾遮尘',detail:'为生命比例最低的存活队友赋予95点护盾，持续两个敌方回合。',quote:'货可以丢，人不能丢。',story:'彗星商队最老的驮夫，背上磨出的茧比盾牌还硬。他说每多挡一次风沙，就离故乡的驿站近一步。'},
    {id:'wren',rarity:'R',art:'wren-v11',sheet:'comet',index:1,name:'蕾恩',title:'风铃斥候',english:'WREN',role:'标记 · 协击',hp:300,atk:57,cost:1,kind:'mark',power:44,fx:'arrow',color:'#9fd8c9',skill:'铃音定位',detail:'造成44点伤害并标记目标，使下一次攻击伤害提高25%。',quote:'铃声响起的地方，就是箭落的地方。',story:'她在商队桅杆上挂满风铃，凭声音辨出星流的方向。被铃音锁定的猎物，从不曾逃出她的视野。'},
    {id:'keres',rarity:'SR',art:'keres-v11',sheet:'comet',index:2,name:'克蕾丝',title:'熔金匠师',english:'KERES',role:'灼烧 · 输出',hp:330,atk:74,cost:2,kind:'burn',power:118,fx:'fire',color:'#ffb27a',skill:'熔金泼洒',detail:'造成118点伤害，附加两次35点灼烧。',quote:'真金不怕火，怕的是我的火。',story:'坠星熔炉旁长大的匠人，把彗尾残金浇铸成武器。她炉中的火，据说是从一颗尚未冷透的星核里取来的。'},
    {id:'vireo',rarity:'SSR',art:'vireo-v11',sheet:'comet',index:3,name:'维里奥',title:'翠羽守望',english:'VIREO',role:'群疗 · 支援',hp:380,atk:59,cost:3,kind:'healAll',power:74,fx:'heal',color:'#a8e6c0',skill:'翠羽庇荫',detail:'为全体存活队友恢复74点生命。',quote:'羽翼之下，皆为归人。',story:'他守着商队途经的每一片绿洲，用翠色羽翼为伤者遮荫。旅人们说，看见他的羽光，就等于看见了活水。'},
    {id:'sirius',rarity:'UR',art:'sirius-v11',sheet:'comet',index:4,name:'西里乌斯',title:'天狼星君',english:'SIRIUS',role:'群攻 · 神佑',hp:395,atk:90,cost:4,kind:'solar',power:178,fx:'solar',color:'#ffd98f',ultimate:true,skill:'天狼巡夜',detail:'全体敌人受到178点伤害，全体队友获得65点护盾。每场战斗限用一次。',quote:'长夜再深，也深不过我的巡行。',story:'他是彗轨尽头最亮的守望者，以天狼之名巡视每一道星门。凡他光芒所及之处，迷途者皆能找到归途。'}
  );
  entries.push(
    {id:'moss',rarity:'N',art:'moss-v11',sheet:'nebula',index:0,name:'莫斯',title:'苔原拾荒',english:'MOSS',role:'治疗 · 支援',hp:295,atk:41,cost:1,kind:'heal',power:105,fx:'heal',color:'#9ed6a0',skill:'苔衣裹伤',detail:'为生命比例最低的存活队友恢复105点生命。',quote:'星尘落进土里，也会长出苔藓。',story:'他在星云坠落的废土上捡拾残光，把每一寸绿意都当作奇迹供养。药囊里的苔草，救过整支拾荒队。'},
    {id:'mistral',rarity:'R',art:'mistral-v11',sheet:'nebula',index:1,name:'米斯特拉',title:'雾笛乐手',english:'MISTRAL',role:'冰冻 · 控制',hp:305,atk:58,cost:2,kind:'freeze',power:86,fx:'ice',color:'#a9d9f2',skill:'雾笛凝霜',detail:'造成86点伤害并冰冻目标，使其跳过下一次攻击。',quote:'听完这支曲子，你就睡着了。',story:'星云深处的雾笛声能令水汽瞬间结霜。她吹奏的摇篮曲，连风暴都会安静下来。'},
    {id:'cinder',rarity:'SR',art:'cinder-v11',sheet:'nebula',index:2,name:'辛德',title:'灰烬行者',english:'CINDER',role:'贯穿 · 输出',hp:340,atk:75,cost:2,kind:'pierce',power:126,fx:'arrow',color:'#ff9d76',skill:'余烬穿行',detail:'对主目标造成126点伤害，对另一名存活敌人造成50点伤害。',quote:'我走过的路，灰都是热的。',story:'他从星云燃烧的残骸中走出，披风上落满不会熄灭的余烬。没有人知道他要去哪里，只知他身后从无追兵。'},
    {id:'nyx',rarity:'SSR',art:'nyx-v11',sheet:'nebula',index:3,name:'妮克丝',title:'暮色织者',english:'NYX',role:'吸血 · 收割',hp:370,atk:81,cost:2,kind:'drain',power:152,fx:'drain',color:'#e08bb0',skill:'暮色抽丝',detail:'造成152点伤害，恢复实际伤害量50%的自身生命。',quote:'黄昏是我织出的第一匹布。',story:'她在昼夜交界处织幕，以暮色为线、以星光为梭。被她的丝线缠住的人，会在梦里交出体力。'},
    {id:'vega',rarity:'UR',art:'vega-v11',sheet:'nebula',index:4,name:'维加',title:'织女星君',english:'VEGA',role:'领域 · 爆发',hp:355,atk:88,cost:4,kind:'astral',power:150,fx:'astral',color:'#cfa8ff',ultimate:true,skill:'织星成幕',detail:'对全体敌人造成150点伤害，开启两回合星蚀领域：每位队友每回合首次攻击附加25点伤害。每场限一次。',quote:'整片星云，都是我未织完的布。',story:'她与对岸的星君隔着银河相望千年，把思念织成覆盖战场的星幕。幕落之处，同伴的每一次出手都带着她的光。'}
  );
  entries.push(
    {id:'tam',rarity:'N',art:'tam-v11',sheet:'pulsar',index:0,name:'塔姆',title:'雷矿背夫',english:'TAM',role:'连击 · 输出',hp:300,atk:48,cost:1,kind:'double',power:38,fx:'bolt',color:'#e6c37f',skill:'双锤敲雷',detail:'对同一目标连续造成两次38点伤害。',quote:'矿脉会说话，用雷声。',story:'脉冲星矿坑里最年轻的背夫，用两把铁锤敲出雷音辨矿。他说雷声越响的地方，星晶越纯。'},
    {id:'sela',rarity:'R',art:'sela-v11',sheet:'pulsar',index:1,name:'瑟拉',title:'电弧信使',english:'SELA',role:'标记 · 协击',hp:295,atk:59,cost:1,kind:'mark',power:46,fx:'bolt',color:'#d8c6ff',skill:'弧光签收',detail:'造成46点伤害并标记目标，使下一次攻击伤害提高25%。',quote:'闪电签收，概不退件。',story:'她沿着脉冲星的节拍奔行，把电光折成信笺的形状。被她标记的目标，等于签收了下一道雷。'},
    {id:'bront',rarity:'SR',art:'bront-v11',sheet:'pulsar',index:2,name:'布朗特',title:'雷臼锻师',english:'BRONT',role:'群攻 · 重装',hp:400,atk:70,cost:2,kind:'storm',power:92,fx:'lightning',color:'#b7a8ff',skill:'雷臼震落',detail:'对全体敌人造成92点伤害，并为自身赋予90点护盾。',quote:'锻打星铁，要用整场雷雨。',story:'他把脉冲星引到锻炉上方，以雷为锤、以云为砧。每一次落锤，矿坑里都会亮起一圈电光。'},
    {id:'fula',rarity:'SSR',art:'fula-v11',sheet:'pulsar',index:3,name:'芙拉',title:'弧光裁判',english:'FULA',role:'贯穿 · 猎手',hp:390,atk:79,cost:3,kind:'pierce',power:142,fx:'lightning',color:'#cdd6ff',skill:'弧光裁决',detail:'对主目标造成142点伤害，对另一名存活敌人造成50点伤害。',quote:'电荷不会说谎。',story:'星庭的电光裁判，手持一杆能称量罪责的雷矛。矛尖所指，弧光会自行选出第二个有罪者。'},
    {id:'astreus',rarity:'UR',art:'astreus-v11',sheet:'pulsar',index:4,name:'阿斯特鲁',title:'雷枢星君',english:'ASTREUS',role:'时停 · 群控',hp:360,atk:89,cost:4,kind:'time',power:138,fx:'time',color:'#c4b4ff',ultimate:true,skill:'雷枢定刻',detail:'对全体敌人造成138点伤害并冰冻，使其跳过下一次攻击。每场战斗限用一次。',quote:'钟摆停下的那一刻，雷仍记得方向。',story:'他掌管脉冲星的节拍，也掌管群星共用的那口钟。当他按住钟摆，整片星空的雷光都会悬停在半空。'}
  );
  entries.push(
    {id:'lumit',rarity:'N',art:'lumit-v11',sheet:'quasar',index:0,name:'露米特',title:'烛芯学徒',english:'LUMIT',role:'治疗 · 支援',hp:285,atk:42,cost:1,kind:'heal',power:108,fx:'heal',color:'#f2d9a0',skill:'续烛微光',detail:'为生命比例最低的存活队友恢复108点生命。',quote:'烛芯没断，就还能亮。',story:'类星体观测塔的守烛学徒，每晚为三百盏星灯续芯。她相信每一簇火苗里，都住着一位归人。'},
    {id:'gale',rarity:'R',art:'gale-v11',sheet:'quasar',index:1,name:'盖尔',title:'疾风邮差',english:'GALE',role:'连击 · 输出',hp:290,atk:52,cost:1,kind:'double',power:44,fx:'bolt',color:'#bfe3d0',skill:'双程投递',detail:'对同一目标连续造成两次44点伤害。',quote:'一封送过去，一封送回来。',story:'他骑着类星体喷流送件，一天往返两个星区。收件人说，他的拳头和信件一样准时。'},
    {id:'sable',rarity:'SR',art:'sable-v11',sheet:'quasar',index:2,name:'萨布尔',title:'影缝猎手',english:'SABLE',role:'吸血 · 收割',hp:335,atk:76,cost:2,kind:'drain',power:128,fx:'drain',color:'#b48fd6',skill:'影缝收线',detail:'造成128点伤害，恢复实际伤害量50%的自身生命。',quote:'影子缝好了，就别想逃。',story:'她用类星体的暗面作线，把猎物的影子缝在自己的披风上。线收之时，力气也随之流走。'},
    {id:'eos',rarity:'SSR',art:'eos-v11',sheet:'quasar',index:3,name:'厄俄斯',title:'晨光执礼',english:'EOS',role:'群疗 · 护佑',hp:378,atk:58,cost:3,kind:'renew',power:92,fx:'heal',color:'#ffe2b0',skill:'晨礼普照',detail:'全体存活队友恢复92点生命，并获得40点护盾，持续两个敌方回合。',quote:'黎明是一场需要提前排练的仪式。',story:'她每天第一个登上类星体顶端，为尚未升起的晨光执礼。礼成之时，伤者会感到伤口微微发暖。'},
    {id:'solara',rarity:'UR',art:'solara-v11',sheet:'quasar',index:4,name:'索拉拉',title:'曜辉星君',english:'SOLARA',role:'群攻 · 回生',hp:400,atk:92,cost:4,kind:'nova',power:182,fx:'solar',color:'#ffe08a',ultimate:true,skill:'曜辉复燃',detail:'对全体敌人造成182点伤害，为全体存活队友恢复60点生命。每场限用一次。',quote:'熄灭的星，由我来点第二次。',story:'她收集所有濒死恒星的最后一闪，把它们重新点燃成曜辉。战场上的同伴说，她的光落下来时，伤口会自己合拢。'}
  );
  entries.push(
    {id:'bram',rarity:'N',art:'bram-v11',sheet:'zenith',index:0,name:'布拉姆',title:'星轨测量',english:'BRAM',role:'护盾 · 前卫',hp:350,atk:42,cost:1,kind:'shieldOne',power:100,fx:'shield',color:'#cbb490',skill:'标尺遮护',detail:'为生命比例最低的存活队友赋予100点护盾，持续两个敌方回合。',quote:'误差半度，星轨就偏了一生。',story:'他背着测量仪爬过每一座天顶台，用盾面反射星光读数。队友说，站在他尺线里的人最安全。'},
    {id:'iris',rarity:'R',art:'iris-v11',sheet:'zenith',index:1,name:'伊丽丝',title:'虹膜记录',english:'IRIS',role:'治疗 · 护持',hp:310,atk:56,cost:2,kind:'tide',power:84,fx:'tide',color:'#9fe8e0',skill:'虹光归档',detail:'治疗生命比例最低的队友84点，并为全队赋予35点护盾。',quote:'每一次伤痛，都值得被好好记录。',story:'她把伤者的脉象折进虹光胶片，按星历归档。治疗结束前，她总会多留一层光膜，防止伤口在夜里裂开。'},
    {id:'ferro',rarity:'SR',art:'ferro-v11',sheet:'zenith',index:2,name:'费罗',title:'铁律守卫',english:'FERRO',role:'护盾 · 反击',hp:395,atk:66,cost:2,kind:'shieldAll',power:88,fx:'shield',color:'#b9c4d6',skill:'铁律列阵',detail:'为全体存活队友赋予88点护盾；持续两个敌方回合。',quote:'条例第一条：谁都别想过去。',story:'天顶关的铁律守卫，盾上刻着全部关防条例。他列阵时，连风都要按他的规矩绕行。'},
    {id:'mira',rarity:'SSR',art:'mira-v11',sheet:'zenith',index:3,name:'米拉',title:'变星占者',english:'MIRA',role:'群攻 · 重装',hp:405,atk:77,cost:3,kind:'storm',power:98,fx:'lightning',color:'#a9b8ff',skill:'变星暴奏',detail:'对全体敌人造成98点伤害，并为自身赋予90点护盾。',quote:'我的亮度，从不恒定。',story:'她是一颗会呼吸的变星化为人形，亮度随情绪涨落。暴奏之时，整片天顶都会被她的光压笼罩。'},
    {id:'suzu',rarity:'N',art:'suzu-v11',sheet:'zenith',index:4,name:'苏祖',title:'铃锤见习',english:'SUZU',role:'连击 · 输出',hp:288,atk:47,cost:1,kind:'double',power:38,fx:'bolt',color:'#e8cf9a',skill:'铃锤两响',detail:'对同一目标连续造成两次38点伤害。',quote:'第一响叫醒你，第二响送你走。',story:'天顶工坊的见习铃锤匠，敲钟也敲人。她坚信所有问题都能用两锤解决，一锤不行就再来一锤。'}
  );
  entries.push(
    {id:'dune',rarity:'N',art:'dune-v11',sheet:'horizon',index:0,name:'杜恩',title:'沙丘向导',english:'DUNE',role:'标记 · 协击',hp:305,atk:45,cost:1,kind:'mark',power:42,fx:'arrow',color:'#d8c090',skill:'沙径指认',detail:'造成42点伤害并标记目标，使下一次攻击伤害提高25%。',quote:'跟着我的脚印，别踩影子。',story:'地平线沙海的向导，能凭一粒沙认出来路。被他指认过的目标，会在沙暴里格外显眼。'},
    {id:'coral',rarity:'R',art:'coral-v11',sheet:'horizon',index:1,name:'科拉尔',title:'珊瑚牧者',english:'CORAL',role:'群疗 · 支援',hp:300,atk:48,cost:2,kind:'healAll',power:62,fx:'heal',color:'#9fe0cf',skill:'珊瑚抚潮',detail:'为全体存活队友恢复62点生命。',quote:'礁盘会记住每一道浪的脾气。',story:'她在退潮的星礁上放牧珊瑚，把治愈的微粒养进枝杈。浪来时，整片礁盘会泛起安抚的暖光。'},
    {id:'petra',rarity:'SR',art:'petra-v11',sheet:'horizon',index:2,name:'佩特拉',title:'岩脉筑者',english:'PETRA',role:'护盾 · 前卫',hp:370,atk:64,cost:2,kind:'shieldOne',power:105,fx:'shield',color:'#d0b8a0',skill:'岩脉立壁',detail:'为生命比例最低的存活队友赋予105点护盾，持续两个敌方回合。',quote:'墙立起来的那一刻，家就在墙后。',story:'她沿着地平线筑墙，把岩脉唤作兄弟。她立的壁从不修第二次，因为第一次就足够厚。'},
    {id:'maris',rarity:'SSR',art:'maris-v11',sheet:'horizon',index:3,name:'马里斯',title:'深海领航',english:'MARIS',role:'冰冻 · 控制',hp:385,atk:78,cost:3,kind:'freeze',power:96,fx:'ice',color:'#8fd4f2',skill:'深海定针',detail:'造成96点伤害并冰冻目标，使其跳过下一次攻击。',quote:'罗盘失灵时，听冰的声音。',story:'他领航过所有沉没的航线，罗盘针是一枚不化的深海冰。冰针所指之处，连时间都会结霜停步。'},
    {id:'fen',rarity:'N',art:'fen-v11',sheet:'horizon',index:4,name:'芬',title:'泽火守灯',english:'FEN',role:'灼烧 · 输出',hp:292,atk:49,cost:1,kind:'burn',power:100,fx:'fire',color:'#ffb08a',skill:'泽火燎原',detail:'造成100点伤害，附加两次35点灼烧。',quote:'沼泽里的火，比谁都倔强。',story:'她守着泽地边缘的一盏火灯，用蓝焰驱散夜雾。灯芯燃尽时，她就把火种抛向敌人。'}
  );
  entries.push(
    {id:'hana',rarity:'N',art:'hana-v11',sheet:'solstice',index:0,name:'哈娜',title:'至日花匠',english:'HANA',role:'治疗 · 支援',hp:290,atk:43,cost:1,kind:'heal',power:102,fx:'heal',color:'#cfe8a8',skill:'至日催花',detail:'为生命比例最低的存活队友恢复102点生命。',quote:'昼最长的那天，花也开得最急。',story:'她只在至日播种，让花在一夜之间开满祭坛。花瓣敷上伤口时，会留下太阳的味道。'},
    {id:'boreal',rarity:'R',art:'boreal-v11',sheet:'solstice',index:1,name:'玻瑞尔',title:'极辉猎手',english:'BOREAL',role:'冰冻 · 控制',hp:308,atk:60,cost:2,kind:'freeze',power:90,fx:'ice',color:'#a8e4f0',skill:'极辉凝滞',detail:'造成90点伤害并冰冻目标，使其跳过下一次攻击。',quote:'极光出现时，别眨眼，也别动。',story:'他追着极辉跑遍高纬星域，箭簇上镀着一层不会融的光。被极辉凝滞的猎物，会在原地站成一座冰雕。'},
    {id:'solis',rarity:'SR',art:'solis-v11',sheet:'solstice',index:2,name:'索利斯',title:'日轮祭司',english:'SOLIS',role:'灼烧 · 输出',hp:345,atk:77,cost:2,kind:'burn',power:122,fx:'fire',color:'#ffc07a',skill:'日轮焚祝',detail:'造成122点伤害，附加两次35点灼烧。',quote:'太阳不需要信徒，它只需要柴。',story:'至日祭坛最后的祭司，把祷词刻在日轮边缘。他点燃的不是香，是一整年的日照。'},
    {id:'helia',rarity:'SSR',art:'helia-v11',sheet:'solstice',index:3,name:'赫莉亚',title:'昼冠圣女',english:'HELIA',role:'群疗 · 护佑',hp:376,atk:57,cost:3,kind:'renew',power:88,fx:'heal',color:'#ffe8b8',skill:'昼冠加护',detail:'全体存活队友恢复88点生命，并获得40点护盾，持续两个敌方回合。',quote:'白昼是我替你们借来的。',story:'她头戴由正午光斑编成的昼冠，替夜行者向太阳借光。冠冕亮起时，伤口会像晨露一样蒸发。'},
    {id:'kipp',rarity:'N',art:'kipp-v11',sheet:'solstice',index:4,name:'基普',title:'至日钟童',english:'KIPP',role:'连击 · 输出',hp:286,atk:46,cost:1,kind:'double',power:39,fx:'bolt',color:'#e2c58e',skill:'撞钟两声',detail:'对同一目标连续造成两次39点伤害。',quote:'昼钟一声，夜钟一声。',story:'他负责在至日敲响昼夜交替的钟，一手一槌从不出错。敲钟之外的时间，他用同一双槌练习打架。'}
  );
  entries.push(
    {id:'vera',rarity:'N',art:'vera-v11',sheet:'equinox',index:0,name:'维拉',title:'分点守秤',english:'VERA',role:'护盾 · 前卫',hp:335,atk:44,cost:1,kind:'shieldOne',power:92,fx:'shield',color:'#c8c0a8',skill:'衡秤遮护',detail:'为生命比例最低的存活队友赋予92点护盾，持续两个敌方回合。',quote:'昼夜均分，一丝都不能多。',story:'她在分点台守着那杆称量昼夜的秤，盾面就是秤盘。谁想打破平衡，先问过她的盾。'},
    {id:'lynx',rarity:'R',art:'lynx-v11',sheet:'equinox',index:1,name:'林克斯',title:'猞猁潜行',english:'LYNX',role:'贯穿 · 猎手',hp:312,atk:62,cost:2,kind:'pierce',power:116,fx:'arrow',color:'#c9d8a8',skill:'猞影穿林',detail:'对主目标造成116点伤害，对另一名存活敌人造成50点伤害。',quote:'你看见我的时候，已经晚了。',story:'分点林里的猞猁猎手，耳尖的绒羽能听见光的变化。他的箭总是先于脚步抵达。'},
    {id:'aeolus',rarity:'SR',art:'aeolus-v11',sheet:'equinox',index:2,name:'埃俄洛斯',title:'风袋执掌',english:'AEOLUS',role:'群攻 · 重装',hp:380,atk:68,cost:2,kind:'storm',power:90,fx:'lightning',color:'#b0d8e8',skill:'风袋开闸',detail:'对全体敌人造成90点伤害，并为自身赋予90点护盾。',quote:'风借出去，是要还的。',story:'他执掌装着四季风的风袋，按星历开闸放风。闸口失控的那些年，他学会用身体当第二道闸。'},
    {id:'themis',rarity:'SSR',art:'themis-v11',sheet:'equinox',index:3,name:'忒弥斯',title:'均衡裁决',english:'THEMIS',role:'吸血 · 收割',hp:388,atk:82,cost:3,kind:'drain',power:158,fx:'drain',color:'#d8a8c0',skill:'均衡抽偿',detail:'造成158点伤害，恢复实际伤害量50%的自身生命。',quote:'你拿走的，我会连本带利取回。',story:'分点法庭的裁决者，天平两端放着罪与偿。她的剑刃中空，流过的每一滴力都会回到她身上。'},
    {id:'odo',rarity:'N',art:'odo-v11',sheet:'equinox',index:4,name:'奥多',title:'昼夜更夫',english:'ODO',role:'治疗 · 支援',hp:298,atk:42,cost:1,kind:'heal',power:100,fx:'heal',color:'#b8d8c0',skill:'更漏回春',detail:'为生命比例最低的存活队友恢复100点生命。',quote:'天亮之前，我还会敲三次梆。',story:'他沿着分点线敲梆报时，把夜分成可以熬过去的段落。伤者听着他的梆声，就知道天还会亮。'}
  );
  entries.push(
    {id:'cassia',rarity:'N',art:'cassia-v11',sheet:'meridian',index:0,name:'卡西亚',title:'子午药商',english:'CASSIA',role:'群疗 · 支援',hp:296,atk:44,cost:1,kind:'healAll',power:58,fx:'heal',color:'#b8e0b0',skill:'桂香匀分',detail:'为全体存活队友恢复58点生命。',quote:'药要匀着卖，命要一起活。',story:'她沿着子午线贩药，秤杆上刻着二十四节星气。整队人的伤口，她一锅药汤就能抹平。'},
    {id:'rhoda',rarity:'R',art:'rhoda-v11',sheet:'meridian',index:1,name:'罗妲',title:'经线测绘',english:'RHODA',role:'标记 · 协击',hp:302,atk:56,cost:1,kind:'mark',power:45,fx:'arrow',color:'#d0e0a0',skill:'经线钉标',detail:'造成45点伤害并标记目标，使下一次攻击伤害提高25%。',quote:'地图上多一枚钉，路上少一次迷路。',story:'她把经线一根根钉进大地，用玫瑰色的标旗记里程。被她钉过标的目标，等于被写进了地图。'},
    {id:'cirus',rarity:'SR',art:'cirus-v11',sheet:'meridian',index:2,name:'西勒斯',title:'经线剑士',english:'CIRUS',role:'贯穿 · 输出',hp:350,atk:76,cost:2,kind:'pierce',power:130,fx:'arrow',color:'#b8c8e8',skill:'经线直斩',detail:'对主目标造成130点伤害，对另一名存活敌人造成50点伤害。',quote:'剑走直线，从不绕路。',story:'他的剑术只有一式：沿子午线直刺。剑光过境时，敌人的阵列会被犁出一道笔直的沟。'},
    {id:'vesna',rarity:'SSR',art:'vesna-v11',sheet:'meridian',index:3,name:'维斯娜',title:'春分信使',english:'VESNA',role:'群疗 · 护佑',hp:374,atk:58,cost:3,kind:'renew',power:90,fx:'heal',color:'#cfe8c0',skill:'春信遍递',detail:'全体存活队友恢复90点生命，并获得40点护盾，持续两个敌方回合。',quote:'春天的信，一封都不能少。',story:'她背着春分的信袋跨越子午线，把回暖的消息递到每道伤口手里。信到之处，草木与血肉一同苏醒。'},
    {id:'tarn',rarity:'R',art:'tarn-v11',sheet:'meridian',index:4,name:'塔恩',title:'湖镜渔火',english:'TARN',role:'冰冻 · 控制',hp:306,atk:57,cost:2,kind:'freeze',power:84,fx:'ice',color:'#9fd0e8',skill:'湖镜封澜',detail:'造成84点伤害并冰冻目标，使其跳过下一次攻击。',quote:'湖面一平，什么都藏不住。',story:'他在子午湖上点渔火，湖镜映出星轨也映出来敌。被他封住的澜波，会连人一起冻在倒影里。'}
  );
  entries.push(
    {id:'ario',rarity:'N',art:'ario-v11',sheet:'zodiac',index:0,name:'阿里奥',title:'星宫牧童',english:'ARIO',role:'护盾 · 前卫',hp:345,atk:43,cost:1,kind:'shieldOne',power:98,fx:'shield',color:'#d0bc98',skill:'牧圈遮护',detail:'为生命比例最低的存活队友赋予98点护盾，持续两个敌方回合。',quote:'圈里的羊，一只都不能少。',story:'他在星宫之间放牧流星的羊群，用牧鞭圈出安全的围栏。他的盾，就是那圈从不熄灭的星栅。'},
    {id:'libre',rarity:'R',art:'libre-v11',sheet:'zodiac',index:1,name:'利布尔',title:'天秤书记',english:'LIBRE',role:'标记 · 协击',hp:298,atk:55,cost:1,kind:'mark',power:43,fx:'arrow',color:'#e0d0a8',skill:'天秤记过',detail:'造成43点伤害并标记目标，使下一次攻击伤害提高25%。',quote:'罪与罚，都要记在账上。',story:'她替星宫法庭抄录判决，笔尖是一枚天秤砝码。被她记过一笔的目标，下一击会连利息一起偿还。'},
    {id:'skor',rarity:'SR',art:'skor-v11',sheet:'zodiac',index:2,name:'斯科',title:'蝎尾针使',english:'SKOR',role:'灼烧 · 输出',hp:338,atk:75,cost:2,kind:'burn',power:116,fx:'fire',color:'#ff9a80',skill:'蝎尾淬焰',detail:'造成116点伤害，附加两次35点灼烧。',quote:'我的针，只扎一次就够了。',story:'星宫蝎尾座的针使，毒囊里酿着恒星表面的焰尘。被他的尾针刺中者，伤口会自己烧起来。'},
    {id:'piscia',rarity:'SSR',art:'piscia-v11',sheet:'zodiac',index:3,name:'皮西亚',title:'双鱼潮汐',english:'PISCIA',role:'治疗 · 护持',hp:372,atk:59,cost:3,kind:'tide',power:88,fx:'tide',color:'#a0e8e8',skill:'双鱼衔潮',detail:'治疗生命比例最低的队友88点，并为全队赋予35点护盾。',quote:'两条鱼，衔着同一片海。',story:'她与孪生的星鱼共享一次呼吸，潮水在两人之间往返。她治疗时，队友会听见极轻的浪声。'},
    {id:'capri',rarity:'R',art:'capri-v11',sheet:'zodiac',index:4,name:'卡普里',title:'摩羯岩角',english:'CAPRI',role:'连击 · 输出',hp:310,atk:54,cost:2,kind:'double',power:42,fx:'bolt',color:'#d8c8a0',skill:'岩角双顶',detail:'对同一目标连续造成两次42点伤害。',quote:'上山的路，用角开。',story:'他沿着星宫的崖壁攀行，岩角磨得比刀还亮。顶人两下是他的问候方式，也是他的战斗方式。'}
  );
  entries.push(
    {id:'vele',rarity:'N',art:'vele-v11',sheet:'umbra',index:0,name:'维莱',title:'影灯提灯',english:'VELE',role:'治疗 · 支援',hp:294,atk:42,cost:1,kind:'heal',power:104,fx:'heal',color:'#b0c8b8',skill:'影灯照隙',detail:'为生命比例最低的存活队友恢复104点生命。',quote:'影子越深，灯越要亮。',story:'他提着影灯走在星界的暗面，专门照亮别人不敢看的缝隙。灯光落处，伤口会慢慢合拢。'},
    {id:'corvus',rarity:'R',art:'corvus-v11',sheet:'umbra',index:1,name:'科沃斯',title:'鸦羽密使',english:'CORVUS',role:'贯穿 · 猎手',hp:314,atk:61,cost:2,kind:'pierce',power:118,fx:'arrow',color:'#a8b0c8',skill:'鸦羽穿幕',detail:'对主目标造成118点伤害，对另一名存活敌人造成50点伤害。',quote:'信已送到，命也送到。',story:'他为暗面诸宫传递密信，箭羽取自夜鸦的初翎。收信人往往在读完之前，就先读到了箭。'},
    {id:'moro',rarity:'SR',art:'moro-v11',sheet:'umbra',index:2,name:'莫罗',title:'蚀影盗贼',english:'MORO',role:'吸血 · 收割',hp:342,atk:74,cost:2,kind:'drain',power:124,fx:'drain',color:'#b890c8',skill:'蚀影摸囊',detail:'造成124点伤害，恢复实际伤害量50%的自身生命。',quote:'影子口袋里的东西，归我。',story:'他偷过日蚀、月蚀，最后开始偷力气。被他摸过影子的人，会莫名其妙地打一个哈欠。'},
    {id:'selkis',rarity:'SSR',art:'selkis-v11',sheet:'umbra',index:3,name:'塞尔基斯',title:'暗棺守夜',english:'SELKIS',role:'护盾 · 反击',hp:402,atk:72,cost:3,kind:'shieldAll',power:92,fx:'shield',color:'#98a8d0',skill:'暗棺合护',detail:'为全体存活队友赋予92点护盾；持续两个敌方回合。',quote:'棺盖之下，是我守的夜。',story:'她守着暗面最深处的星棺，盾面刻满守夜祷文。护盾碎裂的声响，就是她对入侵者的反击令。'},
    {id:'wisp',rarity:'R',art:'wisp-v11',sheet:'umbra',index:4,name:'威斯普',title:'影火游光',english:'WISP',role:'灼烧 · 输出',hp:296,atk:58,cost:1,kind:'burn',power:108,fx:'fire',color:'#d8a0f0',skill:'影火撩人',detail:'造成108点伤害，附加两次35点灼烧。',quote:'追我呀，追到就给你一点光。',story:'沼泽暗面的一团影火，喜欢引路也喜欢迷路的人。它燎过的地方，会留下一串紫色的笑。'}
  );
  entries.push(
    {id:'flint',rarity:'N',art:'flint-v11',sheet:'lumina',index:0,name:'弗林特',title:'火石点灯',english:'FLINT',role:'灼烧 · 输出',hp:290,atk:50,cost:1,kind:'burn',power:102,fx:'fire',color:'#ffb890',skill:'火石迸星',detail:'造成102点伤害，附加两次35点灼烧。',quote:'一下不行，就敲两下。',story:'他负责点亮光域边缘的第一盏灯，火石敲出的星屑能烧穿夜雾。灯亮之后，他才肯去敲人。'},
    {id:'aura',rarity:'R',art:'aura-v11',sheet:'lumina',index:1,name:'奥拉',title:'光晕织工',english:'AURA',role:'群疗 · 支援',hp:304,atk:47,cost:2,kind:'healAll',power:64,fx:'heal',color:'#f0e0b8',skill:'光晕匀织',detail:'为全体存活队友恢复64点生命。',quote:'光要织得匀，才照得远。',story:'她把光晕抽成丝，在织机上排成暖色的布。披过她织光的人，伤口会像被太阳晒过一样发暖。'},
    {id:'luce',rarity:'SR',art:'luce-v11',sheet:'lumina',index:2,name:'卢切',title:'棱光折师',english:'LUCE',role:'冰冻 · 控制',hp:336,atk:71,cost:2,kind:'freeze',power:92,fx:'ice',color:'#c8e8f8',skill:'棱光折停',detail:'造成92点伤害并冰冻目标，使其跳过下一次攻击。',quote:'光折七次，就会停下来休息。',story:'他掌握着让光减速折返的棱镜术，第七次折射时，光会凝成冰。被凝住的人，会看见自己慢下来的影子。'},
    {id:'aurora',rarity:'SSR',art:'aurora-v11',sheet:'lumina',index:3,name:'奥萝拉',title:'极辉女爵',english:'AURORA',role:'群攻 · 重装',hp:392,atk:76,cost:3,kind:'storm',power:96,fx:'lightning',color:'#b8e0f8',skill:'极辉垂幕',detail:'对全体敌人造成96点伤害，并为自身赋予90点护盾。',quote:'天幕垂落时，请抬头。',story:'光域的女爵，裙摆是整片极辉。她垂幕之时，敌人在光里迷失方向，而她在光里筑起自己的城。'},
    {id:'lumen',rarity:'R',art:'lumen-v11',sheet:'lumina',index:4,name:'卢门',title:'流明执烛',english:'LUMEN',role:'治疗 · 支援',hp:300,atk:46,cost:1,kind:'heal',power:88,fx:'heal',color:'#f8e8c0',skill:'流明递烛',detail:'为生命比例最低的存活队友恢复88点生命。',quote:'烛火递出去，就不会灭。',story:'他执着一支按流明计量的烛，为光域守夜。递烛给伤者时，烛芯会分出一小簇，留在对方胸口。'}
  );
  entries.push(
    {id:'garde',rarity:'N',art:'garde-v11',sheet:'aegis',index:0,name:'加德',title:'城壁见习',english:'GARDE',role:'护盾 · 前卫',hp:352,atk:43,cost:1,kind:'shieldOne',power:104,fx:'shield',color:'#c0b8a8',skill:'见习立壁',detail:'为生命比例最低的存活队友赋予104点护盾，持续两个敌方回合。',quote:'墙在，人在。',story:'城壁兵团最年轻的见习盾手，站姿还不够稳，盾却举得比谁都直。老兵说，他的盾迟早会替整座城市挡下一次日落。'},
    {id:'velli',rarity:'R',art:'velli-v11',sheet:'aegis',index:1,name:'维莉',title:'盾纹刻师',english:'VELLI',role:'护盾 · 前卫',hp:315,atk:50,cost:2,kind:'shieldOne',power:90,fx:'shield',color:'#c8d0d8',skill:'盾纹铭刻',detail:'为生命比例最低的存活队友赋予90点护盾，持续两个敌方回合。',quote:'刻上名字，盾就认主。',story:'她为每一面出征的盾刻上持有者的名字与家训。被铭刻过的盾，会在主人最危险时多撑一刻。'},
    {id:'egide',rarity:'SR',art:'egide-v11',sheet:'aegis',index:2,name:'埃吉德',title:'圣盾执事',english:'EGIDE',role:'护盾 · 反击',hp:360,atk:62,cost:2,kind:'shieldAll',power:84,fx:'shield',color:'#b0c0e0',skill:'圣盾列祷',detail:'为全体存活队友赋予84点护盾；持续两个敌方回合。',quote:'祷词念完之前，盾不会倒。',story:'圣盾厅的执事，掌管着历代骑士归还的盾。他列祷时，所有盾面会同时亮起旧主人的纹章。'},
    {id:'vallum',rarity:'SSR',art:'vallum-v11',sheet:'aegis',index:3,name:'瓦卢姆',title:'壁垒将军',english:'VALLUM',role:'群攻 · 重装',hp:408,atk:75,cost:3,kind:'storm',power:94,fx:'lightning',color:'#c0c8e0',skill:'壁垒推进',detail:'对全体敌人造成94点伤害，并为自身赋予90点护盾。',quote:'我的推进线，就是国境线。',story:'他一生只打过一种仗：向前推进。壁垒随他的脚步生长，敌人退到哪里，他的盾就压到哪里。'},
    {id:'rikka',rarity:'SR',art:'rikka-v11',sheet:'aegis',index:4,name:'里卡',title:'六分仪卫',english:'RIKKA',role:'标记 · 协击',hp:332,atk:70,cost:2,kind:'mark',power:52,fx:'arrow',color:'#d0d8b0',skill:'六分锁定',detail:'造成52点伤害并标记目标，使下一次攻击伤害提高25%。',quote:'角度对了，距离就不算远。',story:'她用六分仪为全军校准射角，误差从不超过一分。被她锁定的目标，会同时出现在所有弓弦的延长线上。'}
  );
  entries.push(
    {id:'brook',rarity:'N',art:'brook-v11',sheet:'cascade',index:0,name:'布鲁克',title:'溪涧背水',english:'BROOK',role:'治疗 · 支援',hp:292,atk:42,cost:1,kind:'heal',power:106,fx:'heal',color:'#a8d8d0',skill:'溪涧润伤',detail:'为生命比例最低的存活队友恢复106点生命。',quote:'水不大，但一直流。',story:'他每天从星瀑源头背水下山，壶里的水能洗去疲惫也洗去伤痛。队伍里谁累了，就先喝一口。'},
    {id:'falla',rarity:'R',art:'falla-v11',sheet:'cascade',index:1,name:'法拉',title:'瀑声歌者',english:'FALLA',role:'群疗 · 支援',hp:302,atk:47,cost:2,kind:'healAll',power:66,fx:'heal',color:'#98e0d8',skill:'瀑声合唱',detail:'为全体存活队友恢复66点生命。',quote:'瀑布的歌，要大家一起听。',story:'她站在星瀑之下练声，把水声编成合唱。歌声漫过之处，伤口会跟着水雾一起变轻。'},
    {id:'undine',rarity:'SR',art:'undine-v11',sheet:'cascade',index:2,name:'温蒂妮',title:'涌泉剑姬',english:'UNDINE',role:'贯穿 · 输出',hp:344,atk:76,cost:2,kind:'pierce',power:128,fx:'tide',color:'#90d8e8',skill:'涌泉突',detail:'对主目标造成128点伤害，对另一名存活敌人造成50点伤害。',quote:'泉眼一开，剑就跟着水走。',story:'她的剑法源自涌泉：起势无声，出鞘时已是满溢的水线。被她的剑泉穿过的人，会听见自己心里的水声。'},
    {id:'deluge',rarity:'SSR',art:'deluge-v11',sheet:'cascade',index:3,name:'德卢格',title:'洪峰执秤',english:'DELUGE',role:'冰冻 · 控制',hp:386,atk:78,cost:3,kind:'freeze',power:98,fx:'ice',color:'#88c8f0',skill:'洪峰压境',detail:'造成98点伤害并冰冻目标，使其跳过下一次攻击。',quote:'洪峰过境，万物屏息。',story:'他执掌星瀑的洪峰刻度，决定哪一年放水、哪一年封冻。被他压境的敌人，会连呼吸一起被冻住。'},
    {id:'vapor',rarity:'SR',art:'vapor-v11',sheet:'cascade',index:4,name:'瓦珀',title:'雾刃潜行',english:'VAPOR',role:'吸血 · 收割',hp:334,atk:73,cost:2,kind:'drain',power:122,fx:'drain',color:'#b0d0e0',skill:'雾刃抽雾',detail:'造成122点伤害，恢复实际伤害量50%的自身生命。',quote:'雾散的时候，你已经无力了。',story:'他把刃藏在瀑雾里，连水汽都是他的眼线。刃过之处，雾气会悄悄吸走对手的力气，再还给他。'}
  );
  entries.push(
    {id:'yume',rarity:'N',art:'yume-v11',sheet:'reverie',index:0,name:'尤梅',title:'梦壤园丁',english:'YUME',role:'治疗 · 支援',hp:288,atk:42,cost:1,kind:'heal',power:103,fx:'heal',color:'#c8b8e0',skill:'梦壤培元',detail:'为生命比例最低的存活队友恢复103点生命。',quote:'好梦是最好的药。',story:'她在梦壤里种下安眠的种子，收获时结出一枚枚温热的梦。把梦敷在额头上，伤痛会退成背景。'},
    {id:'lull',rarity:'R',art:'lull-v11',sheet:'reverie',index:1,name:'拉尔',title:'摇篮曲使',english:'LULL',role:'冰冻 · 控制',hp:304,atk:58,cost:2,kind:'freeze',power:87,fx:'ice',color:'#b8c0e8',skill:'摇篮低吟',detail:'造成87点伤害并冰冻目标，使其跳过下一次攻击。',quote:'睡吧，醒来就打完了。',story:'他背着摇篮走遍战场边缘，为无法入睡的人唱曲。敌人听着听着，就会站在原地睡过去。'},
    {id:'oneira',rarity:'SR',art:'oneira-v11',sheet:'reverie',index:2,name:'奥涅拉',title:'梦占师',english:'ONEIRA',role:'群攻 · 重装',hp:356,atk:69,cost:2,kind:'storm',power:91,fx:'lightning',color:'#c0a8e8',skill:'梦兆风暴',detail:'对全体敌人造成91点伤害，并为自身赋予90点护盾。',quote:'梦里的风暴，也会淋湿现实。',story:'她解读星界的梦兆，也把噩梦放归战场。风暴来临前，敌人会先梦见自己被打败的样子。'},
    {id:'somnus',rarity:'SSR',art:'somnus-v11',sheet:'reverie',index:3,name:'索姆努斯',title:'眠宫守钥',english:'SOMNUS',role:'冰冻 · 控制',hp:384,atk:77,cost:3,kind:'freeze',power:97,fx:'ice',color:'#a8b0e8',skill:'眠宫落锁',detail:'造成97点伤害并冰冻目标，使其跳过下一次攻击。',quote:'钥匙在我手里，梦就在我手里。',story:'眠宫的一千零一把钥匙挂在他腰间，每一把锁着一位失眠的古神。他落锁之时，战场也会跟着入眠。'},
    {id:'somnia',rarity:'SR',art:'somnia-v11',sheet:'reverie',index:4,name:'索姆妮亚',title:'梦织女',english:'SOMNIA',role:'治疗 · 护持',hp:340,atk:64,cost:2,kind:'tide',power:86,fx:'tide',color:'#c8b8f0',skill:'梦线缠护',detail:'治疗生命比例最低的队友86点，并为全队赋予35点护盾。',quote:'梦的线头，我替你攥着。',story:'她把每个人的梦织成同一匹布，线头攥在手心。队友受伤时，她会轻轻拉一下线，把痛感织进梦里稀释。'}
  );
  entries.push(
    {id:'castor',rarity:'SSR',art:'castor-v11',sheet:'binary',index:0,name:'卡斯托',title:'双辉兄星',english:'CASTOR',role:'连击 · 输出',hp:368,atk:80,cost:3,kind:'double',power:78,fx:'bolt',color:'#e8d0a0',skill:'双辉连击',detail:'对同一目标连续造成两次78点伤害。',quote:'弟弟数到二，我就出手。',story:'双星系统中的兄星，掌管第一拍的光。他与弟弟共用一次呼吸、一套剑谱，出手永远是成对的。'},
    {id:'pollux',rarity:'SSR',art:'pollux-v11',sheet:'binary',index:1,name:'波吕克斯',title:'双辉弟星',english:'POLLUX',role:'贯穿 · 猎手',hp:382,atk:83,cost:3,kind:'pierce',power:146,fx:'bolt',color:'#d8c0f0',skill:'双辉贯日',detail:'对主目标造成146点伤害，对另一名存活敌人造成50点伤害。',quote:'哥哥数到一，我已经到了。',story:'双星系统中的弟星，掌管第二拍的光。他的贯击总是跟在兄星之后半瞬，却往往先抵达终点。'}
  );
  if(typeof module!=='undefined'&&module.exports)module.exports=entries;else root.EclipseRoster=entries;
})(typeof globalThis!=='undefined'?globalThis:this);
