(function(root){
  const entries = [
    {id:'bran',rarity:'N',sheet:'dawn',index:0,name:'布兰',title:'锈盾守卫',english:'BRAN',role:'护盾 · 前卫',hp:360,atk:42,cost:1,kind:'shieldOne',power:100,fx:'shield',color:'#dfbf87',skill:'旧盾新誓',detail:'为生命比例最低的存活队友赋予100点护盾，持续两个敌方回合。',quote:'旧盾还能挡住风雨。',story:'港口的最后一班岗，他已经守了十年。盾上的每一道裂纹，都记着一次平安归来。'},
    {id:'flora',rarity:'R',sheet:'dawn',index:1,name:'芙萝拉',title:'苔光药师',english:'FLORA',role:'群疗 · 支援',hp:290,atk:46,cost:2,kind:'healAll',power:65,fx:'heal',color:'#89e5b5',skill:'春息药雨',detail:'为全体存活队友恢复65点生命。',quote:'废墟里，也会开出第一朵花。',story:'她把药草种在坠落的星石上。青绿色的微光，是伤者在漫漫长夜里最熟悉的慰藉。'},
    {id:'nix',rarity:'SR',sheet:'dawn',index:2,name:'凛鸦',title:'霜羽猎手',english:'NIX',role:'冰冻 · 控制',hp:310,atk:73,cost:2,kind:'freeze',power:100,fx:'ice',color:'#89d8ff',skill:'寒鸦封缄',detail:'造成100点伤害并冰冻目标，使其跳过下一次攻击。已冰冻目标不会叠加次数。',quote:'听，雪落下之前，箭已经到了。',story:'雪原孤塔的猎手，将名字交给了冰霜。他的箭从不迷路，因为寒鸦早已看见终点。'},
    {id:'vesper',rarity:'SSR',sheet:'dawn',index:3,name:'维斯珀',title:'血蔷薇公爵',english:'VESPER',role:'吸血 · 收割',hp:360,atk:83,cost:2,kind:'drain',power:155,fx:'drain',color:'#f18eaa',skill:'夜宴终曲',detail:'造成155点伤害，恢复实际伤害量50%的自身生命。',quote:'请留下最后一支舞。',story:'沉睡王城的宴会从未散场。他以蔷薇封存伤痕，却始终记得晨光的温度。'},
    {id:'aurelia',rarity:'UR',sheet:'dawn',index:4,name:'奥蕾莉娅',title:'曜龙女帝',english:'AURELIA',role:'群攻 · 神佑',hp:390,atk:89,cost:4,kind:'solar',power:175,fx:'solar',color:'#ffdc87',ultimate:true,skill:'万曜龙临',detail:'全体敌人受到175点伤害，全体队友获得65点护盾。每场战斗限用一次。',quote:'太阳未至，我便是黎明。',story:'她与最后一条曜龙共享心跳。每当金色龙翼展开，世间便多出一寸不被日蚀吞没的光。'},
    {id:'finch',rarity:'N',sheet:'dusk',index:0,name:'菲妮',title:'发条学徒',english:'FINCH',role:'连击 · 输出',hp:285,atk:48,cost:1,kind:'double',power:38,fx:'bolt',color:'#e8c694',skill:'双拍校时',detail:'对同一目标连续造成两次38点伤害。',quote:'修好钟，就能找回明天吧？',story:'她修理一切停下的东西，从老钟到迷途的机械鸟。唯独天空那只大钟，她还在寻找发条。'},
    {id:'quill',rarity:'R',sheet:'dusk',index:1,name:'奎尔',title:'沙羽游侠',english:'QUILL',role:'贯穿 · 猎手',hp:315,atk:63,cost:2,kind:'pierce',power:120,fx:'arrow',color:'#b8d8be',skill:'流沙穿星',detail:'对主目标造成120点伤害，对另一名存活敌人造成50点伤害。',quote:'沙会抹去足迹，风会记住。',story:'沙海的向导独自背负一张没有终点的地图。他将羽毛系在箭尾，作为每个绿洲的路标。'},
    {id:'lyra',rarity:'SR',sheet:'dusk',index:2,name:'莉拉',title:'潮汐咏者',english:'LYRA',role:'治疗 · 护持',hp:325,atk:57,cost:2,kind:'tide',power:85,fx:'tide',color:'#82e4e7',skill:'沧海摇篮',detail:'治疗生命比例最低的队友85点，并为全队赋予35点护盾。',quote:'请让潮声，替你做一个好梦。',story:'海水淹没故乡之后，她从水下带回了一把竖琴。每一个音符，都是尚未说出口的告别。'},
    {id:'orion',rarity:'SSR',sheet:'dusk',index:3,name:'奥里昂',title:'雷誓圣骑',english:'ORION',role:'群攻 · 重装',hp:430,atk:69,cost:3,kind:'storm',power:95,fx:'lightning',color:'#b7acff',skill:'风暴裁庭',detail:'对全体敌人造成95点伤害，并为自身赋予90点护盾。',quote:'誓言，比雷霆先抵达。',story:'他在废弃钟楼上宣誓，以风暴为证。落下的雷光不是惩罚，而是他为旅人点亮的归途。'},
    {id:'noctis',rarity:'UR',sheet:'dusk',index:4,name:'诺克提斯',title:'永夜时君',english:'NOCTIS',role:'时停 · 群控',hp:350,atk:87,cost:4,kind:'time',power:135,fx:'time',color:'#ccb0ff',ultimate:true,skill:'零时星葬',detail:'对全体敌人造成135点伤害并冰冻，使其跳过下一次攻击。每场战斗限用一次。',quote:'这一秒，留给你。',story:'他走过所有已经失落的时间，却为一个约定停在此刻。碎裂的钟盘中，藏着无数未被选择的黎明。'}
  ];
  entries.push(
    {id:'tessa',rarity:'N',art:'tessa',index:0,name:'泰莎',title:'青灯行医',english:'TESSA',role:'治疗 · 支援',hp:305,atk:42,cost:1,kind:'heal',power:100,fx:'heal',color:'#91d6bb',skill:'旅途急救',detail:'为生命比例最低的存活队友恢复100点生命。',quote:'下一站，也一定有人等着我们。',story:'她背着药箱踏遍六域，把每一次日出记进随身的旅行手札。'},
    {id:'rune',rarity:'R',art:'rune',index:0,name:'卢恩',title:'霜图绘师',english:'RUNE',role:'冰冻 · 控制',hp:320,atk:56,cost:2,kind:'freeze',power:88,fx:'ice',color:'#93cafa',skill:'霜痕坐标',detail:'造成88点伤害并冰冻目标，使其跳过下一次攻击。',quote:'地图没有终点，只有尚未抵达的星。',story:'他用冰晶绘下天空的暗流，循着失落航路寻找风暴之上的故乡。'},
    {id:'ignis',rarity:'SR',art:'ignis',index:0,name:'伊格妮丝',title:'赤羽枪骑',english:'IGNIS',role:'贯穿 · 输出',hp:365,atk:76,cost:2,kind:'pierce',power:130,fx:'fire',color:'#ff9269',skill:'赤羽破阵',detail:'对主目标造成130点伤害，对另一名存活敌人造成50点伤害。',quote:'我会把前路，刺出一道晨光。',story:'最后一支赤羽骑兵的旗帜，仍在她的枪尖迎风燃烧。'},
    {id:'eirene',rarity:'SSR',art:'eirene',index:0,name:'伊蕾涅',title:'曙光圣女',english:'EIRENE',role:'群疗 · 护佑',hp:375,atk:58,cost:3,kind:'renew',power:90,fx:'heal',color:'#d0eec1',skill:'万物复苏',detail:'全体存活队友恢复90点生命，并获得40点护盾，持续两个敌方回合。',quote:'黑夜会过去，伤口也会。',story:'当圣域钟声沉寂，她以一朵永不凋零的百合，守着晨曦的归来。'},
    {id:'caelum',rarity:'UR',art:'caelum',index:0,name:'苍曜',title:'星龙天君',english:'CAELUM',role:'群攻 · 回生',hp:400,atk:92,cost:4,kind:'nova',power:180,fx:'solar',color:'#9fcaff',ultimate:true,skill:'六翼创生',detail:'对全体敌人造成180点伤害，为全体存活队友恢复60点生命。每场限用一次。',quote:'越过风暴，你会看见完整的天空。',story:'六翼星龙化为人形，带着破碎星空最后的祝福，自无尽天穹归来。'}
  );
  entries.push(
    {id:'seraphine',rarity:'SP',variant:'crimson',art:'seraphine-sp',name:'瑟拉菲娜',title:'绯月女皇',english:'SERAPHINE',role:'群攻 · 灼蚀',hp:460,atk:109,cost:4,kind:'crimson',power:230,fx:'fire',color:'#ff4569',ultimate:true,skill:'绯月敕令',detail:'全体敌人受到230点伤害，存活敌人附加两次55点灼烧。每场限用一次。',quote:'今夜，月亮只为你加冕。',story:'她以王冠封印绯月，在千年的静默中守住星界裂隙。唯有回应她的人，能看见猩红月光下尚未凋零的蔷薇。'},
    {id:'ragnar',rarity:'SP',variant:'crimson',art:'ragnar-sp',name:'拉格纳',title:'烬日君王',english:'RAGNAR',role:'群攻 · 守御',hp:540,atk:103,cost:4,kind:'ruin',power:210,fx:'solar',color:'#ff604d',ultimate:true,skill:'烬日王座',detail:'全体敌人受到210点伤害，全体存活队友获得120点护盾，持续两个敌方回合。每场限用一次。',quote:'余烬未冷，我的誓言便不会熄灭。',story:'当最后一轮太阳坠入深渊，他扛起破碎王座，将余火铸进巨剑。无人知晓，那看似毁灭的赤焰，一直在为万千生灵取暖。'},
    {id:'elysium',rarity:'SSP',variant:'prism',art:'elysium-sp',name:'伊璃希娅',title:'万象初光',english:'ELYSIUM',role:'创生 · 神佑',hp:520,atk:118,cost:5,kind:'genesis',power:260,fx:'astral',color:'#b8f8ff',ultimate:true,skill:'万象创生',detail:'全体敌人受到260点伤害，全体存活队友恢复120点生命并获得100点护盾，持续两个敌方回合。每场限用一次。',quote:'所有颜色，都曾是同一道光。',story:'在第一颗星诞生之前，她曾将黑暗折射成七种颜色。如今那道初光再次显现，带着所有尚未写下的未来。'}
  );
  if(typeof module!=='undefined'&&module.exports)module.exports=entries;else root.EclipseRoster=entries;
})(typeof globalThis!=='undefined'?globalThis:this);
